// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth-service/v1/dwh-data-auth-request": {
            "get": {
                "description": "获取数仓数据权限申请列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "获取列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "申请人",
                        "name": "applicant",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "数据ID，支持多个",
                        "name": "data_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "申请单名称",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "每页大小 默认 10",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码 默认 1",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "phase",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PageResult-github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto_DataAuthFormListItem"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "创建数仓数据权限申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "创建数仓数据权限申请",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.IDResp"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/dwh-data-auth-request/audit": {
            "get": {
                "description": "获取数仓数据权限申请审核列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "获取审核列表",
                "parameters": [
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向 asc 正序 desc 倒序, 默认 desc",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "每页大小 默认 10",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码 默认 1",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "create_time",
                            "update_time"
                        ],
                        "type": "string",
                        "default": "create_time",
                        "description": "排序类型 create_time 创建时间 update_time 更新时间, 默认 create_time",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "tasks",
                            "historys"
                        ],
                        "type": "string",
                        "description": "审核列表类型 tasks 待审核 historys 已审核",
                        "name": "target",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PageResult-github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto_DataAuthReqFormAuditListItem"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/dwh-data-auth-request/{id}": {
            "get": {
                "description": "获取数仓数据权限申请详情",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "获取数仓数据权限申请详情",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "逻辑视图授权申请 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthFormDetail"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "put": {
                "description": "更新数仓数据权限申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "更新数仓数据权限申请",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "数仓数据权限申请单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestArg"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "撤回数仓数据权限申请审核",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "撤回审核",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数:OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除数仓数据申请单",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "数仓数据权限申请"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "逻辑视图授权申请 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数: OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/enforce": {
            "post": {
                "description": "查询菜单资源的允许的操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "策略"
                ],
                "summary": "查询菜单资源的允许的操作",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyEnforce"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyEnforceEffect"
                            }
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/indicator-dimensional-rules": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "指标维度规则"
                ],
                "summary": "获取指标维度规则",
                "parameters": [
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "x-enum-varnames": [
                            "Ascending",
                            "Descending"
                        ],
                        "description": "排序的方向",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "未指定且非空时返回属于指定指标的维度规则",
                        "name": "indicator_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示的数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，从 1 开始",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "is_authorized"
                        ],
                        "type": "string",
                        "x-enum-varnames": [
                            "IndicatorDimensionalRuleSortIsAuthorized"
                        ],
                        "description": "排序的依据,为空时不排序",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRuleList"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "指标维度规则"
                ],
                "summary": "创建指标维度规则",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRule"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/indicator-dimensional-rules/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "指标维度规则"
                ],
                "summary": "获取指标维度规则",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "指标维度规则 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRule"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "指标维度规则"
                ],
                "summary": "删除指标维度规则",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "指标维度规则 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRule"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/indicator-dimensional-rules/{id}/spec": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "指标维度规则"
                ],
                "summary": "更新指标维度规则 Spec",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "指标维度规则 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRuleSpec"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRule"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/policy": {
            "get": {
                "description": "策略详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "open策略"
                ],
                "summary": "策略详情",
                "parameters": [
                    {
                        "maxLength": 128,
                        "type": "string",
                        "description": "资源id",
                        "name": "object_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "domain",
                            "data_view",
                            "api",
                            "sub_service",
                            "sub_view",
                            "indicator",
                            "indicator_dimensional_rule"
                        ],
                        "type": "string",
                        "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                        "name": "object_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyGetRes"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "put": {
                "description": "策略更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "策略"
                ],
                "summary": "策略更新",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "策略创建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "策略"
                ],
                "summary": "策略创建",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "策略删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "策略"
                ],
                "summary": "策略删除",
                "parameters": [
                    {
                        "maxLength": 128,
                        "type": "string",
                        "description": "资源id",
                        "name": "object_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "domain",
                            "data_view",
                            "api",
                            "sub_service",
                            "sub_view",
                            "indicator",
                            "indicator_dimensional_rule"
                        ],
                        "type": "string",
                        "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                        "name": "object_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "策略ID，多个，支持逗号分割",
                        "name": "policy_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "视图，接口，指标的ID",
                        "name": "source_object_id",
                        "in": "query"
                    },
                    {
                        "maxLength": 128,
                        "type": "string",
                        "description": "访问者id, 不传访问者id, 表示删除资源的全部授权, 传访问者id, 表示仅删除资源下该访问者的授权",
                        "name": "subject_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "app",
                            "user",
                            "department",
                            "role"
                        ],
                        "type": "string",
                        "description": "访问者类型 app 应用 user 用户 department 部门 role 角色",
                        "name": "subject_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/sub-views": {
            "get": {
                "description": "获取用户拥有权限的子视图（行列规则）列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取用户拥有权限的子视图（行列规则）列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "动作，未指定时返回拥有任意动作的权限的子视图（行列规则）列表。\n\nquery 绑定的参数名称是结构体字段名称的单数。",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "逻辑视图名称",
                        "name": "logic_view_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户 ID，获取此用户的有权限的子视图，默认为当前用户从 Authorization 获取。",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ListSubViewsRes"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/auth-service/v1/subject/objects": {
            "get": {
                "description": "访问者拥有的资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "策略"
                ],
                "summary": "访问者拥有的资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "资源id",
                        "name": "object_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标, 多种类型用逗号分隔",
                        "name": "object_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 128,
                        "type": "string",
                        "description": "访问者id",
                        "name": "subject_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "app",
                            "user",
                            "department",
                            "role"
                        ],
                        "type": "string",
                        "description": "访问者类型 app 应用 user 用户 department 部门 role 角色",
                        "name": "subject_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.GetObjectsBySubjectIdRes"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthFormDetail": {
            "type": "object",
            "properties": {
                "applicant": {
                    "description": "申请人",
                    "type": "string"
                },
                "applicant_name": {
                    "description": "申请人",
                    "type": "string"
                },
                "apply_time": {
                    "description": "申请时间",
                    "type": "integer"
                },
                "created_at": {
                    "description": "创建时间, 申请时间",
                    "type": "string"
                },
                "data_business_name": {
                    "description": "库表名称（业务名称）",
                    "type": "string"
                },
                "data_id": {
                    "description": "库表ID",
                    "type": "string"
                },
                "data_tech_name": {
                    "description": "技术名称",
                    "type": "string"
                },
                "draft_expired_at": {
                    "type": "integer"
                },
                "draft_request_type": {
                    "description": "草稿请求类型",
                    "type": "string"
                },
                "draft_spec": {
                    "type": "string"
                },
                "expired_at": {
                    "description": "权限过期时间，前端详情用",
                    "type": "integer"
                },
                "id": {
                    "description": "申请单ID",
                    "type": "string"
                },
                "name": {
                    "description": "申请单名称",
                    "type": "string"
                },
                "request_type": {
                    "description": "请求类型",
                    "type": "string"
                },
                "spec": {
                    "description": "行列规则压缩成的字符串，前端详情使用",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestStatus"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthFormListItem": {
            "type": "object",
            "properties": {
                "applicant": {
                    "description": "申请人",
                    "type": "string"
                },
                "applicant_name": {
                    "description": "申请人",
                    "type": "string"
                },
                "apply_time": {
                    "description": "申请时间",
                    "type": "integer"
                },
                "created_at": {
                    "description": "创建时间, 申请时间",
                    "type": "string"
                },
                "data_business_name": {
                    "description": "库表名称（业务名称）",
                    "type": "string"
                },
                "data_id": {
                    "description": "库表ID",
                    "type": "string"
                },
                "data_tech_name": {
                    "description": "技术名称",
                    "type": "string"
                },
                "id": {
                    "description": "申请单ID",
                    "type": "string"
                },
                "name": {
                    "description": "申请单名称",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestStatus"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthReqFormAuditListItem": {
            "type": "object",
            "properties": {
                "applicant": {
                    "description": "申请人ID",
                    "type": "string"
                },
                "applicant_name": {
                    "description": "申请人名称",
                    "type": "string"
                },
                "apply_id": {
                    "description": "申请ID",
                    "type": "string"
                },
                "apply_time": {
                    "description": "申请时间",
                    "type": "string"
                },
                "audit_status": {
                    "description": "审核状态",
                    "type": "string"
                },
                "audit_time": {
                    "description": "审核时间，2006-01-02 15:04:05",
                    "type": "string"
                },
                "biz_type": {
                    "description": "业务类型, 审核类型",
                    "type": "string"
                },
                "data_business_name": {
                    "description": "库表名称（业务名称）",
                    "type": "string"
                },
                "data_id": {
                    "description": "库表ID",
                    "type": "string"
                },
                "data_tech_name": {
                    "description": "技术名称",
                    "type": "string"
                },
                "id": {
                    "description": "申请单ID",
                    "type": "string"
                },
                "name": {
                    "description": "申请单名称",
                    "type": "string"
                },
                "proc_inst_id": {
                    "description": "审核实例ID",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestArg": {
            "type": "object",
            "required": [
                "data_id",
                "name",
                "request_type"
            ],
            "properties": {
                "data_id": {
                    "description": "库表ID",
                    "type": "string"
                },
                "expired_at": {
                    "description": "权限过期时间时间戳",
                    "type": "integer"
                },
                "name": {
                    "description": "申请单名称",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "request_type": {
                    "description": "申请类型",
                    "type": "string",
                    "enum": [
                        "check",
                        "query"
                    ]
                },
                "spec": {
                    "description": "行列规则压缩成的字符串",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthRequestStatus": {
            "type": "object",
            "properties": {
                "apply_id": {
                    "description": "审核流程 ID",
                    "type": "string",
                    "example": "0194078a-9319-77d1-8229-b27cb5e1e845"
                },
                "message": {
                    "description": "逻辑视图授权申请处于当前阶段的原因，人类可读",
                    "type": "string",
                    "example": "申请被驳回"
                },
                "phase": {
                    "description": "逻辑视图授权申请所处的阶段",
                    "type": "string"
                },
                "proc_def_key": {
                    "description": "审核流程的 key",
                    "type": "string",
                    "example": "Process_VP2LSITg"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Department": {
            "type": "object",
            "properties": {
                "department_id": {
                    "description": "部门id",
                    "type": "string",
                    "example": "01940797-4ee0-7ec9-a053-8ce9e0ad1271"
                },
                "department_name": {
                    "description": "部门名称",
                    "type": "string",
                    "example": "部门名称"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.GetObjectsBySubjectId": {
            "type": "object",
            "required": [
                "object_id",
                "object_type"
            ],
            "properties": {
                "expired_at": {
                    "description": "过期时间，未指定代表永久生效。",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                },
                "permissions": {
                    "description": "权限",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Permission"
                    }
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.GetObjectsBySubjectIdRes": {
            "type": "object",
            "required": [
                "total_count"
            ],
            "properties": {
                "entries": {
                    "description": "对象列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.GetObjectsBySubjectId"
                    }
                },
                "total_count": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.IDResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ListSubViews": {
            "type": "object",
            "properties": {
                "columns": {
                    "description": "子视图的列名称列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "子视图 ID",
                    "type": "string"
                },
                "logic_view_id": {
                    "description": "子视图所属逻辑视图 ID",
                    "type": "string"
                },
                "logic_view_name": {
                    "description": "子视图所属逻辑视图名称",
                    "type": "string"
                },
                "name": {
                    "description": "子视图名称",
                    "type": "string"
                },
                "row_filter_clause": {
                    "description": "行过滤子句",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ListSubViewsRes": {
            "type": "object",
            "required": [
                "total_count"
            ],
            "properties": {
                "entries": {
                    "description": "对象列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ListSubViews"
                    }
                },
                "total_count": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ObjectOwner": {
            "type": "object",
            "properties": {
                "departments": {
                    "description": "所属部门",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Department"
                        }
                    }
                },
                "owner_id": {
                    "description": "ID",
                    "type": "string"
                },
                "owner_name": {
                    "description": "名称",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PageResult-github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto_DataAuthFormListItem": {
            "type": "object",
            "required": [
                "total_count"
            ],
            "properties": {
                "entries": {
                    "description": "对象列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthFormListItem"
                    }
                },
                "total_count": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PageResult-github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto_DataAuthReqFormAuditListItem": {
            "type": "object",
            "required": [
                "total_count"
            ],
            "properties": {
                "entries": {
                    "description": "对象列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.DataAuthReqFormAuditListItem"
                    }
                },
                "total_count": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Permission": {
            "type": "object",
            "required": [
                "action",
                "effect"
            ],
            "properties": {
                "action": {
                    "description": "请求动作 view查看 read读取  download下载 auth授权 allocate授权(仅分配)",
                    "type": "string",
                    "enum": [
                        "view",
                        "read",
                        "download",
                        "auth",
                        "allocate",
                        "apply"
                    ]
                },
                "effect": {
                    "description": "策略结果 allow 允许 deny 拒绝",
                    "type": "string",
                    "enum": [
                        "allow",
                        "deny"
                    ]
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyCreateReq": {
            "type": "object",
            "required": [
                "object_id",
                "object_type",
                "subjects"
            ],
            "properties": {
                "auth_scope_id": {
                    "description": "授权范围",
                    "type": "string"
                },
                "auth_scope_type": {
                    "description": "授权范围资源的类型",
                    "type": "string"
                },
                "department_id": {
                    "description": "资源的部门，不是子资源的",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128,
                    "example": "01940795-d488-77ea-ab48-689d2683a623"
                },
                "object_name": {
                    "description": "资源名称",
                    "type": "string",
                    "maxLength": 128,
                    "example": "东区销售数据"
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                },
                "owner_departments": {
                    "description": "数据Owner所属部门",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Department"
                        }
                    }
                },
                "owner_id": {
                    "description": "数据OwnerId",
                    "type": "string",
                    "example": "01940796-7bc2-7462-81eb-c7e6399f08fb"
                },
                "owner_name": {
                    "description": "数据Owner名称",
                    "type": "string",
                    "example": "用户名称"
                },
                "owners": {
                    "description": "数据的 Owner 列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ObjectOwner"
                    }
                },
                "source_object_id": {
                    "type": "string",
                    "example": "视图，接口，指标的ID"
                },
                "subjects": {
                    "description": "访问者",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject"
                    }
                },
                "subjects_extend": {
                    "description": "继承权限的访问者",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject"
                    }
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyEnforce": {
            "type": "object",
            "required": [
                "action",
                "object_id",
                "object_type",
                "subject_id",
                "subject_type"
            ],
            "properties": {
                "action": {
                    "description": "请求动作 view 查看 read 读取 download 下载",
                    "type": "string",
                    "enum": [
                        "view",
                        "read",
                        "download",
                        "auth",
                        "allocate",
                        "apply"
                    ]
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                },
                "subject_id": {
                    "description": "访问者id",
                    "type": "string",
                    "maxLength": 128
                },
                "subject_type": {
                    "description": "访问者类型 app 应用 user 用户 department 部门 role 角色",
                    "type": "string",
                    "enum": [
                        "app",
                        "user",
                        "department",
                        "role"
                    ]
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyEnforceEffect": {
            "type": "object",
            "required": [
                "action",
                "object_id",
                "object_type",
                "subject_id",
                "subject_type"
            ],
            "properties": {
                "action": {
                    "description": "请求动作 view 查看 read 读取 download 下载",
                    "type": "string",
                    "enum": [
                        "view",
                        "read",
                        "download",
                        "auth",
                        "allocate",
                        "apply"
                    ]
                },
                "effect": {
                    "description": "策略结果 allow 允许 deny 拒绝",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                },
                "subject_id": {
                    "description": "访问者id",
                    "type": "string",
                    "maxLength": 128
                },
                "subject_type": {
                    "description": "访问者类型 app 应用 user 用户 department 部门 role 角色",
                    "type": "string",
                    "enum": [
                        "app",
                        "user",
                        "department",
                        "role"
                    ]
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyGetRes": {
            "type": "object",
            "required": [
                "object_id",
                "object_type",
                "subjects"
            ],
            "properties": {
                "auth_scope_id": {
                    "description": "授权范围",
                    "type": "string"
                },
                "auth_scope_type": {
                    "description": "授权范围资源的类型",
                    "type": "string"
                },
                "department_id": {
                    "description": "资源的部门，不是子资源的",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128,
                    "example": "01940795-d488-77ea-ab48-689d2683a623"
                },
                "object_name": {
                    "description": "资源名称",
                    "type": "string",
                    "maxLength": 128,
                    "example": "东区销售数据"
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                },
                "owner_departments": {
                    "description": "数据Owner所属部门",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Department"
                        }
                    }
                },
                "owner_id": {
                    "description": "数据OwnerId",
                    "type": "string",
                    "example": "01940796-7bc2-7462-81eb-c7e6399f08fb"
                },
                "owner_name": {
                    "description": "数据Owner名称",
                    "type": "string",
                    "example": "用户名称"
                },
                "owners": {
                    "description": "数据的 Owner 列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ObjectOwner"
                    }
                },
                "source_object_id": {
                    "type": "string",
                    "example": "视图，接口，指标的ID"
                },
                "subjects": {
                    "description": "访问者",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject"
                    }
                },
                "subjects_extend": {
                    "description": "继承权限的访问者",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject"
                    }
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.PolicyUpdateReq": {
            "type": "object",
            "required": [
                "object_id",
                "object_type"
            ],
            "properties": {
                "auth_scope_id": {
                    "description": "授权范围",
                    "type": "string"
                },
                "auth_scope_type": {
                    "description": "授权范围资源的类型",
                    "type": "string"
                },
                "department_id": {
                    "description": "资源的部门，不是子资源的",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128,
                    "example": "01940795-d488-77ea-ab48-689d2683a623"
                },
                "object_name": {
                    "description": "资源名称",
                    "type": "string",
                    "maxLength": 128,
                    "example": "东区销售数据"
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                },
                "owner_departments": {
                    "description": "数据Owner所属部门",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Department"
                        }
                    }
                },
                "owner_id": {
                    "description": "数据OwnerId",
                    "type": "string",
                    "example": "01940796-7bc2-7462-81eb-c7e6399f08fb"
                },
                "owner_name": {
                    "description": "数据Owner名称",
                    "type": "string",
                    "example": "用户名称"
                },
                "owners": {
                    "description": "数据的 Owner 列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.ObjectOwner"
                    }
                },
                "partial": {
                    "description": "是否只修改指定 subjects 的权限。false 将移除 subjects 未指定的用户、应用的权限",
                    "type": "boolean"
                },
                "preserve_expired_at": {
                    "description": "是否保持权限的过期时间不变。",
                    "type": "boolean"
                },
                "source_object_id": {
                    "type": "string",
                    "example": "视图，接口，指标的ID"
                },
                "subjects": {
                    "description": "访问者",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject"
                    }
                },
                "subjects_extend": {
                    "description": "继承权限的访问者",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject"
                    }
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.RulePolicyEnforce": {
            "type": "object",
            "required": [
                "action",
                "object_id",
                "object_type",
                "user_id"
            ],
            "properties": {
                "action": {
                    "description": "请求动作 view 查看 read 读取 download 下载",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户UID",
                    "type": "string"
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.RulePolicyEnforceEffect": {
            "type": "object",
            "required": [
                "action",
                "object_id",
                "object_type"
            ],
            "properties": {
                "action": {
                    "description": "请求动作 view 查看 read 读取 download 下载",
                    "type": "string",
                    "enum": [
                        "view",
                        "read",
                        "download",
                        "allocate",
                        "auth",
                        "apply"
                    ]
                },
                "effect": {
                    "description": "策略结果 allow 允许 deny 拒绝",
                    "type": "string"
                },
                "object_id": {
                    "description": "资源id",
                    "type": "string",
                    "maxLength": 128
                },
                "object_type": {
                    "description": "资源类型 domain 主题域 data_view 逻辑视图 api 接口 sub_view 子视图 indicator 指标",
                    "type": "string",
                    "enum": [
                        "domain",
                        "data_view",
                        "api",
                        "sub_service",
                        "sub_view",
                        "indicator",
                        "indicator_dimensional_rule"
                    ]
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Subject": {
            "type": "object",
            "required": [
                "permissions",
                "subject_id",
                "subject_type"
            ],
            "properties": {
                "departments": {
                    "description": "所属部门",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Department"
                        }
                    }
                },
                "expired_at": {
                    "description": "过期时间，未指定代表永久生效。",
                    "type": "string"
                },
                "permissions": {
                    "description": "权限设置",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.Permission"
                    }
                },
                "policy_id": {
                    "description": "策略ID，由ISF返回的，用来更新的",
                    "type": "string"
                },
                "subject_id": {
                    "description": "访问者id",
                    "type": "string",
                    "maxLength": 128,
                    "example": "01940797-fc33-76ad-98c4-f9e4457ace03"
                },
                "subject_name": {
                    "description": "访问者名称",
                    "type": "string",
                    "maxLength": 128,
                    "example": "访问者名称"
                },
                "subject_type": {
                    "description": "访问者类型 app 应用 user 用户 department 部门 role 角色",
                    "type": "string",
                    "enum": [
                        "app",
                        "user",
                        "department",
                        "role"
                    ]
                },
                "user_status": {
                    "description": "用户状态，仅当访问者类型 SubjectType 是 user 时有值",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.UserStatus"
                        }
                    ]
                }
            }
        },
        "github_com_kweaver-ai_dsg_services_apps_auth-service_common_dto.UserStatus": {
            "type": "string",
            "enum": [
                "Unknown",
                "Normal",
                "Deleted"
            ],
            "x-enum-comments": {
                "UserDeleted": "已删除",
                "UserNormal": "正常",
                "UserUnknown": "未知"
            },
            "x-enum-varnames": [
                "UserUnknown",
                "UserNormal",
                "UserDeleted"
            ]
        },
        "github_com_kweaver-ai_idrm-go-common_api_meta_v1.Direction": {
            "type": "string",
            "enum": [
                "asc",
                "desc"
            ],
            "x-enum-varnames": [
                "Ascending",
                "Descending"
            ]
        },
        "rest.HttpError": {
            "type": "object",
            "properties": {
                "cause": {
                    "description": "错误原因",
                    "type": "string",
                    "x-omitempty": false,
                    "example": "错误原因"
                },
                "code": {
                    "description": "返回错误码，格式: 服务名.模块.错误",
                    "type": "string",
                    "example": "task-center.Public.InternalError"
                },
                "description": {
                    "description": "错误描述",
                    "type": "string",
                    "example": "内部错误"
                },
                "detail": {
                    "description": "错误详情, 一般是json对象",
                    "x-omitempty": false
                },
                "solution": {
                    "description": "错误处理办法",
                    "type": "string",
                    "x-omitempty": false,
                    "example": "请联系内部人员"
                }
            }
        },
        "v1.Field": {
            "type": "object",
            "properties": {
                "data_type": {
                    "description": "数据类型,由逻辑视图定义。",
                    "type": "string"
                },
                "id": {
                    "description": "字段 ID",
                    "type": "string"
                },
                "name": {
                    "description": "中文名称、业务名称",
                    "type": "string"
                },
                "name_en": {
                    "description": "英文名称、技术名称",
                    "type": "string"
                }
            }
        },
        "v1.IndicatorDimensionalRule": {
            "type": "object",
            "properties": {
                "metadata": {
                    "description": "元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.Metadata"
                        }
                    ]
                },
                "spec": {
                    "description": "指标维度规则的内容",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.IndicatorDimensionalRuleSpec"
                        }
                    ]
                }
            }
        },
        "v1.IndicatorDimensionalRuleList": {
            "type": "object",
            "properties": {
                "entries": {
                    "description": "对象列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.IndicatorDimensionalRule"
                    }
                },
                "total_count": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "v1.IndicatorDimensionalRuleSort": {
            "type": "string",
            "enum": [
                "is_authorized"
            ],
            "x-enum-varnames": [
                "IndicatorDimensionalRuleSortIsAuthorized"
            ]
        },
        "v1.IndicatorDimensionalRuleSpec": {
            "type": "object",
            "properties": {
                "auth_scope_id": {
                    "description": "上一级的范围ID",
                    "type": "string",
                    "example": "0"
                },
                "can_auth": {
                    "description": "当前用户是否有该指标维度的授权权限",
                    "type": "boolean"
                },
                "fields": {
                    "description": "列、字段列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Field"
                    }
                },
                "fixed_row_filters": {
                    "description": "固定的行过滤规则",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.RowFilters"
                        }
                    ]
                },
                "indicator_id": {
                    "description": "维度规则所属指标的 ID",
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "row_filters": {
                    "description": "行过滤规则，nil 代表没有过滤规则",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.RowFilters"
                        }
                    ]
                },
                "scope_fields": {
                    "description": "固定范围的字段，",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1.Member": {
            "type": "object",
            "properties": {
                "data_type": {
                    "description": "数据类型,由逻辑视图定义。",
                    "type": "string"
                },
                "id": {
                    "description": "字段 ID",
                    "type": "string"
                },
                "name": {
                    "description": "中文名称、业务名称",
                    "type": "string"
                },
                "name_en": {
                    "description": "英文名称、技术名称",
                    "type": "string"
                },
                "operator": {
                    "description": "限定条件",
                    "type": "string"
                },
                "value": {
                    "description": "限定比较值",
                    "type": "string"
                }
            }
        },
        "v1.Metadata": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "删除时间。当用户请求优雅删除时，服务器会设置这个字段，并不是由用户直接设\n置。",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "v1.RowFilters": {
            "type": "object",
            "properties": {
                "where": {
                    "description": "条件组列表\n\n前端要求空列表序列化 json 为 ` + "`" + `[]` + "`" + ` 所以不能使用 json tag omitempty",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Where"
                    }
                },
                "where_relation": {
                    "description": "条件组间关系",
                    "type": "string"
                }
            }
        },
        "v1.Where": {
            "type": "object",
            "properties": {
                "member": {
                    "description": "限定对象",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Member"
                    }
                },
                "relation": {
                    "description": "限定关系",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "auth-service",
	Description:      "AnyFabric auth service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
