// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameClassificationRuleAlgorithmRelation = "classification_rule_algorithm_relation"

// ClassificationRuleAlgorithmRelation 分类规则算法关系
type ClassificationRuleAlgorithmRelation struct {
	ClassificationRuleAlgorithmRelationID int64  `gorm:"column:classification_rule_algorithm_relation_id;primaryKey;comment:分类规则算法关系雪花id" json:"classification_rule_algorithm_relation_id"` // 分类规则算法关系雪花id
	ID                                    string `gorm:"column:id;not null;comment:分类规则算法关系uuid" json:"id"`                                                                                 // 分类规则算法关系uuid
	ClassificationRuleID                  string `gorm:"column:classification_rule_id;not null;comment:分类规则uuid" json:"classification_rule_id"`                                             // 分类规则uuid
	RecognitionAlgorithmID                string `gorm:"column:recognition_algorithm_id;not null;comment:识别算法uuid" json:"recognition_algorithm_id"`                                         // 识别算法uuid
	Status                                int32  `gorm:"column:status;not null;comment:0停用1启用" json:"status"`                                                                               // 0停用1启用
	DeletedAt                             int64  `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`                                                                         // 删除时间
}

// TableName ClassificationRuleAlgorithmRelation's table name
func (*ClassificationRuleAlgorithmRelation) TableName() string {
	return TableNameClassificationRuleAlgorithmRelation
}

func (c *ClassificationRuleAlgorithmRelation) BeforeCreate(tx *gorm.DB) (err error) {
	if c.ID == "" {
		c.ID = uuid.NewString()
	}
	if c.ClassificationRuleAlgorithmRelationID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		c.ClassificationRuleAlgorithmRelationID, err = int64(uniqueID), idErr
	}

	return
}
