// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameClassificationFieldRefuseHistory = "classification_field_refuse_history"

// ClassificationFieldRefuseHistory 分类字段拒绝推荐记录表
type ClassificationFieldRefuseHistory struct {
	ClassificationFieldRefuseHistoryID int64     `gorm:"column:classification_field_refuse_history_id;primaryKey;comment:分类字段拒绝推荐记录雪花id" json:"classification_field_refuse_history_id"` // 分类字段拒绝推荐记录雪花id
	ID                                 string    `gorm:"column:id;not null;comment:分类字段拒绝推荐记录uuid" json:"id"`                                                                           // 分类字段拒绝推荐记录uuid
	ClassificationID                   string    `gorm:"column:classification_id;not null;comment:分类属性uuid" json:"classification_id"`                                                   // 分类属性uuid
	FormViewFieldID                    string    `gorm:"column:form_view_field_id;not null;comment:视图字段uuid" json:"form_view_field_id"`                                                 // 视图字段uuid
	CreatedAt                          time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                                              // 创建时间
}

// TableName ClassificationFieldRefuseHistory's table name
func (*ClassificationFieldRefuseHistory) TableName() string {
	return TableNameClassificationFieldRefuseHistory
}

func (c *ClassificationFieldRefuseHistory) BeforeCreate(tx *gorm.DB) (err error) {
	if c.ID == "" {
		c.ID = uuid.NewString()
	}
	if c.ClassificationFieldRefuseHistoryID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		c.ClassificationFieldRefuseHistoryID, err = int64(uniqueID), idErr
	}
	if c.CreatedAt.IsZero() {
		c.CreatedAt = time.Now()
	}
	return
}
