// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameClassificationRule = "classification_rule"

// ClassificationRule 分类规则表
type ClassificationRule struct {
	ClassificationRuleID int64     `gorm:"column:classification_rule_id;primaryKey;comment:分类规则雪花id" json:"classification_rule_id"` // 分类规则雪花id
	ID                   string    `gorm:"column:id;not null;comment:分类规则uuid" json:"id"`                                           // 分类规则uuid
	Name                 string    `gorm:"column:name;comment:分类规则名称" json:"name"`                                                  // 分类规则名称
	Description          string    `gorm:"column:description;comment:分类规则描述" json:"description"`                                    // 分类规则描述
	Type                 string    `gorm:"column:type;comment:分类规则类型" json:"type"`                                                  // 分类规则类型
	SubjectID            string    `gorm:"column:subject_id;not null;comment:分类属性uuid" json:"subject_id"`                           // 分类属性uuid
	Status               int32     `gorm:"column:status;not null;comment:0停用1启用" json:"status"`                                     // 0停用1启用
	CreatedAt            time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                        // 创建时间
	CreatedByUID         string    `gorm:"column:created_by_uid;comment:创建用户id" json:"created_by_uid"`                              // 创建用户id
	UpdatedAt            time.Time `gorm:"column:updated_at;autoUpdateTime;comment:修改时间" json:"updated_at"`                         // 修改时间
	UpdatedByUID         string    `gorm:"column:updated_by_uid;comment:修改用户id" json:"updated_by_uid"`                              // 修改用户id
	DeletedAt            int64     `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`                               // 删除时间
}

// TableName ClassificationRule's table name
func (*ClassificationRule) TableName() string {
	return TableNameClassificationRule
}

func (c *ClassificationRule) BeforeCreate(tx *gorm.DB) (err error) {
	if c.ID == "" {
		c.ID = uuid.NewString()
	}
	if c.ClassificationRuleID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		c.ClassificationRuleID, err = int64(uniqueID), idErr
	}
	if c.CreatedAt.IsZero() {
		c.CreatedAt = time.Now()
	}
	if c.UpdatedAt.IsZero() {
		c.UpdatedAt = time.Now()
	}
	return
}

func (c *ClassificationRule) BeforeUpdate(tx *gorm.DB) (err error) {
	if c.UpdatedAt.IsZero() {
		c.UpdatedAt = time.Now()
	}
	return
}
