// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameDataPreviewConfig = "data_preview_config"

// DataPreviewConfig mapped from table <data_preview_config>
type DataPreviewConfig struct {
	ID         uint64 `gorm:"column:id;primaryKey;comment:雪花id" json:"id"`                     // 雪花id
	FormViewID string `gorm:"column:form_view_id;not null;comment:逻辑视图id" json:"form_view_id"` // 逻辑视图id
	CreatorUID string `gorm:"column:creator_uid;not null;comment:用户ID" json:"creator_uid"`     // 用户ID
	Config     string `gorm:"column:config;comment:数据预览配置" json:"config"`                      // 数据预览配置
}

// TableName DataPreviewConfig's table name
func (*DataPreviewConfig) TableName() string {
	return TableNameDataPreviewConfig
}

func (e *DataPreviewConfig) BeforeCreate(_ *gorm.DB) error {
	if e == nil {
		return nil
	}
	var err error
	if e.ID == 0 {
		e.ID, err = utilities.GetUniqueID()
	}
	return err
}
