// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameDataPrivacyPolicy = "data_privacy_policy"

// DataPrivacyPolicy 数据隐私策略表
type DataPrivacyPolicy struct {
	DataPrivacyPolicyID int64     `gorm:"column:data_privacy_policy_id;primaryKey;comment:数据隐私策略雪花id" json:"data_privacy_policy_id"` // 数据隐私策略雪花id
	ID                  string    `gorm:"column:id;not null;comment:数据隐私策略uuid" json:"id"`                                           // 数据隐私策略uuid
	FormViewID          string    `gorm:"column:form_view_id;not null;comment:待脱敏数据视图雪花id" json:"form_view_id"`                      // 待脱敏数据视图雪花id
	PolicyDescription   string    `gorm:"column:policy_description;comment:隐私策略描述" json:"policy_description"`                        // 隐私策略描述
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:current_timestamp();comment:创建时间" json:"created_at"`     // 创建时间
	CreatedByUID        string    `gorm:"column:created_by_uid;comment:创建用户id" json:"created_by_uid"`                                // 创建用户id
	UpdatedAt           time.Time `gorm:"column:updated_at;not null;autoUpdateTime;comment:修改时间" json:"updated_at"`                  // 修改时间
	UpdatedByUID        string    `gorm:"column:updated_by_uid;comment:修改用户id" json:"updated_by_uid"`                                // 修改用户id
	DeletedAt           int64     `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`                                 // 删除时间
}

// TableName DataPrivacyPolicy's table name
func (*DataPrivacyPolicy) TableName() string {
	return TableNameDataPrivacyPolicy
}

func (d *DataPrivacyPolicy) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.DataPrivacyPolicyID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		d.DataPrivacyPolicyID, err = int64(uniqueID), idErr
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}

func (d *DataPrivacyPolicy) BeforeUpdate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return nil
}
