// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameDataClassifyAttrBlacklist = "data_classify_attribute_blacklist"

// DataClassifyAttrBlacklist mapped from table <data_classify_attribute_blacklist>
type DataClassifyAttrBlacklist struct {
	ID         uint64    `gorm:"column:id;primaryKey" json:"id"`                                                         // 黑名单记录id
	FormViewID string    `gorm:"column:form_view_id;comment:视图id" json:"form_view_id"`                                   // 视图id
	FieldID    string    `gorm:"column:field_id;not null;comment:字段id" json:"field_id"`                                  // 字段id
	SubjectID  string    `gorm:"column:subject_id;not null;comment:关联逻辑实体属性ID（L5）" json:"subject_id"`                    // 关联逻辑实体属性ID（L5）
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"` // 创建时间
}

// TableName TmpExploreSubTask's table name
func (*DataClassifyAttrBlacklist) TableName() string {
	return TableNameDataClassifyAttrBlacklist
}

func (d *DataClassifyAttrBlacklist) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		d.ID, err = utilities.GetUniqueID()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	return err
}
