// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameDataPrivacyPolicyField = "data_privacy_policy_field"

// DataPrivacyPolicyField 数据隐私策略字段表
type DataPrivacyPolicyField struct {
	DataPrivacyPolicyFieldID int64  `gorm:"column:data_privacy_policy_field_id;primaryKey;comment:隐私策略字段雪花id" json:"data_privacy_policy_field_id"` // 隐私策略字段雪花id
	ID                       string `gorm:"column:id;not null;comment:隐私策略字段uuid" json:"id"`                                                       // 隐私策略字段uuid
	DataPrivacyPolicyID      string `gorm:"column:data_privacy_policy_id;not null;comment:隐私策略uuid" json:"data_privacy_policy_id"`                 // 隐私策略uuid
	FormViewFieldID          string `gorm:"column:form_view_field_id;not null;comment:视图字段uuid" json:"form_view_field_id"`                         // 视图字段uuid
	DesensitizationRuleID    string `gorm:"column:desensitization_rule_id;not null;comment:脱敏规则uuid" json:"desensitization_rule_id"`               // 脱敏规则uuid
	DeletedAt                int64  `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`                                             // 删除时间
}

// TableName DataPrivacyPolicyField's table name
func (*DataPrivacyPolicyField) TableName() string {
	return TableNameDataPrivacyPolicyField
}

func (d *DataPrivacyPolicyField) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.DataPrivacyPolicyFieldID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		d.DataPrivacyPolicyFieldID, err = int64(uniqueID), idErr
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	return err
}
