// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameDepartmentExploreReport = "department_explore_report"

// DepartmentExploreReport mapped from table <department_explore_report>
type DepartmentExploreReport struct {
	ID                   uint64   `gorm:"column:id;primaryKey;comment:id,uuid" json:"id"`                            // id,uuid
	DepartmentID         string   `gorm:"column:department_id;not null;comment:部门id" json:"department_id"`           // 部门id
	TotalViews           int64    `gorm:"column:total_views;not null;comment:视图总量" json:"total_views"`               // 视图总量
	ExploredViews        int64    `gorm:"column:explored_views;not null;comment:已探查成功视图数" json:"explored_views"`     // 已探查成功视图数
	TotalScore           *float64 `gorm:"column:f_total_score;comment:总分" json:"total_score"`                        // 总分
	TotalCompleteness    *float64 `gorm:"column:f_total_completeness;comment:完整性总分" json:"total_completeness"`       // 完整性总分
	TotalStandardization *float64 `gorm:"column:f_total_standardization;comment:规范性总分" json:"total_standardization"` // 规范性总分
	TotalUniqueness      *float64 `gorm:"column:f_total_uniqueness;comment:唯一性总分" json:"total_uniqueness"`           // 唯一性总分
	TotalAccuracy        *float64 `gorm:"column:f_total_accuracy;comment:准确性总分" json:"total_accuracy"`               // 准确性总分
	TotalConsistency     *float64 `gorm:"column:f_total_consistency;comment:一致性总分" json:"total_consistency"`         // 一致性总分
}

func (d *DepartmentExploreReport) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		d.ID, err = utilities.GetUniqueID()
	}
	return err
}

// TableName DepartmentExploreReport's table name
func (*DepartmentExploreReport) TableName() string {
	return TableNameDepartmentExploreReport
}
