// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameDesensitizationRule = "desensitization_rule"

// DesensitizationRule mapped from table <desensitization_rule>
type DesensitizationRule struct {
	DesensitizationRuleID uint64    `gorm:"column:desensitization_rule_id;primaryKey;comment:脱敏规则id, 雪花id" json:"desensitization_rule_id"` // 脱敏规则id, 雪花id
	ID                    string    `gorm:"column:id;not null;comment:脱敏规则id, uuid" json:"id"`                                             // 脱敏规则id, uuid
	Name                  string    `gorm:"column:name" json:"name"`
	Description           string    `gorm:"column:description;comment:描述信息" json:"description"`              // 描述信息
	Type                  string    `gorm:"column:type;comment:算法类型，自定义；内置" json:"type"`                     // 算法类型，自定义；内置
	InnerType             string    `gorm:"column:inner_type;comment:内置类型：身份证、手机、邮箱" json:"inner_type"`      // 内置类型：身份证、手机、邮箱
	Algorithm             string    `gorm:"column:algorithm;comment:脱敏规则算法内容，正则" json:"algorithm"`           // 脱敏规则算法内容，正则
	Method                string    `gorm:"column:method;comment:脱敏方式，首尾、中间、全部" json:"method"`               // 脱敏方式，首尾、中间、全部
	MiddleBit             int32     `gorm:"column:middle_bit;comment:中间脱敏位数" json:"middle_bit"`              // 中间脱敏位数
	HeadBit               int32     `gorm:"column:head_bit;comment:头部位数" json:"head_bit"`                    // 头部位数
	TailBit               int32     `gorm:"column:tail_bit;comment:尾部位数" json:"tail_bit"`                    // 尾部位数
	CreatedAt             time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                // 创建时间
	CreatedByUID          string    `gorm:"column:created_by_uid;comment:创建者id" json:"created_by_uid"`       // 创建者id
	UpdatedAt             time.Time `gorm:"column:updated_at;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	UpdatedByUID          string    `gorm:"column:updated_by_uid;comment:更新者id" json:"updated_by_uid"`       // 更新者id
	DeletedAt             int32     `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                // 删除时间
}

type DesensitizationRuleRelate struct {
	DesensitizationRuleId   string `gorm:"column:desensitization_rule_id;not null;comment:脱敏规则id, uuid" json:"desensitization_rule_id"` // 脱敏规则id, uuid
	DesensitizationRuleName string `gorm:"column:desensitization_rule_name" json:"desensitization_rule_name"`
	Description             string `gorm:"column:description;comment:描述信息" json:"description"`             // 描述信息
	PrivacyPolicyId         string `gorm:"column:privacy_policy_id;comment:描述信息" json:"privacy_policy_id"` // 描述信息
	FormViewId              string `gorm:"column:form_view_id;comment:描述信息" json:"form_view_id"`           // 描述信息
}

// TableName DesensitizationRule's table name
func (*DesensitizationRule) TableName() string {
	return TableNameDesensitizationRule
}

func (d *DesensitizationRule) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.DesensitizationRuleID == 0 {
		d.DesensitizationRuleID, err = utilities.GetUniqueID()
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}

//func (d *DesensitizationRule) BeforeUpdate(_ *gorm.DB) error {
//	if d == nil {
//		return nil
//	}
//	if d.UpdatedAt.IsZero() {
//		d.UpdatedAt = time.Now()
//	}
//	return nil
//}
