// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameExploreTask = "explore_task"

// ExploreTask mapped from table <explore_task>
type ExploreTask struct {
	ID           uint64                `gorm:"column:id;primaryKey" json:"id"`
	TaskID       string                `gorm:"column:task_id;not null;comment:探查任务id" json:"task_id"`                                                                         // 探查任务id
	Type         int32                 `gorm:"column:type;not null;comment:探查任务类型，1：explore_data(探查数据)；2：explore_timestamp(探查业务更新时间)；" json:"type"`                           // 探查任务类型，1：explore_data(探查数据)；2：explore_timestamp(探查业务更新时间)；
	DatasourceID string                `gorm:"column:datasource_id;comment:数据源id" json:"datasource_id"`                                                                       // 数据源id
	SubjectIDS   string                `gorm:"column:subject_ids;comment:分类属性id" json:"subject_ids"`                                                                          // 分类属性id
	FormViewID   string                `gorm:"column:form_view_id;comment:视图id" json:"form_view_id"`                                                                          // 视图id
	FormViewType int32                 `gorm:"column:form_view_type;comment:视图来源, 1：元数据视图；2：自定义视图；3：逻辑实体视图；" json:"form_view_type"`                                           // 视图来源, 1：元数据视图；2：自定义视图；3：逻辑实体视图；
	WorkOrderID  string                `gorm:"column:work_order_id;comment:工单id" json:"work_order_id"`                                                                        // 工单id
	Status       int32                 `gorm:"column:status;not null;comment:任务状态，1：queuing（等待中）；2：running（进行中）；3：finished（已完成）；4：canceled（已取消）；5：failed（异常）；" json:"status"` // 任务状态，1：queuing（等待中）；2：running（进行中）；3：finished（已完成）；4：canceled（已取消）；5：failed（异常）；
	Config       string                `gorm:"column:config;comment:探查配置" json:"config"`                                                                                      // 探查配置
	Remark       string                `gorm:"column:remark;comment:执行失败说明" json:"remark"`                                                                                    // 执行失败说明
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"`                                        // 创建时间
	CreatedByUID string                `gorm:"column:created_by_uid;not null;comment:创建人" json:"created_by_uid"`                                                              // 创建人
	FinishedAt   *time.Time            `gorm:"column:finished_at;comment:结束时间" json:"finished_at"`                                                                            // 结束时间
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;softDelete:milli;comment:删除时间" json:"deleted_at"`                                                             // 删除时间
}

// TableName ExploreTask's table name
func (*ExploreTask) TableName() string {
	return TableNameExploreTask
}

func (e *ExploreTask) BeforeCreate(_ *gorm.DB) error {
	if e == nil {
		return nil
	}
	var err error
	if e.ID == 0 {
		e.ID, err = utilities.GetUniqueID()
	}
	if len(e.TaskID) == 0 {
		e.TaskID = uuid.NewString()
	}
	if e.CreatedAt.IsZero() {
		e.CreatedAt = time.Now()
	}
	e.FinishedAt = nil
	return err
}
