// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameExploreRuleConfig = "explore_rule_config"

// ExploreRuleConfig mapped from table <explore_rule_config>
type ExploreRuleConfig struct {
	ID              uint64                `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                              // 主键
	RuleID          string                `gorm:"column:rule_id;comment:规则id" json:"rule_id"`                                             // 规则id
	RuleName        string                `gorm:"column:rule_name;not null;comment:规则名称" json:"rule_name"`                                // 规则名称
	RuleDescription string                `gorm:"column:rule_description;comment:规则描述" json:"rule_description"`                           // 规则描述
	RuleLevel       int32                 `gorm:"column:rule_level;not null;comment:规则级别" json:"rule_level"`                              // 规则级别
	FormViewID      string                `gorm:"column:form_view_id;comment:视图id" json:"form_view_id"`                                   // 视图id
	FieldID         string                `gorm:"column:field_id;comment:字段id" json:"field_id"`                                           // 字段id
	Dimension       int32                 `gorm:"column:dimension;not null;comment:维度" json:"dimension"`                                  // 维度
	DimensionType   int32                 `gorm:"column:dimension_type;comment:维度类型" json:"dimension_type"`                               // 维度类型
	RuleConfig      *string               `gorm:"column:rule_config;comment:规则配置" json:"rule_config"`                                     // 规则配置
	Enable          int32                 `gorm:"column:enable;not null;comment:是否启用" json:"enable"`                                      // 是否启用
	Draft           int32                 `gorm:"column:draft;comment:是否草稿" json:"draft"`                                                 // 是否草稿
	TemplateID      string                `gorm:"column:template_id;comment:模板id" json:"template_id"`                                     // 模板id
	CreatedAt       time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"` // 创建时间
	CreatedByUID    string                `gorm:"column:created_by_uid;comment:创建人" json:"created_by_uid"`                                // 创建人
	UpdatedAt       time.Time             `gorm:"column:updated_at;not null;autoUpdateTime;comment:修改时间" json:"updated_at"`               // 修改时间
	UpdatedByUID    string                `gorm:"column:updated_by_uid;comment:修改人" json:"updated_by_uid"`                                // 修改人
	DeletedAt       soft_delete.DeletedAt `gorm:"column:deleted_at;softDelete:milli;comment:删除时间" json:"deleted_at"`                      // 删除时间
}

func (e *ExploreRuleConfig) BeforeCreate(_ *gorm.DB) error {
	if e == nil {
		return nil
	}
	var err error
	if e.ID == 0 {
		e.ID, err = utilities.GetUniqueID()
	}
	if len(e.RuleID) == 0 {
		e.RuleID = uuid.NewString()
	}

	return err
}

// TableName ExploreRuleConfig's table name
func (*ExploreRuleConfig) TableName() string {
	return TableNameExploreRuleConfig
}
