// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameFormViewSql = "form_view_sql"

// FormViewSql mapped from table <form_view_sql>
type FormViewSql struct {
	ID         uint64 `gorm:"column:id;primaryKey;comment:雪花id" json:"id"`                                 // 雪花id
	FormViewID string `gorm:"column:form_view_id;not null;comment:视图id（逻辑实体视图及自定义视图）" json:"form_view_id"` // 视图id（逻辑实体视图及自定义视图）
	Sql        string `gorm:"column:sql;not null;comment:生成视图sql" json:"sql"`                              // 生成视图sql
}

// TableName FormViewField's table name
func (*FormViewSql) TableName() string {
	return TableNameFormViewSql
}

func (d *FormViewSql) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		if d.ID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	return err
}
