// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameGradeRuleGroup = "grade_rule_group"

// GradeRuleGroup 分级规则组表
type GradeRuleGroup struct {
	ID               string    `gorm:"column:id;primaryKey;comment:规则组uuid" json:"id"`                                        // 规则组uuid
	Name             string    `gorm:"column:name;not null;comment:规则组名称" json:"name"`                                       // 规则组名称
	Description      string    `gorm:"column:description;default:'';comment:规则组描述" json:"description"`                       // 规则组描述
	BusinessObjectID string    `gorm:"column:business_object_id;not null;comment:分级规则雪花id" json:"business_object_id"`        // 分级规则雪花id
	CreatedAt        time.Time `gorm:"column:created_at;default:current_timestamp();comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt        int64     `gorm:"column:deleted_at;not null;default:0;comment:删除时间" json:"deleted_at"`                   // 删除时间
}

func (g *GradeRuleGroup) BeforeCreate(tx *gorm.DB) (err error) {
	if g.ID == "" {
		g.ID = uuid.NewString()
	}
	return
}

// TableName GradeRuleGroup's table name
func (*GradeRuleGroup) TableName() string {
	return TableNameGradeRuleGroup
}
