// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameGradeRule = "grade_rule"

// GradeRule 分级规则表
type GradeRule struct {
	GradeRuleID       int64     `gorm:"column:grade_rule_id;primaryKey;comment:分级规则雪花id" json:"grade_rule_id"`                 // 分级规则雪花id
	ID                string    `gorm:"column:id;not null;default:'';comment:分级规则uuid" json:"id"`                              // 分级规则uuid
	Name              string    `gorm:"column:name;default:NULL;comment:分级规则名称" json:"name"`                                   // 分级规则名称
	Description       string    `gorm:"column:description;default:NULL;comment:分级规则描述" json:"description"`                     // 分级规则描述
	SubjectID         string    `gorm:"column:subject_id;not null;default:'';comment:分级属性uuid" json:"subject_id"`              // 分级属性uuid
	LabelID           int64     `gorm:"column:label_id;not null;default:0;comment:分级标签uuid" json:"label_id"`                   // 分级标签uuid
	LogicalExpression string    `gorm:"column:logical_expression;not null;default:'';comment:逻辑表达式" json:"logical_expression"` // 逻辑表达式
	Type              string    `gorm:"column:type;not null;default:'';comment:类型" json:"type"`                                // 类型
	GroupID           string    `gorm:"column:group_id;default:'';comment:所属规则组ID" json:"group_id"`                            // 所属规则组ID
	Status            int32     `gorm:"column:status;not null;default:0;comment:0停用1启用" json:"status"`                         // 0停用1启用
	CreatedAt         time.Time `gorm:"column:created_at;default:NULL;comment:创建时间" json:"created_at"`                         // 创建时间
	CreatedByUID      string    `gorm:"column:created_by_uid;default:NULL;comment:创建用户id" json:"created_by_uid"`               // 创建用户id
	UpdatedAt         time.Time `gorm:"column:updated_at;autoUpdateTime;comment:修改时间" json:"updated_at"`                       // 修改时间
	UpdatedByUID      string    `gorm:"column:updated_by_uid;default:NULL;comment:修改用户id" json:"updated_by_uid"`               // 修改用户id
	DeletedAt         int64     `gorm:"column:deleted_at;not null;default:0;comment:删除时间" json:"deleted_at"`                   // 删除时间
}

// TableName GradeRule's table name
func (*GradeRule) TableName() string {
	return TableNameGradeRule
}

func (g *GradeRule) BeforeCreate(tx *gorm.DB) (err error) {
	if g.ID == "" {
		g.ID = uuid.NewString()
	}
	if g.GradeRuleID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		g.GradeRuleID, err = int64(uniqueID), idErr
	}
	if g.CreatedAt.IsZero() {
		g.CreatedAt = time.Now()
	}
	if g.UpdatedAt.IsZero() {
		g.UpdatedAt = time.Now()
	}
	return
}

func (g *GradeRule) BeforeUpdate(tx *gorm.DB) (err error) {
	if g.UpdatedAt.IsZero() {
		g.UpdatedAt = time.Now()
	}
	return
}
