// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameRecognitionAlgorithm = "recognition_algorithm"

// RecognitionAlgorithm 识别算法表
type RecognitionAlgorithm struct {
	RecognitionAlgorithmID int64     `gorm:"column:recognition_algorithm_id;primaryKey;comment:识别算法雪花id" json:"recognition_algorithm_id"` // 识别算法雪花id
	ID                     string    `gorm:"column:id;not null;comment:识别算法uuid" json:"id"`                                               // 识别算法uuid
	Name                   string    `gorm:"column:name;comment:识别算法名称" json:"name"`                                                      // 识别算法名称
	Description            string    `gorm:"column:description;comment:识别算法描述" json:"description"`                                        // 识别算法描述
	Type                   string    `gorm:"column:type;comment:算法类型，自定义;内置" json:"type"`                                                 // 算法类型，自定义;内置
	InnerType              string    `gorm:"column:inner_type;comment:内置类型" json:"inner_type"`                                            // 内置类型
	Algorithm              string    `gorm:"column:algorithm;comment:算法表达式" json:"algorithm"`                                             // 算法表达式
	Status                 int32     `gorm:"column:status;not null;comment:0停用1启用" json:"status"`                                         // 0停用1启用
	CreatedAt              time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                            // 创建时间
	CreatedByUID           string    `gorm:"column:created_by_uid;comment:创建用户id" json:"created_by_uid"`                                  // 创建用户id
	UpdatedAt              time.Time `gorm:"column:updated_at;autoUpdateTime;comment:修改时间" json:"updated_at"`                             // 修改时间
	UpdatedByUID           string    `gorm:"column:updated_by_uid;comment:修改用户id" json:"updated_by_uid"`                                  // 修改用户id
	DeletedAt              int64     `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`                                   // 删除时间
}

// TableName RecognitionAlgorithm's table name
func (*RecognitionAlgorithm) TableName() string {
	return TableNameRecognitionAlgorithm
}

func (r *RecognitionAlgorithm) BeforeCreate(tx *gorm.DB) (err error) {
	if r.ID == "" {
		r.ID = uuid.NewString()
	}
	if r.RecognitionAlgorithmID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		r.RecognitionAlgorithmID, err = int64(uniqueID), idErr
	}
	if r.CreatedAt.IsZero() {
		r.CreatedAt = time.Now()
	}
	if r.UpdatedAt.IsZero() {
		r.UpdatedAt = time.Now()
	}
	return
}

func (r *RecognitionAlgorithm) BeforeUpdate(tx *gorm.DB) (err error) {
	if r.UpdatedAt.IsZero() {
		r.UpdatedAt = time.Now()
	}
	return
}
