// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameScanRecord = "scan_record"

// ScanRecord mapped from table <scan_record>
type ScanRecord struct {
	ID           uint64    `gorm:"column:id;primaryKey" json:"id"`                                   // 雪花id
	DatasourceID string    `gorm:"column:datasource_id;not null;comment:数据源id" json:"datasource_id"` // 数据源id
	Scanner      string    `gorm:"column:scanner;not null;comment:扫描者" json:"scanner"`               // 扫描者
	ScanTime     time.Time `gorm:"column:scan_time;default:CURRENT_TIMESTAMP" json:"scan_time"`      // 扫描时间
}

func (s *ScanRecord) BeforeCreate(_ *gorm.DB) (err error) {
	if s == nil {
		return nil
	}

	if s.ID == 0 {
		if s.ID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}

	return nil
}

// TableName Datasource's table name
func (*ScanRecord) TableName() string {
	return TableNameScanRecord
}
