// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTGraphModel = "t_graph_model"

// TGraphModel 元模型
type TGraphModel struct {
	ModelID      uint64 `gorm:"column:model_id;primaryKey;comment:自增雪花ID" json:"model_id"`                            // 自增雪花ID
	ID           string `gorm:"column:id;not null;comment:主键ID，uuid" json:"id"`                                       // 主键ID，uuid
	BusinessName string `gorm:"column:business_name;comment:模型名称，业务名称" json:"business_name"`                          // 模型名称，业务名称
	SubjectID    string `gorm:"column:subject_id;comment:业务对象ID" json:"subject_id"`                                   // 业务对象ID
	Description  string `gorm:"column:description;comment:描述" json:"description"`                                     // 描述
	ModelType    int32  `gorm:"column:model_type;not null;default:1;comment:模型类型，1元模型，2专题模型，3主题模型" json:"model_type"` // 模型类型，1元模型，2专题模型，3主题模型
	//-- 不同的字段
	TechnicalName string `gorm:"column:technical_name;not null;comment:模型技术名称" json:"technical_name"`  // 模型技术名称
	CatalogID     uint64 `gorm:"column:catalog_id;not null;comment:目录的主键ID" json:"catalog_id"`         // 目录的主键ID
	DataViewID    string `gorm:"column:data_view_id;not null;comment:目录带的元数据视图ID" json:"data_view_id"` // 目录带的元数据视图ID
	GraphID       int    `gorm:"column:graph_id" json:"graph_id"`                                      // 图谱ID
	GradeLabelId  string `gorm:"column:grade_label_id" json:"grade_label_id"`                          //密级ID
	//基础字段
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"` // 创建时间
	CreatorUID  string    `gorm:"column:creator_uid;not null;comment:用户ID" json:"creator_uid"`                            // 用户ID
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;autoUpdateTime;comment:更新时间" json:"updated_at"`               // 更新时间
	UpdaterUID  string    `gorm:"column:updater_uid;comment:更新用户ID" json:"updater_uid"`                                   // 更新用户ID
	UpdaterName string    `gorm:"column:updater_name;comment:更新用户名称" json:"updater_name"`                                 // 更新用户名称
	DeletedAt   int64     `gorm:"column:deleted_at;comment:删除时间(逻辑删除)" json:"deleted_at"`                                 // 删除时间(逻辑删除)
}

func (d *TGraphModel) UniqueKey() string {
	return "id"
}

// TableName TMetaModel's table name
func (*TGraphModel) TableName() string {
	return TableNameTGraphModel
}

func (d *TGraphModel) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ModelID == 0 {
		if d.ModelID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	return err
}
