// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTModelCanva = "t_model_canvas"

// TModelCanva 模型画布
type TModelCanva struct {
	ID     string `gorm:"column:id;primaryKey;comment:模型id" json:"id"` // 模型id
	Canvas string `gorm:"column:canvas;comment:画布信息" json:"canvas"`    // 画布信息
}

// TableName TModelCanva's table name
func (*TModelCanva) TableName() string {
	return TableNameTModelCanva
}
