// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTModelSingleNode = "t_model_single_node"

// TModelSingleNode 复合模型的孤立模型的ID
type TModelSingleNode struct {
	ID             uint64 `gorm:"column:id;primaryKey;comment:自增雪花ID" json:"id"`                           // 自增雪花ID
	ModelID        string `gorm:"column:model_id;not null;comment:主题模型/专题模型ID" json:"model_id"`            // 主题模型/专题模型ID
	MetaModelID    string `gorm:"column:meta_model_id;not null;comment:元模型ID" json:"meta_model_id"`        // 元模型ID
	DisplayFieldID string `gorm:"column:display_field_id;not null;comment:显示字段ID" json:"display_field_id"` // 显示字段ID
}

// TableName TModelSingleNode's table name
func (*TModelSingleNode) TableName() string {
	return TableNameTModelSingleNode
}
func (d *TModelSingleNode) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		if d.ID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	return err
}
