// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTModelRelation = "t_model_relation"

// TModelRelation 复合模型的关系
type TModelRelation struct {
	RelationID          uint64    `gorm:"column:relation_id;primaryKey;comment:自增雪花ID" json:"relation_id"`                        // 自增雪花ID
	ID                  string    `gorm:"column:id;not null;comment:主键ID，uuid" json:"id"`                                         // 主键ID，uuid
	BusinessName        string    `gorm:"column:business_name;comment:业务名称" json:"business_name"`                                 // 业务名称
	TechnicalName       string    `gorm:"column:technical_name;not null;comment:模型技术名称" json:"technical_name"`                    // 模型技术名称
	ModelID             string    `gorm:"column:model_id;not null;comment:主题模型/专题模型ID" json:"model_id"`                           // 主题模型/专题模型ID
	StartDisplayFieldID string    `gorm:"column:start_display_field_id;comment:模型显示字段ID" json:"start_display_field_id"`           // 起点模型显示字段ID
	EndDisplayFieldID   string    `gorm:"column:end_display_field_id;comment:模型显示字段ID" json:"end_display_field_id"`               // 模型显示字段ID
	Description         string    `gorm:"column:description;comment:描述" json:"description"`                                       // 描述
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt           time.Time `gorm:"column:updated_at;not null;autoUpdateTime;comment:更新时间" json:"updated_at"`               // 更新时间
	UpdaterUID          string    `gorm:"column:updater_uid;comment:更新用户ID" json:"updater_uid"`                                   // 更新用户ID
	UpdaterName         string    `gorm:"column:updater_name;comment:更新用户名称" json:"updater_name"`                                 // 更新用户名称
}

// TableName TModelRelation's table name
func (*TModelRelation) TableName() string {
	return TableNameTModelRelation
}

func (d *TModelRelation) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.RelationID == 0 {
		if d.RelationID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	return err
}
