// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTModelField = "t_model_field"

// TModelField 元模型字段表
type TModelField struct {
	ID            uint64 `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                        // 主键ID
	FieldID       string `gorm:"column:field_id;not null;comment:元模型ID" json:"field_id"`             // 视图字段ID
	ModelID       string `gorm:"column:model_id;not null;comment:元模型ID" json:"model_id"`             // 元模型ID
	TechnicalName string `gorm:"column:technical_name;not null;comment:列技术名称" json:"technical_name"` // 列技术名称
	BusinessName  string `gorm:"column:business_name;comment:列业务名称" json:"business_name"`            // 列业务名称
	DataType      string `gorm:"column:data_type;not null;comment:数据类型" json:"data_type"`            // 数据类型
	DataLength    int32  `gorm:"column:data_length;not null;comment:数据长度" json:"data_length"`        // 数据长度
	DataAccuracy  int32  `gorm:"column:data_accuracy;not null;comment:数据精度" json:"data_accuracy"`    // 数据精度
	PrimaryKey    bool   `gorm:"column:primary_key;comment:是否是主键,0不是，1是" json:"primary_key"`         // 是否是主键,0不是，1是
	IsNullable    string `gorm:"column:is_nullable;not null;comment:是否为空" json:"is_nullable"`        // 是否为空
	Comment       string `gorm:"column:comment;comment:字段注释" json:"comment"`                         // 字段注释
}

// TableName TModelField's table name
func (*TModelField) TableName() string {
	return TableNameTModelField
}

func (d *TModelField) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		if d.ID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	return err
}
