// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTModelLabelRecRel = "t_model_label_rec_rel"

// TModelLabelRecRel 模型标签推荐关联配置
type TModelLabelRecRel struct {
	ID              uint64 `gorm:"column:id;primaryKey;comment:自增雪花ID" json:"id"`                      // 自增雪花ID
	Name            string `gorm:"column:name;comment:名称" json:"name"`                                 // 名称
	RelatedModelIDs string `gorm:"column:related_model_ids;comment:关联模型id集合" json:"related_model_ids"` // 关联模型id集合,多个逗号分隔
	Description     string `gorm:"column:description;comment:描述" json:"description"`                   // 描述

	//基础字段
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"` // 创建时间
	CreatorUID  string    `gorm:"column:creator_uid;not null;comment:用户ID" json:"creator_uid"`                            // 用户ID
	CreatedName string    `gorm:"column:created_name;comment:新建用户名称" json:"created_name"`                                 // 新建用户名称
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;autoUpdateTime;comment:更新时间" json:"updated_at"`               // 更新时间
	UpdaterUID  string    `gorm:"column:updater_uid;comment:更新用户ID" json:"updater_uid"`                                   // 更新用户ID
	UpdaterName string    `gorm:"column:updater_name;comment:更新用户名称" json:"updater_name"`                                 // 更新用户名称
	DeletedAt   int64     `gorm:"column:deleted_at;comment:删除时间(逻辑删除)" json:"deleted_at"`                                 // 删除时间(逻辑删除)

}

func (d *TModelLabelRecRel) UniqueKey() string {
	return "id"
}

// TableName TMetaModel's table name
func (*TModelLabelRecRel) TableName() string {
	return TableNameTModelLabelRecRel
}

func (d *TModelLabelRecRel) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		if d.ID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	return err
}
