// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTModelRelationLink = "t_model_relation_link"

// TModelRelationLink 复合模型的关系
type TModelRelationLink struct {
	ID           uint64 `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                          // 主键ID
	UniqueID     string `gorm:"column:unique_id;not null;comment:关系信息几个字段拼接的MD5值" json:"unique_id"`   // 关系信息几个字段拼接的MD5值
	ModelID      string `gorm:"column:model_id;not null;comment:主题模型/专题模型ID" json:"model_id"`         // 主题模型/专题模型ID
	RelationID   string `gorm:"column:relation_id;not null;comment:模型关系ID" json:"relation_id"`        // 模型关系ID
	StartModelID string `gorm:"column:start_model_id;not null;comment:起点元模型ID" json:"start_model_id"` // 起点元模型ID
	StartFieldID string `gorm:"column:start_field_id;not null;comment:起点字段ID" json:"start_field_id"`  // 起点字段ID
	EndModelID   string `gorm:"column:end_model_id;not null;comment:终点元模型ID" json:"end_model_id"`     // 终点元模型ID
	EndFieldID   string `gorm:"column:end_field_id;not null;comment:起点字段ID" json:"end_field_id"`      // 起点字段ID
}

// TableName TModelRelationLink's table name
func (*TModelRelationLink) TableName() string {
	return TableNameTModelRelationLink
}
func (d *TModelRelationLink) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		if d.ID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	return err
}
