// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTemplateRule = "template_rule"

// TemplateRule 模板规则表
type TemplateRule struct {
	ID              uint64     `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                // 主键
	RuleID          string     `gorm:"column:rule_id;comment:规则id" json:"rule_id"`                               // 规则id
	RuleName        string     `gorm:"column:rule_name;not null;comment:规则名称" json:"rule_name"`                  // 规则名称
	RuleDescription string     `gorm:"column:rule_description;comment:规则描述" json:"rule_description"`             // 规则描述
	RuleLevel       int32      `gorm:"column:rule_level;not null;comment:规则级别" json:"rule_level"`                // 规则级别
	Dimension       int32      `gorm:"column:dimension;not null;comment:维度" json:"dimension"`                    // 维度
	DimensionType   *int32     `gorm:"column:dimension_type;comment:维度类型" json:"dimension_type"`                 // 维度类型
	Source          int32      `gorm:"column:source;not null;comment:来源" json:"source"`                          // 来源
	RuleConfig      *string    `gorm:"column:rule_config;comment:规则配置" json:"rule_config"`                       // 规则配置
	Enable          int32      `gorm:"column:enable;not null;comment:默认检测是否启用" json:"enable"`                    // 默认检测是否启用
	CreatedAt       *time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                // 创建时间
	CreatedByUID    string     `gorm:"column:created_by_uid;comment:创建人" json:"created_by_uid"`                  // 创建人
	UpdatedAt       *time.Time `gorm:"column:updated_at;not null;autoUpdateTime;comment:修改时间" json:"updated_at"` // 修改时间
	UpdatedByUID    string     `gorm:"column:updated_by_uid;comment:修改人" json:"updated_by_uid"`                  // 修改人
	DeletedAt       int64      `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`                // 删除时间
}

func (e *TemplateRule) BeforeCreate(_ *gorm.DB) error {
	if e == nil {
		return nil
	}
	var err error
	if e.ID == 0 {
		e.ID, err = utilities.GetUniqueID()
	}
	if len(e.RuleID) == 0 {
		e.RuleID = uuid.NewString()
	}

	return err
}

// TableName TemplateRule's table name
func (*TemplateRule) TableName() string {
	return TableNameTemplateRule
}
