// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTmpExploreSubTask = "tmp_explore_sub_task"

// TmpExploreSubTask mapped from table <tmp_explore_sub_task>
type TmpExploreSubTask struct {
	ID           uint64     `gorm:"column:id;primaryKey" json:"id"`                                                                                                // 探查子任务id
	ParentTaskID string     `gorm:"column:parent_task_id;not null;comment:探查任务id" json:"parent_task_id"`                                                           // 父级探查任务id
	FormViewID   string     `gorm:"column:form_view_id;comment:视图id" json:"form_view_id"`                                                                          // 视图id
	Status       int32      `gorm:"column:status;not null;comment:任务状态，1：queuing（等待中）；2：running（进行中）；3：finished（已完成）；4：canceled（已取消）；5：failed（异常）；" json:"status"` // 任务状态，1：queuing（等待中）；2：running（进行中）；3：finished（已完成）；4：canceled（已取消）；5：failed（异常）；
	Remark       *string    `gorm:"column:remark;comment:执行失败说明" json:"remark"`                                                                                    // 执行失败说明
	CreatedAt    time.Time  `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"`                                        // 创建时间
	FinishedAt   *time.Time `gorm:"column:finished_at;comment:结束时间" json:"finished_at"`                                                                            // 结束时间
}

// TableName TmpExploreSubTask's table name
func (*TmpExploreSubTask) TableName() string {
	return TableNameTmpExploreSubTask
}

func (d *TmpExploreSubTask) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.ID == 0 {
		d.ID, err = utilities.GetUniqueID()
	}
	return err
}
