// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTmpCompletion = "tmp_completion"

// TmpCompletion mapped from table <tmp_completion>
type TmpCompletion struct {
	FormViewID   string    `gorm:"column:form_view_id;primaryKey;comment:视图id" json:"form_view_id"`   // 视图id
	CompletionID string    `gorm:"column:completion_id;not null;comment:补全结果id" json:"completion_id"` // 补全结果id
	Result       string    `gorm:"column:result;comment:补全结果" json:"result"`                          // 补全结果
	Status       int32     `gorm:"column:status;not null;comment:补全状态" json:"status"`                 // 补全状态
	Reason       string    `gorm:"column:reason;comment:补全失败原因" json:"reason"`                        // 补全失败原因
	CreatedAt    *time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`         // 创建时间
}

// TableName TmpCompletion's table name
func (*TmpCompletion) TableName() string {
	return TableNameTmpCompletion
}
