// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameViewAuthedUser = "view_authed_users"

// ViewAuthedUser 视图授权用户关系表
type ViewAuthedUser struct {
	ID     string `gorm:"column:id;primaryKey" json:"id"`
	ViewID string `gorm:"column:view_id;not null;comment:视图ID" json:"view_id"` // 视图ID
	UserID string `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"` // 用户ID
}

// TableName ViewAuthedUser's table name
func (*ViewAuthedUser) TableName() string {
	return TableNameViewAuthedUser
}
