// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameWhiteListPolicy = "white_list_policy"

// WhiteListPolicy mapped from table <white_list_policy>
type WhiteListPolicy struct {
	WhitePolicyID uint64    `gorm:"column:white_policy_id;primaryKey" json:"white_policy_id"`
	ID            string    `gorm:"column:id" json:"id"`
	FormViewID    string    `gorm:"column:form_view_id" json:"form_view_id"`
	Description   string    `gorm:"column:description" json:"description"`
	Config        string    `gorm:"column:config" json:"config"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	CreatedByUID  string    `gorm:"column:created_by_uid" json:"created_by_uid"`
	UpdatedAt     time.Time `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`
	UpdatedByUID  string    `gorm:"column:updated_by_uid" json:"updated_by_uid"`
	DeletedAt     int32     `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName WhiteListPolicy's table name
func (*WhiteListPolicy) TableName() string {
	return TableNameWhiteListPolicy
}

func (d *WhiteListPolicy) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.WhitePolicyID == 0 {
		d.WhitePolicyID, err = utilities.GetUniqueID()
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}
