// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/idrm-go-frame/core/utils/httpclient (interfaces: HTTPClient)
//
// Generated by this command:
//
//	mockgen -destination=httpclient.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/idrm-go-frame/core/utils/httpclient HTTPClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=httpclient.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/idrm-go-frame/core/utils/httpclient HTTPClient

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHTTPClient) Delete(arg0 context.Context, arg1 string, arg2 map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHTTPClientMockRecorder) Delete(arg0, arg1, arg2 any) *MockHTTPClientDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHTTPClient)(nil).Delete), arg0, arg1, arg2)
	return &MockHTTPClientDeleteCall{Call: call}
}

// MockHTTPClientDeleteCall wrap *gomock.Call
type MockHTTPClientDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientDeleteCall) Return(arg0 any, arg1 error) *MockHTTPClientDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientDeleteCall) Do(f func(context.Context, string, map[string]string) (any, error)) *MockHTTPClientDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientDeleteCall) DoAndReturn(f func(context.Context, string, map[string]string) (any, error)) *MockHTTPClientDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockHTTPClient) Get(arg0 context.Context, arg1 string, arg2 map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHTTPClientMockRecorder) Get(arg0, arg1, arg2 any) *MockHTTPClientGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHTTPClient)(nil).Get), arg0, arg1, arg2)
	return &MockHTTPClientGetCall{Call: call}
}

// MockHTTPClientGetCall wrap *gomock.Call
type MockHTTPClientGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientGetCall) Return(arg0 any, arg1 error) *MockHTTPClientGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientGetCall) Do(f func(context.Context, string, map[string]string) (any, error)) *MockHTTPClientGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientGetCall) DoAndReturn(f func(context.Context, string, map[string]string) (any, error)) *MockHTTPClientGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Post mocks base method.
func (m *MockHTTPClient) Post(arg0 context.Context, arg1 string, arg2 map[string]string, arg3 any) (int, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Post indicates an expected call of Post.
func (mr *MockHTTPClientMockRecorder) Post(arg0, arg1, arg2, arg3 any) *MockHTTPClientPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPClient)(nil).Post), arg0, arg1, arg2, arg3)
	return &MockHTTPClientPostCall{Call: call}
}

// MockHTTPClientPostCall wrap *gomock.Call
type MockHTTPClientPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientPostCall) Return(arg0 int, arg1 any, arg2 error) *MockHTTPClientPostCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientPostCall) Do(f func(context.Context, string, map[string]string, any) (int, any, error)) *MockHTTPClientPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientPostCall) DoAndReturn(f func(context.Context, string, map[string]string, any) (int, any, error)) *MockHTTPClientPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Put mocks base method.
func (m *MockHTTPClient) Put(arg0 context.Context, arg1 string, arg2 map[string]string, arg3 any) (int, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Put indicates an expected call of Put.
func (mr *MockHTTPClientMockRecorder) Put(arg0, arg1, arg2, arg3 any) *MockHTTPClientPutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockHTTPClient)(nil).Put), arg0, arg1, arg2, arg3)
	return &MockHTTPClientPutCall{Call: call}
}

// MockHTTPClientPutCall wrap *gomock.Call
type MockHTTPClientPutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientPutCall) Return(arg0 int, arg1 any, arg2 error) *MockHTTPClientPutCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientPutCall) Do(f func(context.Context, string, map[string]string, any) (int, any, error)) *MockHTTPClientPutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientPutCall) DoAndReturn(f func(context.Context, string, map[string]string, any) (int, any, error)) *MockHTTPClientPutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
