// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Doc           *Doc                   `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	Telemetry     *Telemetry             `protobuf:"bytes,3,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	DepServices   *DepServices           `protobuf:"bytes,4,opt,name=depServices,proto3" json:"depServices,omitempty"`
	Database      *Database              `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Exploration   *Exploration           `protobuf:"bytes,6,opt,name=exploration,proto3" json:"exploration,omitempty"`
	Config        *Config                `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetDoc() *Doc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *Bootstrap) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *Bootstrap) GetDepServices() *DepServices {
	if x != nil {
		return x.DepServices
	}
	return nil
}

func (x *Bootstrap) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Bootstrap) GetExploration() *Exploration {
	if x != nil {
		return x.Exploration
	}
	return nil
}

func (x *Bootstrap) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Http          *Server_HTTP           `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,3,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Doc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Doc) Reset() {
	*x = Doc{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Doc) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Doc) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceUrl      string                 `protobuf:"bytes,1,opt,name=traceUrl,proto3" json:"traceUrl,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	LogUrl        string                 `protobuf:"bytes,3,opt,name=logUrl,proto3" json:"logUrl,omitempty"`
	ServerName    string                 `protobuf:"bytes,4,opt,name=serverName,proto3" json:"serverName,omitempty"`
	ServerVersion string                 `protobuf:"bytes,5,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	TraceEnabled  string                 `protobuf:"bytes,6,opt,name=traceEnabled,proto3" json:"traceEnabled,omitempty"`
	AuditUrl      string                 `protobuf:"bytes,7,opt,name=auditUrl,proto3" json:"auditUrl,omitempty"`
	AuditEnabled  string                 `protobuf:"bytes,8,opt,name=auditEnabled,proto3" json:"auditEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Telemetry) GetTraceUrl() string {
	if x != nil {
		return x.TraceUrl
	}
	return ""
}

func (x *Telemetry) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Telemetry) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *Telemetry) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Telemetry) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Telemetry) GetTraceEnabled() string {
	if x != nil {
		return x.TraceEnabled
	}
	return ""
}

func (x *Telemetry) GetAuditUrl() string {
	if x != nil {
		return x.AuditUrl
	}
	return ""
}

func (x *Telemetry) GetAuditEnabled() string {
	if x != nil {
		return x.AuditEnabled
	}
	return ""
}

type DepServices struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	KafkaMQ                    *DepServices_KafkaMQ   `protobuf:"bytes,1,opt,name=kafkaMQ,proto3" json:"kafkaMQ,omitempty"`
	UserMgmPrivate             string                 `protobuf:"bytes,2,opt,name=userMgmPrivate,proto3" json:"userMgmPrivate,omitempty"`
	HydraAdmin                 string                 `protobuf:"bytes,3,opt,name=hydraAdmin,proto3" json:"hydraAdmin,omitempty"`
	BusinessGroomingHost       string                 `protobuf:"bytes,4,opt,name=businessGroomingHost,proto3" json:"businessGroomingHost,omitempty"`
	ConfigurationCenterHost    string                 `protobuf:"bytes,5,opt,name=configurationCenterHost,proto3" json:"configurationCenterHost,omitempty"`
	VirtualizationEngineHost   string                 `protobuf:"bytes,6,opt,name=virtualizationEngineHost,proto3" json:"virtualizationEngineHost,omitempty"`
	MetadataHost               string                 `protobuf:"bytes,7,opt,name=metadataHost,proto3" json:"metadataHost,omitempty"`
	AuthServiceHost            string                 `protobuf:"bytes,8,opt,name=authServiceHost,proto3" json:"authServiceHost,omitempty"`
	DataSubjectHost            string                 `protobuf:"bytes,9,opt,name=dataSubjectHost,proto3" json:"dataSubjectHost,omitempty"`
	AfSailorServiceHost        string                 `protobuf:"bytes,10,opt,name=afSailorServiceHost,proto3" json:"afSailorServiceHost,omitempty"`
	StandardizationBackendHost string                 `protobuf:"bytes,11,opt,name=standardizationBackendHost,proto3" json:"standardizationBackendHost,omitempty"`
	DataExploreHost            string                 `protobuf:"bytes,12,opt,name=dataExploreHost,proto3" json:"dataExploreHost,omitempty"`
	SceneAnalysisHost          string                 `protobuf:"bytes,13,opt,name=sceneAnalysisHost,proto3" json:"sceneAnalysisHost,omitempty"`
	WorkflowHost               string                 `protobuf:"bytes,14,opt,name=workflowHost,proto3" json:"workflowHost,omitempty"`
	Nsq                        *DepServices_Nsq       `protobuf:"bytes,15,opt,name=nsq,proto3" json:"nsq,omitempty"`
	MqType                     string                 `protobuf:"bytes,16,opt,name=mqType,proto3" json:"mqType,omitempty"`
	HydraPublic                string                 `protobuf:"bytes,17,opt,name=hydraPublic,proto3" json:"hydraPublic,omitempty"`
	MdlDataModelHost           string                 `protobuf:"bytes,18,opt,name=mdlDataModelHost,proto3" json:"mdlDataModelHost,omitempty"`
	MdlUniqueryHost            string                 `protobuf:"bytes,19,opt,name=mdlUniqueryHost,proto3" json:"mdlUniqueryHost,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DepServices) Reset() {
	*x = DepServices{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepServices) ProtoMessage() {}

func (x *DepServices) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepServices.ProtoReflect.Descriptor instead.
func (*DepServices) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *DepServices) GetKafkaMQ() *DepServices_KafkaMQ {
	if x != nil {
		return x.KafkaMQ
	}
	return nil
}

func (x *DepServices) GetUserMgmPrivate() string {
	if x != nil {
		return x.UserMgmPrivate
	}
	return ""
}

func (x *DepServices) GetHydraAdmin() string {
	if x != nil {
		return x.HydraAdmin
	}
	return ""
}

func (x *DepServices) GetBusinessGroomingHost() string {
	if x != nil {
		return x.BusinessGroomingHost
	}
	return ""
}

func (x *DepServices) GetConfigurationCenterHost() string {
	if x != nil {
		return x.ConfigurationCenterHost
	}
	return ""
}

func (x *DepServices) GetVirtualizationEngineHost() string {
	if x != nil {
		return x.VirtualizationEngineHost
	}
	return ""
}

func (x *DepServices) GetMetadataHost() string {
	if x != nil {
		return x.MetadataHost
	}
	return ""
}

func (x *DepServices) GetAuthServiceHost() string {
	if x != nil {
		return x.AuthServiceHost
	}
	return ""
}

func (x *DepServices) GetDataSubjectHost() string {
	if x != nil {
		return x.DataSubjectHost
	}
	return ""
}

func (x *DepServices) GetAfSailorServiceHost() string {
	if x != nil {
		return x.AfSailorServiceHost
	}
	return ""
}

func (x *DepServices) GetStandardizationBackendHost() string {
	if x != nil {
		return x.StandardizationBackendHost
	}
	return ""
}

func (x *DepServices) GetDataExploreHost() string {
	if x != nil {
		return x.DataExploreHost
	}
	return ""
}

func (x *DepServices) GetSceneAnalysisHost() string {
	if x != nil {
		return x.SceneAnalysisHost
	}
	return ""
}

func (x *DepServices) GetWorkflowHost() string {
	if x != nil {
		return x.WorkflowHost
	}
	return ""
}

func (x *DepServices) GetNsq() *DepServices_Nsq {
	if x != nil {
		return x.Nsq
	}
	return nil
}

func (x *DepServices) GetMqType() string {
	if x != nil {
		return x.MqType
	}
	return ""
}

func (x *DepServices) GetHydraPublic() string {
	if x != nil {
		return x.HydraPublic
	}
	return ""
}

func (x *DepServices) GetMdlDataModelHost() string {
	if x != nil {
		return x.MdlDataModelHost
	}
	return ""
}

func (x *DepServices) GetMdlUniqueryHost() string {
	if x != nil {
		return x.MdlUniqueryHost
	}
	return ""
}

type Database struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dbtype                string                 `protobuf:"bytes,1,opt,name=dbtype,proto3" json:"dbtype,omitempty"`
	Host                  string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                  string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Username              string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password              string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Database              string                 `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	MaxIdleConnections    int32                  `protobuf:"varint,7,opt,name=maxIdleConnections,proto3" json:"maxIdleConnections,omitempty"`
	MaxOpenConnections    int32                  `protobuf:"varint,8,opt,name=maxOpenConnections,proto3" json:"maxOpenConnections,omitempty"`
	MaxConnectionIdleTime int32                  `protobuf:"varint,9,opt,name=maxConnectionIdleTime,proto3" json:"maxConnectionIdleTime,omitempty"`
	MaxConnectionLifeTime int32                  `protobuf:"varint,10,opt,name=maxConnectionLifeTime,proto3" json:"maxConnectionLifeTime,omitempty"`
	Loglevel              int32                  `protobuf:"varint,11,opt,name=loglevel,proto3" json:"loglevel,omitempty"`
	Isdebug               bool                   `protobuf:"varint,12,opt,name=isdebug,proto3" json:"isdebug,omitempty"`
	Tableprefix           string                 `protobuf:"bytes,13,opt,name=tableprefix,proto3" json:"tableprefix,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Database) GetDbtype() string {
	if x != nil {
		return x.Dbtype
	}
	return ""
}

func (x *Database) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Database) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Database) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Database) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Database) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Database) GetMaxIdleConnections() int32 {
	if x != nil {
		return x.MaxIdleConnections
	}
	return 0
}

func (x *Database) GetMaxOpenConnections() int32 {
	if x != nil {
		return x.MaxOpenConnections
	}
	return 0
}

func (x *Database) GetMaxConnectionIdleTime() int32 {
	if x != nil {
		return x.MaxConnectionIdleTime
	}
	return 0
}

func (x *Database) GetMaxConnectionLifeTime() int32 {
	if x != nil {
		return x.MaxConnectionLifeTime
	}
	return 0
}

func (x *Database) GetLoglevel() int32 {
	if x != nil {
		return x.Loglevel
	}
	return 0
}

func (x *Database) GetIsdebug() bool {
	if x != nil {
		return x.Isdebug
	}
	return false
}

func (x *Database) GetTableprefix() string {
	if x != nil {
		return x.Tableprefix
	}
	return ""
}

type Exploration struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CompletionDefaultOvertime string                 `protobuf:"bytes,1,opt,name=completionDefaultOvertime,proto3" json:"completionDefaultOvertime,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Exploration) Reset() {
	*x = Exploration{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exploration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exploration) ProtoMessage() {}

func (x *Exploration) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exploration.ProtoReflect.Descriptor instead.
func (*Exploration) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Exploration) GetCompletionDefaultOvertime() string {
	if x != nil {
		return x.CompletionDefaultOvertime
	}
	return ""
}

type Config struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SyntheticDataCache *SyntheticDataCache    `protobuf:"bytes,1,opt,name=SyntheticDataCache,proto3" json:"SyntheticDataCache,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Config) GetSyntheticDataCache() *SyntheticDataCache {
	if x != nil {
		return x.SyntheticDataCache
	}
	return nil
}

type SyntheticDataCache struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpirationTime int32                  `protobuf:"varint,1,opt,name=ExpirationTime,proto3" json:"ExpirationTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyntheticDataCache) Reset() {
	*x = SyntheticDataCache{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticDataCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticDataCache) ProtoMessage() {}

func (x *SyntheticDataCache) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticDataCache.ProtoReflect.Descriptor instead.
func (*SyntheticDataCache) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *SyntheticDataCache) GetExpirationTime() int32 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type DepServices_Sasl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepServices_Sasl) Reset() {
	*x = DepServices_Sasl{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepServices_Sasl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepServices_Sasl) ProtoMessage() {}

func (x *DepServices_Sasl) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepServices_Sasl.ProtoReflect.Descriptor instead.
func (*DepServices_Sasl) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DepServices_Sasl) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DepServices_Sasl) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DepServices_Sasl) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DepServices_Producer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendBufSize   int32                  `protobuf:"varint,1,opt,name=sendBufSize,proto3" json:"sendBufSize,omitempty"`
	RecvBufSize   int32                  `protobuf:"varint,2,opt,name=recvBufSize,proto3" json:"recvBufSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepServices_Producer) Reset() {
	*x = DepServices_Producer{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepServices_Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepServices_Producer) ProtoMessage() {}

func (x *DepServices_Producer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepServices_Producer.ProtoReflect.Descriptor instead.
func (*DepServices_Producer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 1}
}

func (x *DepServices_Producer) GetSendBufSize() int32 {
	if x != nil {
		return x.SendBufSize
	}
	return 0
}

func (x *DepServices_Producer) GetRecvBufSize() int32 {
	if x != nil {
		return x.RecvBufSize
	}
	return 0
}

type DepServices_KafkaMQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Sasl          *DepServices_Sasl      `protobuf:"bytes,2,opt,name=sasl,proto3" json:"sasl,omitempty"`
	Producer      *DepServices_Producer  `protobuf:"bytes,3,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepServices_KafkaMQ) Reset() {
	*x = DepServices_KafkaMQ{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepServices_KafkaMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepServices_KafkaMQ) ProtoMessage() {}

func (x *DepServices_KafkaMQ) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepServices_KafkaMQ.ProtoReflect.Descriptor instead.
func (*DepServices_KafkaMQ) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 2}
}

func (x *DepServices_KafkaMQ) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DepServices_KafkaMQ) GetSasl() *DepServices_Sasl {
	if x != nil {
		return x.Sasl
	}
	return nil
}

func (x *DepServices_KafkaMQ) GetProducer() *DepServices_Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

type DepServices_Nsq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	HttpHost      string                 `protobuf:"bytes,4,opt,name=httpHost,proto3" json:"httpHost,omitempty"`
	HttpPort      string                 `protobuf:"bytes,5,opt,name=httpPort,proto3" json:"httpPort,omitempty"`
	LookupdHost   string                 `protobuf:"bytes,6,opt,name=lookupdHost,proto3" json:"lookupdHost,omitempty"`
	LookupdPort   string                 `protobuf:"bytes,7,opt,name=lookupdPort,proto3" json:"lookupdPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepServices_Nsq) Reset() {
	*x = DepServices_Nsq{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepServices_Nsq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepServices_Nsq) ProtoMessage() {}

func (x *DepServices_Nsq) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepServices_Nsq.ProtoReflect.Descriptor instead.
func (*DepServices_Nsq) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 3}
}

func (x *DepServices_Nsq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DepServices_Nsq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DepServices_Nsq) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *DepServices_Nsq) GetHttpHost() string {
	if x != nil {
		return x.HttpHost
	}
	return ""
}

func (x *DepServices_Nsq) GetHttpPort() string {
	if x != nil {
		return x.HttpPort
	}
	return ""
}

func (x *DepServices_Nsq) GetLookupdHost() string {
	if x != nil {
		return x.LookupdHost
	}
	return ""
}

func (x *DepServices_Nsq) GetLookupdPort() string {
	if x != nil {
		return x.LookupdPort
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06config\x1a\x1egoogle/protobuf/duration.proto\"\xc7\x02\n" +
	"\tBootstrap\x12&\n" +
	"\x06server\x18\x01 \x01(\v2\x0e.config.ServerR\x06server\x12\x1d\n" +
	"\x03doc\x18\x02 \x01(\v2\v.config.DocR\x03doc\x12/\n" +
	"\ttelemetry\x18\x03 \x01(\v2\x11.config.TelemetryR\ttelemetry\x125\n" +
	"\vdepServices\x18\x04 \x01(\v2\x13.config.DepServicesR\vdepServices\x12,\n" +
	"\bdatabase\x18\x05 \x01(\v2\x10.config.DatabaseR\bdatabase\x125\n" +
	"\vexploration\x18\x06 \x01(\v2\x13.config.ExplorationR\vexploration\x12&\n" +
	"\x06config\x18\a \x01(\v2\x0e.config.ConfigR\x06config\"\xc4\x02\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04http\x18\x02 \x01(\v2\x13.config.Server.HTTPR\x04http\x12'\n" +
	"\x04grpc\x18\x03 \x01(\v2\x13.config.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"3\n" +
	"\x03Doc\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x85\x02\n" +
	"\tTelemetry\x12\x1a\n" +
	"\btraceUrl\x18\x01 \x01(\tR\btraceUrl\x12\x1a\n" +
	"\blogLevel\x18\x02 \x01(\tR\blogLevel\x12\x16\n" +
	"\x06logUrl\x18\x03 \x01(\tR\x06logUrl\x12\x1e\n" +
	"\n" +
	"serverName\x18\x04 \x01(\tR\n" +
	"serverName\x12$\n" +
	"\rserverVersion\x18\x05 \x01(\tR\rserverVersion\x12\"\n" +
	"\ftraceEnabled\x18\x06 \x01(\tR\ftraceEnabled\x12\x1a\n" +
	"\bauditUrl\x18\a \x01(\tR\bauditUrl\x12\"\n" +
	"\fauditEnabled\x18\b \x01(\tR\fauditEnabled\"\xc9\n" +
	"\n" +
	"\vDepServices\x125\n" +
	"\akafkaMQ\x18\x01 \x01(\v2\x1b.config.DepServices.KafkaMQR\akafkaMQ\x12&\n" +
	"\x0euserMgmPrivate\x18\x02 \x01(\tR\x0euserMgmPrivate\x12\x1e\n" +
	"\n" +
	"hydraAdmin\x18\x03 \x01(\tR\n" +
	"hydraAdmin\x122\n" +
	"\x14businessGroomingHost\x18\x04 \x01(\tR\x14businessGroomingHost\x128\n" +
	"\x17configurationCenterHost\x18\x05 \x01(\tR\x17configurationCenterHost\x12:\n" +
	"\x18virtualizationEngineHost\x18\x06 \x01(\tR\x18virtualizationEngineHost\x12\"\n" +
	"\fmetadataHost\x18\a \x01(\tR\fmetadataHost\x12(\n" +
	"\x0fauthServiceHost\x18\b \x01(\tR\x0fauthServiceHost\x12(\n" +
	"\x0fdataSubjectHost\x18\t \x01(\tR\x0fdataSubjectHost\x120\n" +
	"\x13afSailorServiceHost\x18\n" +
	" \x01(\tR\x13afSailorServiceHost\x12>\n" +
	"\x1astandardizationBackendHost\x18\v \x01(\tR\x1astandardizationBackendHost\x12(\n" +
	"\x0fdataExploreHost\x18\f \x01(\tR\x0fdataExploreHost\x12,\n" +
	"\x11sceneAnalysisHost\x18\r \x01(\tR\x11sceneAnalysisHost\x12\"\n" +
	"\fworkflowHost\x18\x0e \x01(\tR\fworkflowHost\x12)\n" +
	"\x03nsq\x18\x0f \x01(\v2\x17.config.DepServices.NsqR\x03nsq\x12\x16\n" +
	"\x06mqType\x18\x10 \x01(\tR\x06mqType\x12 \n" +
	"\vhydraPublic\x18\x11 \x01(\tR\vhydraPublic\x12*\n" +
	"\x10mdlDataModelHost\x18\x12 \x01(\tR\x10mdlDataModelHost\x12(\n" +
	"\x0fmdlUniqueryHost\x18\x13 \x01(\tR\x0fmdlUniqueryHost\x1aX\n" +
	"\x04Sasl\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x1aN\n" +
	"\bProducer\x12 \n" +
	"\vsendBufSize\x18\x01 \x01(\x05R\vsendBufSize\x12 \n" +
	"\vrecvBufSize\x18\x02 \x01(\x05R\vrecvBufSize\x1a\x85\x01\n" +
	"\aKafkaMQ\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12,\n" +
	"\x04sasl\x18\x02 \x01(\v2\x18.config.DepServices.SaslR\x04sasl\x128\n" +
	"\bproducer\x18\x03 \x01(\v2\x1c.config.DepServices.ProducerR\bproducer\x1a\xbd\x01\n" +
	"\x03Nsq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1a\n" +
	"\bhttpHost\x18\x04 \x01(\tR\bhttpHost\x12\x1a\n" +
	"\bhttpPort\x18\x05 \x01(\tR\bhttpPort\x12 \n" +
	"\vlookupdHost\x18\x06 \x01(\tR\vlookupdHost\x12 \n" +
	"\vlookupdPort\x18\a \x01(\tR\vlookupdPort\"\xc2\x03\n" +
	"\bDatabase\x12\x16\n" +
	"\x06dbtype\x18\x01 \x01(\tR\x06dbtype\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x06 \x01(\tR\bdatabase\x12.\n" +
	"\x12maxIdleConnections\x18\a \x01(\x05R\x12maxIdleConnections\x12.\n" +
	"\x12maxOpenConnections\x18\b \x01(\x05R\x12maxOpenConnections\x124\n" +
	"\x15maxConnectionIdleTime\x18\t \x01(\x05R\x15maxConnectionIdleTime\x124\n" +
	"\x15maxConnectionLifeTime\x18\n" +
	" \x01(\x05R\x15maxConnectionLifeTime\x12\x1a\n" +
	"\bloglevel\x18\v \x01(\x05R\bloglevel\x12\x18\n" +
	"\aisdebug\x18\f \x01(\bR\aisdebug\x12 \n" +
	"\vtableprefix\x18\r \x01(\tR\vtableprefix\"K\n" +
	"\vExploration\x12<\n" +
	"\x19completionDefaultOvertime\x18\x01 \x01(\tR\x19completionDefaultOvertime\"T\n" +
	"\x06Config\x12J\n" +
	"\x12SyntheticDataCache\x18\x01 \x01(\v2\x1a.config.SyntheticDataCacheR\x12SyntheticDataCache\"<\n" +
	"\x12SyntheticDataCache\x12&\n" +
	"\x0eExpirationTime\x18\x01 \x01(\x05R\x0eExpirationTimeB\n" +
	"Z\b.;configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_config_proto_goTypes = []any{
	(*Bootstrap)(nil),            // 0: config.Bootstrap
	(*Server)(nil),               // 1: config.Server
	(*Doc)(nil),                  // 2: config.Doc
	(*Telemetry)(nil),            // 3: config.Telemetry
	(*DepServices)(nil),          // 4: config.DepServices
	(*Database)(nil),             // 5: config.Database
	(*Exploration)(nil),          // 6: config.Exploration
	(*Config)(nil),               // 7: config.Config
	(*SyntheticDataCache)(nil),   // 8: config.SyntheticDataCache
	(*Server_HTTP)(nil),          // 9: config.Server.HTTP
	(*Server_GRPC)(nil),          // 10: config.Server.GRPC
	(*DepServices_Sasl)(nil),     // 11: config.DepServices.Sasl
	(*DepServices_Producer)(nil), // 12: config.DepServices.Producer
	(*DepServices_KafkaMQ)(nil),  // 13: config.DepServices.KafkaMQ
	(*DepServices_Nsq)(nil),      // 14: config.DepServices.Nsq
	(*durationpb.Duration)(nil),  // 15: google.protobuf.Duration
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: config.Bootstrap.server:type_name -> config.Server
	2,  // 1: config.Bootstrap.doc:type_name -> config.Doc
	3,  // 2: config.Bootstrap.telemetry:type_name -> config.Telemetry
	4,  // 3: config.Bootstrap.depServices:type_name -> config.DepServices
	5,  // 4: config.Bootstrap.database:type_name -> config.Database
	6,  // 5: config.Bootstrap.exploration:type_name -> config.Exploration
	7,  // 6: config.Bootstrap.config:type_name -> config.Config
	9,  // 7: config.Server.http:type_name -> config.Server.HTTP
	10, // 8: config.Server.grpc:type_name -> config.Server.GRPC
	13, // 9: config.DepServices.kafkaMQ:type_name -> config.DepServices.KafkaMQ
	14, // 10: config.DepServices.nsq:type_name -> config.DepServices.Nsq
	8,  // 11: config.Config.SyntheticDataCache:type_name -> config.SyntheticDataCache
	15, // 12: config.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	15, // 13: config.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	11, // 14: config.DepServices.KafkaMQ.sasl:type_name -> config.DepServices.Sasl
	12, // 15: config.DepServices.KafkaMQ.producer:type_name -> config.DepServices.Producer
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
