// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameTApi = "t_api"

// TDataResource mapped from table <t_data_resource>
type TApi struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`                 // 标识
	CatalogID  uint64 `gorm:"column:catalog_id;not null" json:"catalog_id"`   // 数据资源目录ID
	BodyType   int32  `gorm:"column:body_type;not null" json:"body_type"`     // 请求类型
	ParamType  string `gorm:"column:param_type;not null" json:"param_type"`   // 参数类型
	Name       string `gorm:"column:name;not null" json:"name"`               // 参数名
	IsArray    bool   `gorm:"column:is_array;not null" json:"is_array"`       // 是否数组
	HasContent bool   `gorm:"column:has_content;not null" json:"has_content"` // 是否有内容

}

// TableName TableNameTApi's table name
func (*TApi) TableName() string {
	return TableNameTApi
}

func (m *TApi) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == "" {
		m.ID = uuid.New().String()
	}

	return err
}
