// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTBusinessFormNotCataloged = "t_business_form_not_cataloged"

// TBusinessFormNotCataloged mapped from table <t_business_form_not_cataloged>
type TBusinessFormNotCataloged struct {
	FID               string  `gorm:"column:f_id;primaryKey" json:"f_id"`                      // 业务表ID
	FName             string  `gorm:"column:f_name;not null" json:"f_name"`                    // 业务表名称
	FDescription      string  `gorm:"column:f_description;not null" json:"f_description"`      // 业务表描述
	FInfoSystemID     *string `gorm:"column:f_info_system_id" json:"f_info_system_id"`         // 信息系统ID数组
	FDepartmentID     string  `gorm:"column:f_department_id;not null" json:"f_department_id"`  // 所属部门ID
	FBusinessDomainID *string `gorm:"column:f_business_domain_id" json:"f_business_domain_id"` // 主干业务ID
	FBusinessModelID  *string `gorm:"column:f_business_model_id" json:"f_business_model_id"`   // 业务模型ID
	FUpdateAt         int64   `gorm:"column:f_update_at;not null" json:"f_update_at"`          // 更新时间
}

// TableName TBusinessFormNotCataloged's table name
func (*TBusinessFormNotCataloged) TableName() string {
	return TableNameTBusinessFormNotCataloged
}
