// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTBusinessLogicEntityByBusinessDomain = "t_business_logic_entity_by_business_domain"

// TBusinessLogicEntityByBusinessDomain mapped from table <t_business_logic_entity_by_business_domain>
type TBusinessLogicEntityByBusinessDomain struct {
	ID                       uint64 `gorm:"column:id;primaryKey" json:"id"`                                                 // 唯一id，雪花算法
	BusinessDomainID         string `gorm:"column:business_domain_id;not null" json:"business_domain_id"`                   // 业务域id
	BusinessDomainName       string `gorm:"column:business_domain_name;not null" json:"business_domain_name"`               // 业务域名称
	BusinessLogicEntityCount int32  `gorm:"column:business_logic_entity_count;not null" json:"business_logic_entity_count"` // 已发布的业务逻辑实体数量
}

func (m *TBusinessLogicEntityByBusinessDomain) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TBusinessLogicEntityByBusinessDomain's table name
func (*TBusinessLogicEntityByBusinessDomain) TableName() string {
	return TableNameTBusinessLogicEntityByBusinessDomain
}
