// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTBusinessScene = "t_business_scene"

// TBusinessScene mapped from table <t_business_scene>
type TBusinessScene struct {
	FID                    int64  `gorm:"column:f_id;primaryKey;autoIncrement:true" json:"f_id"`                        // 自增主键
	FType                  int32  `gorm:"column:f_type;not null" json:"f_type"`                                         // 业务类型
	FValue                 string `gorm:"column:f_value;not null" json:"f_value"`                                       // 业务场景
	FInfoResourceCatalogID int64  `gorm:"column:f_info_resource_catalog_id;not null" json:"f_info_resource_catalog_id"` // 所属信息资源目录ID
	FRelatedType           int32  `gorm:"column:f_related_type;not null" json:"f_related_type"`                         // 关联类型
}

// TableName TBusinessScene's table name
func (*TBusinessScene) TableName() string {
	return TableNameTBusinessScene
}
