// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTBusinessLogicEntityByDepartment = "t_business_logic_entity_by_department"

// TBusinessLogicEntityByDepartment mapped from table <t_business_logic_entity_by_department>
type TBusinessLogicEntityByDepartment struct {
	ID                       uint64 `gorm:"column:id;primaryKey" json:"id"`                                                 // 唯一id，雪花算法
	DepartmentID             string `gorm:"column:department_id;not null" json:"department_id"`                             // 一级部门id
	DepartmentName           string `gorm:"column:department_name;not null" json:"department_name"`                         // 一级部门名称
	BusinessLogicEntityCount int32  `gorm:"column:business_logic_entity_count;not null" json:"business_logic_entity_count"` // 已发布的业务逻辑实体数量
}

func (m *TBusinessLogicEntityByDepartment) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TBusinessLogicEntityByDepartment's table name
func (*TBusinessLogicEntityByDepartment) TableName() string {
	return TableNameTBusinessLogicEntityByDepartment
}
