// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTCatalogCodeTitle = "t_catalog_code_title"

// TCatalogCodeTitle mapped from table <t_catalog_code_title>
type TCatalogCodeTitle struct {
	ID    uint64 `gorm:"column:id;primaryKey" json:"id"`     // 唯一id，雪花算法
	Code  string `gorm:"column:code;not null" json:"code"`   // 目录编码
	Title string `gorm:"column:title;not null" json:"title"` // 目录名称
}

func (m *TCatalogCodeTitle) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TCatalogCodeTitle's table name
func (*TCatalogCodeTitle) TableName() string {
	return TableNameTCatalogCodeTitle
}
