// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTClientInfo = "t_client_info"

// TClientInfo mapped from table <t_client_info>
type TClientInfo struct {
	ID           uint64 `gorm:"column:id;primaryKey" json:"id"`                     // 唯一id，雪花算法
	ClientID     string `gorm:"column:client_id;not null" json:"client_id"`         // 客户端id
	ClientSecret string `gorm:"column:client_secret;not null" json:"client_secret"` // 客户端密钥
}

func (m *TClientInfo) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TClientInfo's table name
func (*TClientInfo) TableName() string {
	return TableNameTClientInfo
}
