// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalog = "t_data_catalog"
const TableNameTDataCatalogApply = "t_data_catalog_apply"
const TableNameTDataINTERFACEApply = "t_data_interface_apply"
const TableNameTDataInterfaceAggregate = "t_data_interface_aggregate"

// TDataCatalog mapped from table <t_data_catalog>
type TDataCatalog struct {
	ID                     uint64     `gorm:"column:id" json:"id,string"`                                                   // 唯一id，雪花算法
	Code                   string     `gorm:"column:code;not null" json:"code"`                                             // 目录编码
	Title                  string     `gorm:"column:title;not null" json:"title"`                                           // 目录名称
	GroupID                uint64     `gorm:"column:group_id;not null;default:0" json:"group_id,string,omitempty"`          // 数据资源目录分类ID
	GroupName              string     `gorm:"column:group_name;not null" json:"group_name,omitempty"`                       // 数据资源目录分类名称
	ThemeID                uint64     `gorm:"column:theme_id" json:"theme_id,string,omitempty"`                             // 主题分类ID
	ThemeName              string     `gorm:"column:theme_name" json:"theme_name,omitempty"`                                // 主题分类名称
	ForwardVersionID       uint64     `gorm:"column:forward_version_id" json:"forward_version_id,omitempty"`                // 当前目录前一版本目录ID
	Description            string     `gorm:"column:description" json:"description,omitempty"`                              // 资源目录描述
	DataRange              int32      `gorm:"column:data_range" json:"data_range,omitempty"`                                // 数据范围：字典DM_DATA_SJFW，01全市 02市直 03区县
	UpdateCycle            int32      `gorm:"column:update_cycle" json:"update_cycle,omitempty"`                            // 更新频率 参考数据字典：GXZQ，1不定时 2实时 3每日 4每周 5每月 6每季度 7每半年 8每年 9其他
	OtherUpdateCycle       string     `gorm:"column:other_update_cycle" json:"other_update_cycle,omitempty"`                // 其他更新频率
	DataKind               int32      `gorm:"column:data_kind;not null" json:"data_kind"`                                   // 基础信息分类 1 人 2 地 4 事 8 物 16 组织 32 其他  可组合，如 人和地 即 1|2 = 3
	SharedType             int8       `gorm:"column:shared_type;not null" json:"shared_type"`                               // 共享属性 1 无条件共享 2 有条件共享 3 不予共享
	SharedCondition        string     `gorm:"column:shared_condition" json:"shared_condition,omitempty"`                    // 共享条件
	ColumnUnshared         bool       `gorm:"column:column_unshared;not null" json:"column_unshared"`                       // 信息项不予共享
	OpenType               int8       `gorm:"column:open_type;not null" json:"open_type,omitempty"`                         // 开放属性 1 向公众开放 2 不向公众开放
	OpenCondition          string     `gorm:"column:open_condition" json:"open_condition,omitempty"`                        // 开放条件
	SharedMode             int8       `gorm:"column:shared_mode;not null" json:"shared_mode,omitempty"`                     // 共享方式 1 共享平台方式 2 邮件方式 3 介质方式
	PhysicalDeletion       *int8      `gorm:"column:physical_deletion" json:"physical_deletion,omitempty"`                  // 挂接实体资源是否存在物理删除(1 是 ; 0 否)
	SyncMechanism          int8       `gorm:"column:sync_mechanism" json:"sync_mechanism,omitempty"`                        // 数据归集机制(1 增量 ; 2 全量) ----归集到数据中台
	SyncFrequency          string     `gorm:"column:sync_frequency" json:"sync_frequency,omitempty"`                        // 数据归集频率 ----归集到数据中台
	ViewCount              int        `gorm:"column:view_count;not null" json:"view_count"`                                 // 挂接逻辑视图数量
	ApiCount               int        `gorm:"column:api_count;not null" json:"api_count"`                                   // 挂接接口数量
	FileCount              int        `gorm:"column:file_count;not null" json:"file_count"`                                 // 挂接文件资源数量
	FlowNodeID             string     `gorm:"column:flow_node_id" json:"flow_node_id"`                                      // 目录当前所处审核流程结点ID
	FlowNodeName           string     `gorm:"column:flow_node_name" json:"flow_node_name"`                                  // 目录当前所处审核流程结点名称
	FlowID                 string     `gorm:"column:flow_id" json:"flow_id"`                                                // 审批流程实例ID
	FlowName               string     `gorm:"column:flow_name" json:"flow_name"`                                            // 审批流程名称
	FlowVersion            string     `gorm:"column:flow_version" json:"flow_version"`                                      // 审批流程版本
	DepartmentID           string     `gorm:"column:department_id;not null" json:"department_id"`                           // 所属部门ID
	CreatedAt              time.Time  `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`     // 创建时间
	CreatorUID             string     `gorm:"column:creator_uid;not null" json:"creator_uid,omitempty"`                     // 创建用户ID
	UpdatedAt              time.Time  `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`                  // 更新时间
	UpdaterUID             string     `gorm:"column:updater_uid" json:"updater_uid,omitempty"`                              // 更新用户ID
	Source                 int8       `gorm:"column:source;not null;default:1" json:"source"`                               // 数据来源 1 认知平台自动创建 2 人工创建
	TableType              int8       `gorm:"column:table_type" json:"table_type,omitempty"`                                // 库表类型 1 贴源表 2 标准表
	CurrentVersion         *int8      `gorm:"column:current_version;not null;default:1" json:"current_version,omitempty"`   // 是否先行版本 0 否 1 是
	PublishFlag            *int8      `gorm:"column:publish_flag;not null;default:0" json:"publish_flag,omitempty"`         // 是否发布到超市 (1 是 ; 0 否)
	DataKindFlag           *int8      `gorm:"column:data_kind_flag;not null;default:0" json:"data_kind_flag,omitempty"`     // 基础信息分类是否智能推荐 (1 是 ; 0 否)
	LabelFlag              *int8      `gorm:"column:label_flag;not null;default:0" json:"label_flag,omitempty"`             // 标签是否智能推荐 (1 是 ; 0 否)
	SrcEventFlag           *int8      `gorm:"column:src_event_flag;not null;default:0" json:"src_event_flag,omitempty"`     // 来源业务场景是否智能推荐 (1 是 ; 0 否)
	RelEventFlag           *int8      `gorm:"column:rel_event_flag;not null;default:0" json:"rel_event_flag,omitempty"`     // 关联业务场景是否智能推荐 (1 是 ; 0 否)
	SystemFlag             *int8      `gorm:"column:system_flag;not null;default:0" json:"system_flag,omitempty"`           // 关联信息系统是否智能推荐 (1 是 ; 0 否)
	RelCatalogFlag         *int8      `gorm:"column:rel_catalog_flag;not null;default:0" json:"rel_catalog_flag,omitempty"` // 关联目录是否智能推荐 (1 是 ; 0 否)
	IsIndexed              int8       `gorm:"column:is_indexed" json:"is_indexed"`                                          // 是否已建ES索引，0 否 1 是，默认为0
	AuditApplySN           uint64     `gorm:"column:audit_apply_sn;not null" json:"audit_apply_sn"`                         // 发起审核申请序号
	AuditAdvice            string     `gorm:"audit_advice" json:"audit_advice"`
	OwnerId                string     `gorm:"column:owner_id;not null" json:"owner_id"`                                                                                                                                // 目录数据owner的用户ID
	OwnerName              string     `gorm:"column:owner_name;not null" json:"owner_name"`                                                                                                                            // 审核意见，仅驳回时有用
	IsCanceled             *int8      `gorm:"is_canceled" json:"is_canceled"`                                                                                                                                          // 目录下线时针对该目录的关联申请是否已撤销，0 待撤销 1 已撤销
	ProcDefKey             string     `gorm:"column:proc_def_key" json:"proc_def_key"`                                                                                                                                 // 审核流程key
	FlowApplyId            string     `gorm:"column:flow_apply_id" json:"flow_apply_id"`                                                                                                                               // 审核流程ID
	AuditType              string     `gorm:"column:audit_type;type:varchar(50);not null;default:unpublished;comment:审核类型 unpublished 未发布 af-data-catalog-online 上线审核 af-data-catalog-offline 下线审核" json:"audit_type"` // 审核类型 unpublished 未发布 af-data-catalog-online 上线审核 af-data-catalog-offline  下线审核
	AuditState             int        `gorm:"audit_state" json:"audit_state"`                                                                                                                                          // 审核状态，1 审核中  2 通过  3 驳回
	PublishStatus          string     `gorm:"column:publish_status;type:varchar(20);not null;default:unpublished;comment:发布状态" json:"publish_status"`                                                                  // 发布状态 未发布unpublished 、发布审核中pub-auditing、已发布published、发布审核未通过pub-reject、变更审核中change-auditing、变更审核未通过change-reject
	PublishedAt            *time.Time `gorm:"column:published_at" json:"published_at,omitempty"`                                                                                                                       // 上线发布时间
	OnlineStatus           string     `gorm:"column:online_status;type:varchar(20);not null;default:notline;comment:上线状态 " json:"status"`                                                                              // 上线状态 未上线 notline、已上线 online、已下线offline、上线审核中up-auditing、下线审核中down-auditing、上线审核未通过up-reject、已下线（上线审核中）offline-up-auditing、已下线（上线审核未通过）offline-up-reject、下线审核未通过down-reject
	OnlineTime             *time.Time `gorm:"column:online_time;type:datetime;comment:上线时间" json:"online_time"`                                                                                                        // 上线时间
	AppSceneClassify       *int8      `gorm:"column:app_scene_classify" json:"app_scene_classify"`                                                                                                                     // 应用场景分类
	OthersAppSceneClassify string     `gorm:"column:other_app_scene_classify" json:"other_app_scene_classify"`                                                                                                         // 其他应用场景分类
	SourceDepartmentID     string     `gorm:"column:source_department_id" json:"source_department_id"`                                                                                                                 // 数据资源来源部门id
	DataRelatedMatters     string     `gorm:"column:data_related_matters" json:"data_related_matters"`                                                                                                                 // 数据所属事项
	BusinessMatters        string     `gorm:"column:business_matters" json:"business_matters"`                                                                                                                         // 业务事项,替代data_related_matters
	DataClassify           string     `gorm:"column:data_classify" json:"data_classify"`                                                                                                                               // 数据分级【标签】
	DataDomain             int32      `gorm:"column:data_domain" json:"data_domain"`                                                                                                                                   // 数据所在领域
	DataLevel              int32      `gorm:"column:data_level" json:"data_level"`                                                                                                                                     // 数据所在层级
	TimeRange              string     `gorm:"column:time_range" json:"time_range"`                                                                                                                                     // 数据时间范围
	ProviderChannel        int32      `gorm:"column:provider_channel" json:"provider_channel"`                                                                                                                         // 提供渠道
	AdministrativeCode     *int32     `gorm:"column:administrative_code" json:"administrative_code" `                                                                                                                  // 行政区划代码
	CentralDepartmentCode  int32      `gorm:"column:central_department_code" json:"central_department_code"`                                                                                                           // 中央业务指导部门代码
	ProcessingLevel        string     `gorm:"column:processing_level" json:"processing_level"`                                                                                                                         // 数据加工程度
	CatalogTag             int32      `gorm:"column:catalog_tag" json:"catalog_tag"`                                                                                                                                   // 目录标签
	IsElectronicProof      *bool      `gorm:"column:is_electronic_proof" json:"is_electronic_proof"`                                                                                                                   // 是否电子证明编码
	DraftID                uint64     `gorm:"column:draft_id" json:"draft_id"`                                                                                                                                         // 草稿id
	ApplyNum               int64      `gorm:"column:apply_num" json:"apply_num"`                                                                                                                                       // 申请量
	OperationAuthorized    *int8      `gorm:"column:operation_authorized" json:"operation_authorized"`                                                                                                                 // 是否可授权运营字段
	IsImport               bool       `gorm:"column:is_import" json:"is_import"`                                                                                                                                       // 是否导入
}

func (m *TDataCatalog) UniqueKey() string {
	return "id"
}

func (m *TDataCatalog) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}
	now := time.Now()

	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return err
}

// TableName TDataCatalog's table name
func (*TDataCatalog) TableName() string {
	return TableNameTDataCatalog
}

type TDataCatalogApply struct {
	ID         int64  `json:"id"`
	CatalogID  int64  `json:"catalog_id"`
	ApplyNum   int32  `json:"apply_num"`
	CreateTime string `json:"create_time"`
}

func (*TDataCatalogApply) TableName() string {
	return TableNameTDataCatalogApply
}

type TDataInterfaceApply struct {
	ID          int64  `json:"id"`
	InterfaceID string `json:"interface_id"`
	ApplyNum    int32  `json:"apply_num"`
	BizDate     string `json:"biz_date"`
}

func (*TDataInterfaceApply) TableName() string {
	return TableNameTDataINTERFACEApply
}

type TDataInterfaceAggregate struct {
	ID          int64  `gorm:"primaryKey;autoIncrement" json:"id"`
	InterfaceID string `gorm:"column:interface_id" json:"interface_id"`
	ApplyNum    int64  `gorm:"column:apply_num" json:"apply_num"`
	ServiceName string `gorm:"column:service_name" json:"service_name"`
}

func (*TDataInterfaceAggregate) TableName() string {
	return TableNameTDataInterfaceAggregate
}
