// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogResource = "t_data_catalog_resource"

// TDataCatalogResourceWithName mapped from table <t_data_catalog_resource>
type TDataCatalogResource struct {
	ID             uint64 `gorm:"column:id;primaryKey" json:"id"`                         // 标识
	CatalogID      uint64 `gorm:"column:catalog_id" json:"catalog_id"`                    // 目录id
	ResourceID     string `gorm:"column:resource_id" json:"resource_id"`                  // 数据资源id
	RequestFormat  string `gorm:"column:request_format;not null" json:"request_format"`   // 请求报文格式
	ResponseFormat string `gorm:"column:response_format;not null" json:"response_format"` // 响应报文格式
	SchedulingPlan int32  `gorm:"column:scheduling_plan" json:"scheduling_plan"`          // 调度计划 1 一次性、2按分钟、3按天、4按周、5按月
	Interval       int32  `gorm:"column:interval" json:"interval"`                        // 间隔
	Time           string `gorm:"column:time" json:"time"`                                // 时间
}

// TableName TDataCatalogResourceWithName's table name
func (*TDataCatalogResource) TableName() string {
	return TableNameTDataCatalogResource
}
func (m *TDataCatalogResource) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}
