// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogResourceMount = "t_data_catalog_resource_mount"

// TDataCatalogResourceMount mapped from table <t_data_catalog_resource_mount>
type TDataCatalogResourceMount struct {
	ID        uint64 `gorm:"column:id;primaryKey" json:"id"`               // 唯一id，雪花算法
	CatalogID uint64 `gorm:"column:catalog_id;not null" json:"catalog_id"` // 数据资源目录ID
	ResType   int8   `gorm:"column:res_type;not null" json:"res_type"`     // 挂接资源类型 1逻辑视图 2 接口
	ResID     string `gorm:"column:res_id;not null" json:"res_id"`         // 挂接资源ID
	ResName   string `gorm:"column:res_name;not null" json:"res_name"`     // 挂接资源名称
	Code      string `gorm:"column:code;not null" json:"code"`             // 目录编码
}

func (m *TDataCatalogResourceMount) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataCatalogResourceMount's table name
func (*TDataCatalogResourceMount) TableName() string {
	return TableNameTDataCatalogResourceMount
}
