// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataPushModel = "t_data_push_model"

// TDataPushModel mapped from table <t_data_push_model>
type TDataPushModel struct {
	ID                  uint64 `gorm:"column:id;primaryKey" json:"id"`                                     // 主键ID
	Name                string `gorm:"column:name;not null" json:"name"`                                   // 模型名
	Description         string `gorm:"column:description" json:"description"`                              // 描述
	ResponsiblePersonID string `gorm:"column:responsible_person_id;not null" json:"responsible_person_id"` // 责任人
	Channel             int32  `gorm:"column:channel;not null" json:"channel"`                             // 渠道，1web,2share_apply,3catalog_report
	PushStatus          int32  `gorm:"column:push_status;not null" json:"push_status"`                     // 推送状态,1待发布，2未开始，3进行中，4已结束，5已停用
	Operation           int32  `gorm:"column:operation;not null" json:"operation"`                         // 操作,1发布审核，2变更审核，3停用审核，4启用审核
	PushError           string `gorm:"push_error" json:"push_error"`                                       // 推送错误
	//推送策略
	TransmitMode       int32  `gorm:"column:transmit_mode;not null" json:"transmit_mode"`    // 传输模式(1 增量 ; 2 全量)
	IncrementField     string `gorm:"column:increment_field" json:"increment_field"`         // 增量字段，传输模式是增量时候填写
	IncrementTimestamp int64  `gorm:"column:increment_timestamp" json:"increment_timestamp"` // 增量时间，传输模式是增量时候填写, 秒为单位
	PrimaryKey         string `gorm:"column:primary_key" json:"primary_key"`                 // 主键， 传输模式是增量时候填写
	//推送内容
	SourceCatalogID      uint64 `gorm:"column:source_catalog_id;not null" json:"source_catalog_id"`           // 目录主键ID
	SourceDatasourceUUID string `gorm:"column:source_datasource_uuid;not null" json:"source_datasource_uuid"` // 目标表所在的数据源UUID
	SourceHuaAoId        string `gorm:"column:source_hua_ao_id" json:"source_hua_ao_id"`                      // 来源数据的华傲ID
	SourceDatasourceID   uint64 `gorm:"column:source_datasource_id;not null" json:"source_datasource_id"`     // 目标表所在的数据源雪花ID
	SourceTableID        string `gorm:"column:source_table_id;not null" json:"source_table_id"`               // 来源表ID，视图的uuid
	SourceTableName      string `gorm:"column:source_table_name;not null" json:"source_table_name"`           // 来源表名称，技术名称
	SourceDepartmentID   string `gorm:"column:source_department_id;not null" json:"source_department_id"`     // 来源数据的部门ID
	TargetDatasourceUUID string `gorm:"column:target_datasource_uuid;not null" json:"target_datasource_uuid"` // 目标表所在的数据源UUID
	TargetHuaAoId        string `gorm:"column:target_hua_ao_id" json:"target_hua_ao_id"`                      // 目标数据的华傲ID
	TargetDatasourceID   uint64 `gorm:"column:target_datasource_id;not null" json:"target_datasource_id"`     // 目标表所在的数据源雪花ID
	TargetSandboxID      string `gorm:"column:target_sandbox_id;default ''" json:"target_sandbox_id"`         // 目标表所在的沙箱空间ID，可能为空
	TargetDepartmentID   string `gorm:"column:target_department_id;not null" json:"target_department_id"`     // 目标数据的部门ID
	TargetTableExists    int32  `gorm:"column:target_table_exists;not null" json:"target_table_exists"`       // 目标表是否是本次新建的
	TargetTableName      string `gorm:"column:target_table_name;not null" json:"target_table_name"`           // 目标表名称
	FilterCondition      string `gorm:"column:filter_condition" json:"filter_condition"`                      // 过滤表达式，SQL后面的where条件
	IsDesensitization    int32  `gorm:"column:is_desensitization;not null" json:"is_desensitization"`         // 是否脱敏，0为否，1为是
	//调度计划
	ScheduleType  string         `gorm:"column:schedule_type;not null" json:"schedule_type"` // 调度计划:none一次性,timely定时
	ScheduleTime  string         `gorm:"column:schedule_time;not null" json:"schedule_time"` // 调度时间，0立即执行，>0 定时
	ScheduleStart string         `gorm:"column:schedule_start" json:"schedule_start"`        // 计划开始日期, 2025-01-25
	ScheduleEnd   string         `gorm:"column:schedule_end" json:"schedule_end"`            // 计划结束日期, 2025-01-25
	CrontabExpr   string         `gorm:"column:crontab_expr" json:"crontab_expr"`            // linux crontab表达式, 5级
	DraftSchedule sql.NullString `gorm:"column:draft_schedule" json:"draft_schedule"`        // 调度时间草稿
	//dolphin关键信息
	DolphinWorkflowID      string `gorm:"column:dolphin_workflow_id;default:''" json:"dolphin_workflow_id"`           // dolphin工作流ID
	CreateSQL              string `gorm:"column:create_sql;not null" json:"create_sql"`                               // 同步模型的建表语句
	InsertSQL              string `gorm:"column:insert_sql;not null" json:"insert_sql"`                               // 同步模型的插入语句
	UpdateSQL              string `gorm:"column:update_sql;not null" json:"update_sql"`                               // 同步模型的更新语句
	UpdateExistingDataFlag int32  `gorm:"column:update_existing_data_flag;not null" json:"update_existing_data_flag"` // 是否更新已存在的数据，0不更新，1更新
	//审核信息
	AuditState  int32  `gorm:"column:audit_state;not null" json:"audit_state"` // 审核状态,1审核中，2审核通过，3未通过
	ApplyID     string `gorm:"column:apply_id" json:"apply_id"`                // 审批流程申请ID
	ProcDefKey  string `gorm:"column:proc_def_key" json:"proc_def_key"`        // 审核流程定义的key
	AuditAdvice string `gorm:"audit_advice" json:"audit_advice"`               // 审核意见
	//基本字段
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	CreatorUID  string    `gorm:"column:creator_uid" json:"creator_uid"`                                     // 创建用户ID
	CreatorName string    `gorm:"column:creator_name" json:"creator_name"`                                   // 创建用户名称
	ThirdUserId string    `gorm:"column:f_third_user_id" json:"third_user_id"`                               // 创建者第三方用户ID
	ThirdDeptId string    `gorm:"column:f_third_dept_id" json:"third_dept_id"`                               // 创建者第三方部门ID
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`               // 更新时间
	UpdaterUID  string    `gorm:"column:updater_uid" json:"updater_uid"`                                     // 更新用户ID
	UpdaterName string    `gorm:"column:updater_name" json:"updater_name"`                                   // 更新用户名称
	DeletedAt   int64     `gorm:"column:deleted_at" json:"deleted_at"`                                       // 删除时间(逻辑删除)
}

func (m *TDataPushModel) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataPushModel's table name
func (*TDataPushModel) TableName() string {
	return TableNameTDataPushModel
}
