// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogSearchHistory = "t_data_catalog_search_history"

// TDataCatalogSearchHistory mapped from table <t_data_catalog_search_history>
type TDataCatalogSearchHistory struct {
	CatalogSearchHistoryID uint64    `gorm:"column:catalog_search_history_id;primaryKey" json:"catalog_search_history_id"`
	ID                     string    `gorm:"column:id" json:"id"`
	DataCatalogID          uint64    `gorm:"column:data_catalog_id;not null" json:"data_catalog_id"`
	Fields                 string    `gorm:"column:fields" json:"fields"`
	FieldsDetails          string    `gorm:"column:fields_details" json:"fields_details"`
	Configs                string    `gorm:"column:configs" json:"configs"`
	Type                   string    `gorm:"column:type;comment:左侧目录类型，department\authorization" json:"type"` // 左侧目录类型，department\authorization
	DepartmentPath         string    `gorm:"column:department_path" json:"department_path"`
	TotalCount             int       `gorm:"column:total_count" json:"total_count"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	CreatedByUID           string    `gorm:"column:created_by_uid" json:"created_by_uid"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
	UpdatedByUID           string    `gorm:"column:updated_by_uid" json:"updated_by_uid"`
	DeletedAt              int32     `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName TDataCatalogSearchHistory's table name
func (*TDataCatalogSearchHistory) TableName() string {
	return TableNameTDataCatalogSearchHistory
}

type TDataCatalogSearchHistoryData struct {
	ID              string    `gorm:"column:id" json:"id"`
	Type            string    `gorm:"column:type;comment:左侧数据目录来源类型：department、authorization" json:"type"`
	DataCatalogId   string    `gorm:"column:data_catalog_id" json:"data_catalog_id"`
	DataCatalogName string    `gorm:"column:data_catalog_name" json:"data_catalog_name"`
	TDepartmentPath string    `gorm:"column:t_department_path" json:"t_department_path"`
	DDepartmentId   string    `gorm:"column:d_department_id" json:"d_department_id"`
	TotalCount      int32     `gorm:"column:total_count" json:"total_count"`
	SearchAt        time.Time `gorm:"column:search_at" json:"search_at"`
}

func (d *TDataCatalogSearchHistory) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.CatalogSearchHistoryID == 0 {
		d.CatalogSearchHistoryID, err = utils.GetUniqueID()
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}
