// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/plugin/soft_delete"
	"time"

	"gorm.io/gorm"
)

const TableNameTDataComprehensionTemplate = "t_data_comprehension_template"

// TDataComprehensionTemplate mapped from table <t_data_comprehension_template>
type TDataComprehensionTemplate struct {
	ID                        string                `gorm:"column:id;primaryKey" json:"id"`
	Name                      string                `gorm:"column:name;not null;comment:理解模板名称" json:"name"`                                      // 理解模板名称
	Description               string                `gorm:"column:description;comment:理解模板描述" json:"description"`                                 // 理解模板描述
	BusinessObject            bool                  `gorm:"column:business_object;comment:业务对象" json:"business_object"`                           // 业务对象
	TimeRange                 bool                  `gorm:"column:time_range;comment:时间范围" json:"time_range"`                                     // 时间范围
	TimeFieldComprehension    bool                  `gorm:"column:time_field_comprehension;comment:时间字段理解" json:"time_field_comprehension"`       // 时间字段理解
	SpatialRange              bool                  `gorm:"column:spatial_range;comment:空间范围" json:"spatial_range"`                               // 空间范围
	SpatialFieldComprehension bool                  `gorm:"column:spatial_field_comprehension;comment:空间字段理解" json:"spatial_field_comprehension"` // 空间字段理解
	BusinessSpecialDimension  bool                  `gorm:"column:business_special_dimension;comment:业务特殊维度" json:"business_special_dimension"`   // 业务特殊维度
	CompoundExpression        bool                  `gorm:"column:compound_expression;comment:复合表达" json:"compound_expression"`                   // 复合表达
	ServiceRange              bool                  `gorm:"column:service_range;comment:服务范围" json:"service_range"`                               // 服务范围
	ServiceAreas              bool                  `gorm:"column:service_areas;comment:服务领域" json:"service_areas"`                               // 服务领域
	FrontSupport              bool                  `gorm:"column:front_support;comment:正面支撑" json:"front_support"`                               // 正面支撑
	NegativeSupport           bool                  `gorm:"column:negative_support;comment:负面支撑" json:"negative_support"`                         // 负面支撑
	ProtectControl            bool                  `gorm:"column:protect_control;comment:保护/控制什么" json:"protect_control"`                        // 保护/控制什么
	PromotePush               bool                  `gorm:"column:promote_push;comment:促进/推动什么" json:"promote_push"`                              // 促进/推动什么
	CreatedAt                 time.Time             `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                            // 创建时间
	CreatedUID                string                `gorm:"column:created_uid;not null;comment:创建人" json:"created_uid"`                           // 创建人
	UpdatedAt                 time.Time             `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                     // 更新时间
	UpdatedUID                string                `gorm:"column:updated_uid;comment:更新人" json:"updated_uid"`                                    // 更新人
	DeletedAt                 soft_delete.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                     // 删除时间
	DeletedUID                string                `gorm:"column:deleted_uid;comment:删除人" json:"deleted_uid"`                                    // 删除人
}

// TableName TDataComprehensionTemplate's table name
func (*TDataComprehensionTemplate) TableName() string {
	return TableNameTDataComprehensionTemplate
}

func (d *TDataComprehensionTemplate) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}

func (d *TDataComprehensionTemplate) BeforeUpdate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return nil
}
