// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataAssetsInfo = "t_data_assets_info"

// TDataAssetsInfo mapped from table <t_data_assets_info>
type TDataAssetsInfo struct {
	ID                       uint64 `gorm:"column:id;primaryKey" json:"id"`                                                 // 唯一id，雪花算法
	BusinessDomainCount      int32  `gorm:"column:business_domain_count;not null" json:"business_domain_count"`             // 业务域数量
	SubjectDomainCount       int32  `gorm:"column:subject_domain_count;not null" json:"subject_domain_count"`               // 主题域数量
	BusinessObjectCount      int32  `gorm:"column:business_object_count;not null" json:"business_object_count"`             // 业务对象数量
	BusinessLogicEntityCount int32  `gorm:"column:business_logic_entity_count;not null" json:"business_logic_entity_count"` // 已发布的业务逻辑实体数量
	BusinessAttributesCount  int32  `gorm:"column:business_attributes_count;not null" json:"business_attributes_count"`     // 业务属性数量
}

func (m *TDataAssetsInfo) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataAssetsInfo's table name
func (*TDataAssetsInfo) TableName() string {
	return TableNameTDataAssetsInfo
}
