// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogColumn = "t_data_catalog_column"

// TDataCatalogColumn mapped from table <t_data_catalog_column>
type TDataCatalogColumn struct {
	PrimaryID     int    `gorm:"column:primary_id" json:"primary_id"`                                // 主键id
	ID            uint64 `gorm:"column:id;primaryKey" json:"id,string"`                              // 唯一id，雪花算法
	CatalogID     uint64 `gorm:"column:catalog_id;not null" json:"catalog_id,string"`                // 数据资源目录ID
	TechnicalName string `gorm:"column:technical_name;not null;comment:列技术名称" json:"technical_name"` // 技术名称
	BusinessName  string `gorm:"column:business_name;comment:列业务名称" json:"business_name"`            // 业务名称
	SourceID      string `gorm:"column:source_id;comment:来源id" json:"source_id"`                     // 来源id
	//ColumnName      string `gorm:"column:column_name;not null" json:"column_name"`                     // 字段名称
	//NameCn          string `gorm:"column:name_cn;not null" json:"name_cn"`                             // 信息项名称
	DataFormat *int32 `gorm:"column:data_format;comment:数据类型" json:"data_format"` // 数据类型 0:数字型 1:字符型 2:日期型 3:日期时间型 5:布尔型 6:其他 7:小数型 8:高精度型 9:时间型
	//DataType   string `gorm:"column:data_type;not null;comment:数据类型" json:"data_type"`     // 数据类型
	DataLength    *int32 `gorm:"column:data_length" json:"data_length"`       // 数据长度
	DataPrecision *int32 `gorm:"column:data_precision" json:"data_precision"` // 数据精度
	//DatametaID      string `gorm:"column:datameta_id" json:"datameta_id"`                              // 关联数据元ID
	//DatametaName    string `gorm:"column:datameta_name" json:"datameta_name"`                          // 关联数据元名称
	Ranges string `gorm:"column:ranges" json:"ranges"` // 字段值域
	//CodesetID       string `gorm:"column:codeset_id" json:"-"`                                         // 关联代码集ID
	//CodesetName     string `gorm:"column:codeset_name" json:"-"`                                       // 关联代码集名称
	SharedType     int8          `gorm:"column:shared_type;not null" json:"shared_type"`         // 共享属性 1 无条件共享 2 有条件共享 3 不予共享
	OpenType       int8          `gorm:"column:open_type;not null" json:"open_type"`             // 开放属性 1 向公众开放 2 不向公众开放
	TimestampFlag  sql.NullInt16 `gorm:"column:timestamp_flag;not null" json:"timestamp_flag"`   // 是否时间戳(1 是 ; 0 否)
	PrimaryFlag    sql.NullInt16 `gorm:"column:primary_flag;not null" json:"primary_flag"`       // 是否主键(1 是 ; 0 否)
	NullFlag       *int8         `gorm:"column:null_flag;not null" json:"null_flag"`             // 是否为空(1 是 ; 0 否)
	ClassifiedFlag sql.NullInt16 `gorm:"column:classified_flag;not null" json:"classified_flag"` // 是否涉密属性(1 是 ; 0 否)
	SensitiveFlag  sql.NullInt16 `gorm:"column:sensitive_flag;not null" json:"sensitive_flag"`   // 是否敏感属性(1 是 ; 0 否)
	Description    string        `gorm:"column:description" json:"description"`                  // 字段描述
	AIDescription  string        `gorm:"column:ai_description" json:"ai_description"`            // 在AI数据理解下生成的字段描述
	//SharedCondition string         `gorm:"column:shared_condition" json:"shared_condition,omitempty"`  // 共享条件
	OpenCondition string         `gorm:"column:open_condition" json:"open_condition,omitempty"`      // 开放条件
	StandardCode  sql.NullString `gorm:"column:standard_code;comment:数据标准code" json:"standard_code"` // 关联数据标准code
	CodeTableID   sql.NullString `gorm:"column:code_table_id;comment:关联码表ID" json:"code_table_id"`   // 关联码表ID

	SourceSystem      string `gorm:"column:source_system" json:"source_system"`             // 来源系统
	SourceSystemLevel int32  `gorm:"column:source_system_level" json:"source_system_level"` // 来源系统分级 1 自建自用 2 国直(国家部委统一平台) 3省直(省级统一平台) 4市直(市级统一平台) 5县直(县级统一平台)
	//InfoItemLevel     int32  `gorm:"column:info_item_level" json:"info_item_level"`         // 信息项分级 1级 2级 3级 4级
	Index int `gorm:"column:index" json:"index"` // 信息项顺序
}

func (m *TDataCatalogColumn) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataCatalogColumn's table name
func (*TDataCatalogColumn) TableName() string {
	return TableNameTDataCatalogColumn
}
