// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataResource = "t_data_resource"

// TDataResource mapped from table <t_data_resource>
type TDataResource struct {
	ID             uint64     `gorm:"column:id;primaryKey" json:"id"`                            // 标识
	ResourceId     string     `gorm:"column:resource_id;not null" json:"resource_id"`            // 数据资源id
	Name           string     `gorm:"column:name;not null" json:"name"`                          // 数据资源名称
	Code           string     `gorm:"column:code;not null" json:"code"`                          // 统一编目编码
	Type           int8       `gorm:"column:type;not null" json:"type"`                          // 数据资源类型 枚举值 1：逻辑视图 2：接口 3:文件资源
	ViewId         string     `gorm:"column:view_id" json:"view_id"`                             // 数据资源类型 为 2：接口 时候类型为接口生成方式来源视图id
	InterfaceCount int        `gorm:"column:interface_count" json:"interface_count"`             // 生成接口数量
	DepartmentId   string     `gorm:"column:department_id;not null" json:"department_id"`        // 所属部门id
	SubjectId      string     `gorm:"column:subject_id" json:"subject_id"`                       // 所属主题id
	RequestFormat  string     `gorm:"column:request_format;not null" json:"request_format"`      // 请求报文格式
	ResponseFormat string     `gorm:"column:response_format;not null" json:"response_format"`    // 响应报文格式
	CatalogID      uint64     `gorm:"column:catalog_id;not null" json:"catalog_id"`              // 数据资源目录ID
	PublishAt      *time.Time `gorm:"column:publish_at;not null" json:"publish_at"`              // 发布时间
	SchedulingPlan int32      `gorm:"column:scheduling_plan" json:"scheduling_plan"`             // 调度计划 1 一次性、2按分钟、3按天、4按周、5按月
	Interval       int32      `gorm:"column:interval" json:"interval"`                           // 间隔
	Time           string     `gorm:"column:time" json:"time"`                                   // 时间
	Status         int8       `gorm:"column:status;not null;comment:视图状态,1正常,2删除" json:"status"` // 视图状态,1正常,2删除

}

// TableName TDataResource's table name
func (*TDataResource) TableName() string {
	return TableNameTDataResource
}

func (m *TDataResource) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}
	if m.Status == 0 {
		m.Status = 1
	}

	return err
}
