// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataPushField = "t_data_push_fields"

// TDataPushField mapped from table <t_data_push_fields>
type TDataPushField struct {
	ID                    uint64 `gorm:"column:id;primaryKey" json:"id"`                                // 主键ID
	ModelID               uint64 `gorm:"column:model_id;primaryKey" json:"model_id"`                    // 推送模型的主键ID
	SourceTechName        string `gorm:"column:source_tech_name;not null" json:"source_tech_name"`      // 来源字段的字数名称
	TechnicalName         string `gorm:"column:technical_name;not null" json:"technical_name"`          // 列技术名称
	BusinessName          string `gorm:"column:business_name" json:"business_name"`                     // 列业务名称
	DataType              string `gorm:"column:data_type;not null" json:"data_type"`                    // 数据类型
	DataLength            int32  `gorm:"column:data_length;not null" json:"data_length"`                // 数据长度
	DataAccuracy          *int32 `gorm:"column:data_accuracy" json:"data_accuracy"`                     // 数据精度（仅DECIMAL类型）
	PrimaryKey            int32  `gorm:"column:primary_key" json:"primary_key"`                         // 是否是主键,0不是，1是
	IsNullable            string `gorm:"column:is_nullable;not null" json:"is_nullable"`                // 是否为空
	Comment               string `gorm:"column:comment" json:"comment"`                                 // 字段注释
	DesensitizationRuleId string `gorm:"column:desensitization_rule_id" json:"desensitization_rule_id"` // 脱敏规则id
}

func (m *TDataPushField) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataPushField's table name
func (*TDataPushField) TableName() string {
	return TableNameTDataPushField
}
