// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogInfo = "t_data_catalog_info"

// TDataCatalogInfo mapped from table <t_data_catalog_info>
type TDataCatalogInfo struct {
	ID        uint64 `gorm:"column:id;primaryKey" json:"id"`               // 唯一id，雪花算法
	CatalogID uint64 `gorm:"column:catalog_id;not null" json:"catalog_id"` // 数据资源目录ID
	InfoType  int8   `gorm:"column:info_type;not null" json:"info_type"`   // 关联信息类型 1 标签 2 来源业务场景 3 关联业务场景 4 关联系统 5 关联目录、信息项 6 业务域
	InfoKey   string `gorm:"column:info_key;not null" json:"info_key"`     // 关联信息key（仅当info_type为5时为关联目录ID，其它情况下为ID或枚举值）
	InfoValue string `gorm:"column:info_value;not null" json:"info_value"` // 关联信息名称（info_type为5时表示关联目录及其信息项的json字符串）
}

func (m *TDataCatalogInfo) UniqueKey() string {
	return "id"
}

func (m *TDataCatalogInfo) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataCatalogInfo's table name
func (*TDataCatalogInfo) TableName() string {
	return TableNameTDataCatalogInfo
}
