// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogCategory = "t_data_catalog_category"

// TDataCatalogCategory mapped from table <t_data_catalog_category>
type TDataCatalogCategory struct {
	ID           uint64 `gorm:"column:id;primaryKey" json:"id"`                     // 主键
	CategoryID   string `gorm:"column:category_id;not null" json:"category_id"`     // 分类ID
	CategoryType int32  `gorm:"column:category_type;not null" json:"category_type"` // 分类类型 部门 信息系统 自定义
	CatalogID    uint64 `gorm:"column:catalog_id;not null" json:"catalog_id"`       // 目录ID
}

// TableName TDataCatalogCategory's table name
func (*TDataCatalogCategory) TableName() string {
	return TableNameTDataCatalogCategory
}
func (m *TDataCatalogCategory) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}
	return err
}
