// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
	"time"
)

const TableNameTFormDataCount = "t_form_data_count"

// TFormDataCount mapped from table <t_form_data_count>
type TFormDataCount struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`                   // id,uuid
	FormViewID string    `gorm:"column:form_view_id;not null" json:"form_view_id"` // 视图id
	DataCount  int32     `gorm:"column:data_count;not null" json:"data_count"`     // 数据量
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`     // 创建时间
}

func (m *TFormDataCount) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TFormDataCount's table name
func (*TFormDataCount) TableName() string {
	return TableNameTFormDataCount
}
