// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTInfoResourceCatalogSourceInfo = "t_info_resource_catalog_source_info"

// TInfoResourceCatalogSourceInfo mapped from table <t_info_resource_catalog_source_info>
type TInfoResourceCatalogSourceInfo struct {
	//FID               uint64  `gorm:"column:f_id;primaryKey" json:"f_id"`                               // 信息资源目录ID
	FBusinessFormID   string `gorm:"column:f_business_form_id;not null" json:"f_business_form_id"`     // 来源业务表ID
	FBusinessFormName string `gorm:"column:f_business_form_name;not null" json:"f_business_form_name"` // 来源业务表名称
	FDepartmentID     string `gorm:"column:f_department_id;not null" json:"f_department_id"`           // 来源部门ID
	FDepartmentName   string `gorm:"column:f_department_name;not null" json:"f_department_name"`       // 来源部门名称
}

// TableName TInfoResourceCatalogSourceInfo's table name
func (*TInfoResourceCatalogSourceInfo) TableName() string {
	return TableNameTInfoResourceCatalogSourceInfo
}
