// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTInfoResourceCatalogColumnRelatedInfo = "t_info_resource_catalog_column_related_info"

// TInfoResourceCatalogColumnRelatedInfo mapped from table <t_info_resource_catalog_column_related_info>
type TInfoResourceCatalogColumnRelatedInfo struct {
	//FRID            uint64  `gorm:"column:f_ids;primaryKey" json:"f_ids"`                         // 信息项ID
	FCodeSetID     int64  `gorm:"column:f_code_set_id;not null" json:"f_code_set_id"`         // 关联代码集ID
	FCodeSetName   string `gorm:"column:f_code_set_name;not null" json:"f_code_set_name"`     // 关联代码集名称
	FDataReferID   int64  `gorm:"column:f_data_refer_id;not null" json:"f_data_refer_id"`     // 关联数据元ID
	FDataReferName string `gorm:"column:f_data_refer_name;not null" json:"f_data_refer_name"` // 关联数据元名称
}

// TableName TInfoResourceCatalogColumnRelatedInfo's table name
func (*TInfoResourceCatalogColumnRelatedInfo) TableName() string {
	return TableNameTInfoResourceCatalogColumnRelatedInfo
}
