// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTInfoResourceCatalogRelatedItem = "t_info_resource_catalog_related_item"

// TInfoResourceCatalogRelatedItem mapped from table <t_info_resource_catalog_related_item>
type TInfoResourceCatalogRelatedItem struct {
	FID                    uint64 `gorm:"column:f_id;primaryKey;autoIncrement:true" json:"f_id"`                        // 自增主键
	FInfoResourceCatalogID int64  `gorm:"column:f_info_resource_catalog_id;not null" json:"f_info_resource_catalog_id"` // 信息资源目录ID
	FRelatedItemID         string `gorm:"column:f_related_item_id;not null" json:"f_related_item_id"`                   // 关联项ID
	FRelatedItemName       string `gorm:"column:f_related_item_name;not null" json:"f_related_item_name"`               // 关联项名称
	FRelationType          int8   `gorm:"column:f_relation_type;not null" json:"f_relation_type"`                       // 关联类型
	FRelatedItemDataType   string `gorm:"column:f_related_item_data_type;not null" json:"f_related_item_data_type"`     // 关联信息项数据类型
}

// TableName TInfoResourceCatalogRelatedItem's table name
func (*TInfoResourceCatalogRelatedItem) TableName() string {
	return TableNameTInfoResourceCatalogRelatedItem
}
