// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTInfoResourceCatalog = "t_info_resource_catalog"

// TInfoResourceCatalog mapped from table <t_info_resource_catalog>
type TInfoResourceCatalog struct {
	FID                           uint64 `gorm:"column:f_id" json:"f_id"`                                                       // 主键ID
	FName                         string `gorm:"column:f_name;not null" json:"f_name"`                                                     // 信息资源目录名称
	FCode                         string `gorm:"column:f_code;not null" json:"f_code"`                                                     // 信息资源目录编码
	FDataRange                    int32  `gorm:"column:f_data_range;not null" json:"f_data_range"`                                         // 数据范围
	FUpdateCycle                  int32  `gorm:"column:f_update_cycle;not null" json:"f_update_cycle"`                                     // 更新周期
	FOfficeBusinessResponsibility string `gorm:"column:f_office_business_responsibility;not null" json:"f_office_business_responsibility"` // 处室业务职责
	FDescription                  string `gorm:"column:f_description;not null" json:"f_description"`                                       // 信息资源目录描述
	FSharedType                   int32  `gorm:"column:f_shared_type;not null" json:"f_shared_type"`                                       // 共享属性
	FSharedMessage                string `gorm:"column:f_shared_message;not null" json:"f_shared_message"`                                 // 共享信息：共享属性为不予共享时是不予共享依据，共享属性为有条件共享时是共享条件
	FSharedMode                   int32  `gorm:"column:f_shared_mode;not null" json:"f_shared_mode"`                                       // 共享方式
	FOpenType                     int32  `gorm:"column:f_open_type;not null" json:"f_open_type"`                                           // 开放属性
	FOpenCondition                string `gorm:"column:f_open_condition;not null" json:"f_open_condition"`                                 // 开放条件
	FPublishStatus                int32  `gorm:"column:f_publish_status;not null" json:"f_publish_status"`                                 // 发布状态
	FPublishAt                    int64  `gorm:"column:f_publish_at;not null" json:"f_publish_at"`                                         // 发布时间
	FOnlineStatus                 int32  `gorm:"column:f_online_status;not null" json:"f_online_status"`                                   // 上线状态
	FOnlineAt                     int64  `gorm:"column:f_online_at;not null" json:"f_online_at"`                                           // 上线时间
	FUpdateAt                     int64  `gorm:"column:f_update_at;not null" json:"f_update_at"`                                           // 更新时间
	FDeleteAt                     int64  `gorm:"column:f_delete_at;not null" json:"f_delete_at"`                                           // 删除时间
	FAuditID                      int64  `gorm:"column:f_audit_id;not null" json:"f_audit_id"`                                             // 审核ID
	FAuditMsg                     string `gorm:"column:f_audit_msg;not null" json:"f_audit_msg"`                                           // 最后一次审核意见
	FCurrentVersion               bool   `gorm:"column:f_current_version;not null;default:1" json:"f_current_version"`                     // 是否现行版本 0 否 1 是
	FAlterUID                     string `gorm:"column:f_alter_uid;not null" json:"f_alter_uid"`                                           // 变更创建人ID
	FAlterName                    string `gorm:"column:f_alter_name;not null" json:"f_alter_name"`                                         // 变更创建人名称
	FAlterAt                      int64  `gorm:"column:f_alter_at;not null" json:"f_alter_at"`                                             // 变更创建时间
	FPreID                        int64  `gorm:"column:f_pre_id;not null" json:"f_pre_id"`                                                 // 前一版本ID
	FNextID                       int64  `gorm:"column:f_next_id;not null" json:"f_next_id"`                                               // 后一版本ID
	LabelIds                      string `gorm:"column:label_ids" json:"label_ids"`                                                        // 标签ID
	FAlterAuditMsg                string `gorm:"column:f_alter_audit_msg;not null" json:"f_alter_audit_msg"`                               // 最后一次变更审核意见
}

// TableName TInfoResourceCatalog's table name
func (*TInfoResourceCatalog) TableName() string {
	return TableNameTInfoResourceCatalog
}
