// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTInfoResourceCatalogCategoryNode = "t_info_resource_catalog_category_node"

// TInfoResourceCatalogCategoryNode mapped from table <t_info_resource_catalog_category_node>
type TInfoResourceCatalogCategoryNode struct {
	FID                    uint64 `gorm:"column:f_id;primaryKey;autoIncrement:true" json:"f_id"`                        // 自增主键
	FCategoryNodeID        string `gorm:"column:f_category_node_id;not null" json:"f_category_node_id"`                 // 类目节点ID
	FCategoryCateID        string `gorm:"column:f_category_cate_id;not null" json:"f_category_cate_id"`                 // 类目分类ID
	FInfoResourceCatalogID int64  `gorm:"column:f_info_resource_catalog_id;not null" json:"f_info_resource_catalog_id"` // 信息资源目录ID
}

// TableName TInfoResourceCatalogCategoryNode's table name
func (*TInfoResourceCatalogCategoryNode) TableName() string {
	return TableNameTInfoResourceCatalogCategoryNode
}
