// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTInfoResourceCatalogColumn = "t_info_resource_catalog_column"

// TInfoResourceCatalogColumn mapped from table <t_info_resource_catalog_column>
type TInfoResourceCatalogColumn struct {
	FID                    uint64 `gorm:"column:f_id" json:"f_id"`                                           // 主键ID
	FName                  string `gorm:"column:f_name;not null" json:"f_name"`                                         // 信息项名称
	FFieldNameEn           string `gorm:"column:f_field_name_en;not null" json:"f_field_name_en"`                       // 对应业务表字段英文名称
	FFieldNameCn           string `gorm:"column:f_field_name_cn;not null" json:"f_field_name_cn"`                       // 对应业务表字段中文名称
	FDataType              int32  `gorm:"column:f_data_type;not null" json:"f_data_type"`                               // 数据类型
	FDataLength            int64  `gorm:"column:f_data_length;not null" json:"f_data_length"`                           // 数据长度
	FDataRange             string `gorm:"column:f_data_range;not null" json:"f_data_range"`                             // 数据值域
	FIsSensitive           int32  `gorm:"column:f_is_sensitive;not null" json:"f_is_sensitive"`                         // 是否敏感属性：0-否；1-是
	FIsSecret              int32  `gorm:"column:f_is_secret;not null" json:"f_is_secret"`                               // 是否涉密属性：0-否；1-是
	FIsIncremental         int32  `gorm:"column:f_is_incremental;not null" json:"f_is_incremental"`                     // 是否增量属性：0-否；1-是
	FIsPrimaryKey          int32  `gorm:"column:f_is_primary_key;not null" json:"f_is_primary_key"`                     // 是否主键属性：0-否；1-是
	FIsLocalGenerated      int32  `gorm:"column:f_is_local_generated;not null" json:"f_is_local_generated"`             // 是否本部门产生：0-否；1-是
	FIsStandardized        int32  `gorm:"column:f_is_standardized;not null" json:"f_is_standardized"`                   // 是否标准化属性：0-否；1-是
	FInfoResourceCatalogID int64  `gorm:"column:f_info_resource_catalog_id;not null" json:"f_info_resource_catalog_id"` // 所属信息资源目录ID
	FOrder                 int32  `gorm:"column:f_order;not null" json:"f_order"`                                       // 排序索引
}

// TableName TInfoResourceCatalogColumn's table name
func (*TInfoResourceCatalogColumn) TableName() string {
	return TableNameTInfoResourceCatalogColumn
}
