// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTRuleConfig = "t_rule_config"

// TRuleConfig mapped from table <t_rule_config>
type TRuleConfig struct {
	ID                        string  `gorm:"column:id;primaryKey" json:"id"`                                        // id,uuid
	RuleName                  string  `gorm:"column:rule_name;not null" json:"rule_name"`                            // 规则名称
	UpdateTimelinessCondition string  `gorm:"column:update_timeliness_condition" json:"update_timeliness_condition"` // 更新及时率条件(≥,<)
	UpdateTimelinessValue     float64 `gorm:"column:update_timeliness_value" json:"update_timeliness_value"`         // 更新及时率值(%)
	QualityPassCondition      string  `gorm:"column:quality_pass_condition" json:"quality_pass_condition"`           // 质量合格率条件(≥,<)
	QualityPassValue          float64  `gorm:"column:quality_pass_value" json:"quality_pass_value"`                   // 质量合格率值(%)
	LogicalOperator           string  `gorm:"column:logical_operator" json:"logical_operator"`                       // 逻辑运算符(AND/OR)
}

// TableName TRuleConfig's table name
func (*TRuleConfig) TableName() string {
	return TableNameTRuleConfig
}
