// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTStandardizationInfo = "t_standardization_info"

// TStandardizationInfo mapped from table <t_standardization_info>
type TStandardizationInfo struct {
	ID                 uint64 `gorm:"column:id;primaryKey" json:"id"`                                   // 唯一id，雪花算法
	BusinessDomainID   string `gorm:"column:business_domain_id;not null" json:"business_domain_id"`     // 业务域id
	BusinessDomainName string `gorm:"column:business_domain_name;not null" json:"business_domain_name"` // 业务域名称
	StandardizedFields int32  `gorm:"column:standardized_fields;not null" json:"standardized_fields"`   // 已标准化字段数
	TotalFields        int32  `gorm:"column:total_fields;not null" json:"total_fields"`                 // 总字段数
}

func (m *TStandardizationInfo) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TStandardizationInfo's table name
func (*TStandardizationInfo) TableName() string {
	return TableNameTStandardizationInfo
}
