// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
	"time"
)

const TableNameTSystemOperationDetail = "t_system_operation_detail"

// TSystemOperationDetail mapped from table <t_system_operation_details>
type TSystemOperationDetail struct {
	ID                   string    `gorm:"column:id;primaryKey" json:"id"`                              // id,uuid
	CatalogID            uint64    `gorm:"column:catalog_id;not null" json:"catalog_id"`                // 数据资源目录id
	DepartmentID         string    `gorm:"column:department_id" json:"department_id"`                   // 部门id
	InfoSystemID         string    `gorm:"column:info_system_id" json:"info_system_id"`                 // 信息系统id
	FormViewID           string    `gorm:"column:form_view_id;not null" json:"form_view_id"`            // 视图id
	TechnicalName        string    `gorm:"column:technical_name;not null" json:"technical_name"`        // 技术名称
	BusinessName         string    `gorm:"column:business_name;not null" json:"business_name"`          // 业务名称
	AcceptanceTime       *time.Time `gorm:"column:acceptance_time" json:"acceptance_time"`               // 验收时间
	FirstAggregationTime *time.Time `gorm:"column:first_aggregation_time" json:"first_aggregation_time"` // 首次归集时间
	UpdateCycle          int32     `gorm:"column:update_cycle" json:"update_cycle"`                     // 更新频率 参考数据字典：GXZQ，1不定时 2实时 3每日 4每周 5每月 6每季度 7每半年 8每年 9其他
	FieldCount           int       `gorm:"column:field_count" json:"field_count"`                       // 字段数
	LatestDataCount      int       `gorm:"column:latest_data_count" json:"latest_data_count"`           // 最新数据量
	HasQualityIssue      int32     `gorm:"column:has_quality_issue" json:"has_quality_issue"`           // 是否存在质量问题
	IssueRemark          string    `gorm:"column:issue_remark" json:"issue_remark"`                     // 问题备注
	QualityCheck         int32     `gorm:"column:quality_check" json:"quality_check"`                   // 质量检测
	DataUpdate           int32     `gorm:"column:data_update" json:"data_update"`                       // 数据更新
	CreatedAt  			 time.Time `gorm:"column:created_at;not null" json:"created_at"`     			// 创建时间
	UpdatedAt  			 time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`     			// 更新时间
}

func (m *TSystemOperationDetail) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TSystemOperationDetail's table name
func (*TSystemOperationDetail) TableName() string {
	return TableNameTSystemOperationDetail
}
