// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID     string `gorm:"column:id" json:"id" format:"用户标识"`
	Name   string `gorm:"column:name" json:"name" example:"用户名称" format:"用户名称"`
	Status int32  `gorm:"column:status;not null;comment:用户状态,1正常,2删除" json:"status"` // 用户状态,1正常,2删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
