// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: register.proto

package register

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName                            = "/register.UserService/CreateUser"
	UserService_ListUser_FullMethodName                              = "/register.UserService/ListUser"
	UserService_QueryUser_FullMethodName                             = "/register.UserService/QueryUser"
	UserService_CreateOrganization_FullMethodName                    = "/register.UserService/CreateOrganization"
	UserService_UpdateOraganization_FullMethodName                   = "/register.UserService/UpdateOraganization"
	UserService_ListOraganization_FullMethodName                     = "/register.UserService/ListOraganization"
	UserService_OrganaizaitionCodeExist_FullMethodName               = "/register.UserService/OrganaizaitionCodeExist"
	UserService_AppCreate_FullMethodName                             = "/register.UserService/AppCreate"
	UserService_AppUpdate_FullMethodName                             = "/register.UserService/AppUpdate"
	UserService_AppSelect_FullMethodName                             = "/register.UserService/AppSelect"
	UserService_AppSelectOnly_FullMethodName                         = "/register.UserService/AppSelectOnly"
	UserService_SystemCreate_FullMethodName                          = "/register.UserService/SystemCreate"
	UserService_SystemUpdate_FullMethodName                          = "/register.UserService/SystemUpdate"
	UserService_SystemStatusUpdate_FullMethodName                    = "/register.UserService/SystemStatusUpdate"
	UserService_SystemSelect_FullMethodName                          = "/register.UserService/SystemSelect"
	UserService_SystemSelectOnly_FullMethodName                      = "/register.UserService/SystemSelectOnly"
	UserService_Create_FullMethodName                                = "/register.UserService/Create"
	UserService_Update_FullMethodName                                = "/register.UserService/Update"
	UserService_StatusUpdate_FullMethodName                          = "/register.UserService/StatusUpdate"
	UserService_SubscriptionCreate_FullMethodName                    = "/register.UserService/SubscriptionCreate"
	UserService_BatchSubscriptionCreate_FullMethodName               = "/register.UserService/BatchSubscriptionCreate"
	UserService_SubscriptionUpdate_FullMethodName                    = "/register.UserService/SubscriptionUpdate"
	UserService_SubscriptionInvokeLimitIntervalUpdate_FullMethodName = "/register.UserService/SubscriptionInvokeLimitIntervalUpdate"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// 注册用户
	CreateUser(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResponse, error)
	// 用户列表查询
	ListUser(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResponse, error)
	// 用户选择列表
	QueryUser(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResponse, error)
	//机构注册
	CreateOrganization(ctx context.Context, in *CreateOrganizationReq, opts ...grpc.CallOption) (*CreateOrganizationResponse, error)
	// 机构编辑
	UpdateOraganization(ctx context.Context, in *UpdateOrganizationReq, opts ...grpc.CallOption) (*UpdateOrganizationResponse, error)
	// 机构列表查询
	ListOraganization(ctx context.Context, in *ListOrganizationReq, opts ...grpc.CallOption) (*ListOrganizationResponse, error)
	// 机构code是否存在
	OrganaizaitionCodeExist(ctx context.Context, in *OrganizationExitReq, opts ...grpc.CallOption) (*OrganizationExitResponse, error)
	// 应用创建接口
	AppCreate(ctx context.Context, in *AppCreateRequest, opts ...grpc.CallOption) (*CommonResult, error)
	// 应用修改接口
	AppUpdate(ctx context.Context, in *AppUpdateRequest, opts ...grpc.CallOption) (*CommonResult, error)
	// 应用查询接口
	AppSelect(ctx context.Context, in *AppSelectRequest, opts ...grpc.CallOption) (*AppSelectResult, error)
	// 应用唯一性查询接口
	AppSelectOnly(ctx context.Context, in *AppSelectOnlyRequest, opts ...grpc.CallOption) (*AppSelectOnlyResult, error)
	// 系统创建接口
	SystemCreate(ctx context.Context, in *SystemCreateRequest, opts ...grpc.CallOption) (*CommonResult, error)
	// 系统修改接口
	SystemUpdate(ctx context.Context, in *SystemUpdateRequest, opts ...grpc.CallOption) (*CommonResult, error)
	// 系统发布接口（发布）
	SystemStatusUpdate(ctx context.Context, in *SystemStatusUpdateRequest, opts ...grpc.CallOption) (*CommonResult, error)
	// 系统查询接口
	SystemSelect(ctx context.Context, in *SystemSelectRequest, opts ...grpc.CallOption) (*SystemSelectResult, error)
	// 系统唯一性查询接口
	SystemSelectOnly(ctx context.Context, in *SystemSelectOnlyRequest, opts ...grpc.CallOption) (*SystemSelectOnlyResult, error)
	// 服务创建接口
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Result, error)
	// 服务修改接口
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Result, error)
	// 服务状态修改接口（上线&下线）
	StatusUpdate(ctx context.Context, in *StatusUpdateRequest, opts ...grpc.CallOption) (*Result, error)
	// 服务订阅接口
	SubscriptionCreate(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*SubscriptionCreateResult, error)
	// 新增批量服务订阅接口
	BatchSubscriptionCreate(ctx context.Context, in *BatchSubscriptionCreateRequest, opts ...grpc.CallOption) (*BatchSubscriptionCreateResult, error)
	// 服务订阅状态修改接口
	SubscriptionUpdate(ctx context.Context, in *SubscriptionStatusUpdateRequest, opts ...grpc.CallOption) (*SubscriptionStatusUpdateResult, error)
	// 服务订阅调用频率修改接口
	SubscriptionInvokeLimitIntervalUpdate(ctx context.Context, in *SubscriptionInvokeLimitIntervalUpdateRequest, opts ...grpc.CallOption) (*SubscriptionStatusUpdateResult, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, UserService_ListUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QueryUser(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, UserService_QueryUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateOrganization(ctx context.Context, in *CreateOrganizationReq, opts ...grpc.CallOption) (*CreateOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrganizationResponse)
	err := c.cc.Invoke(ctx, UserService_CreateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateOraganization(ctx context.Context, in *UpdateOrganizationReq, opts ...grpc.CallOption) (*UpdateOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrganizationResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateOraganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListOraganization(ctx context.Context, in *ListOrganizationReq, opts ...grpc.CallOption) (*ListOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrganizationResponse)
	err := c.cc.Invoke(ctx, UserService_ListOraganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) OrganaizaitionCodeExist(ctx context.Context, in *OrganizationExitReq, opts ...grpc.CallOption) (*OrganizationExitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationExitResponse)
	err := c.cc.Invoke(ctx, UserService_OrganaizaitionCodeExist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AppCreate(ctx context.Context, in *AppCreateRequest, opts ...grpc.CallOption) (*CommonResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResult)
	err := c.cc.Invoke(ctx, UserService_AppCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AppUpdate(ctx context.Context, in *AppUpdateRequest, opts ...grpc.CallOption) (*CommonResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResult)
	err := c.cc.Invoke(ctx, UserService_AppUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AppSelect(ctx context.Context, in *AppSelectRequest, opts ...grpc.CallOption) (*AppSelectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSelectResult)
	err := c.cc.Invoke(ctx, UserService_AppSelect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AppSelectOnly(ctx context.Context, in *AppSelectOnlyRequest, opts ...grpc.CallOption) (*AppSelectOnlyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSelectOnlyResult)
	err := c.cc.Invoke(ctx, UserService_AppSelectOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SystemCreate(ctx context.Context, in *SystemCreateRequest, opts ...grpc.CallOption) (*CommonResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResult)
	err := c.cc.Invoke(ctx, UserService_SystemCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SystemUpdate(ctx context.Context, in *SystemUpdateRequest, opts ...grpc.CallOption) (*CommonResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResult)
	err := c.cc.Invoke(ctx, UserService_SystemUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SystemStatusUpdate(ctx context.Context, in *SystemStatusUpdateRequest, opts ...grpc.CallOption) (*CommonResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResult)
	err := c.cc.Invoke(ctx, UserService_SystemStatusUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SystemSelect(ctx context.Context, in *SystemSelectRequest, opts ...grpc.CallOption) (*SystemSelectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemSelectResult)
	err := c.cc.Invoke(ctx, UserService_SystemSelect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SystemSelectOnly(ctx context.Context, in *SystemSelectOnlyRequest, opts ...grpc.CallOption) (*SystemSelectOnlyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemSelectOnlyResult)
	err := c.cc.Invoke(ctx, UserService_SystemSelectOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, UserService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, UserService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) StatusUpdate(ctx context.Context, in *StatusUpdateRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, UserService_StatusUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SubscriptionCreate(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*SubscriptionCreateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionCreateResult)
	err := c.cc.Invoke(ctx, UserService_SubscriptionCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) BatchSubscriptionCreate(ctx context.Context, in *BatchSubscriptionCreateRequest, opts ...grpc.CallOption) (*BatchSubscriptionCreateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSubscriptionCreateResult)
	err := c.cc.Invoke(ctx, UserService_BatchSubscriptionCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SubscriptionUpdate(ctx context.Context, in *SubscriptionStatusUpdateRequest, opts ...grpc.CallOption) (*SubscriptionStatusUpdateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionStatusUpdateResult)
	err := c.cc.Invoke(ctx, UserService_SubscriptionUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SubscriptionInvokeLimitIntervalUpdate(ctx context.Context, in *SubscriptionInvokeLimitIntervalUpdateRequest, opts ...grpc.CallOption) (*SubscriptionStatusUpdateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionStatusUpdateResult)
	err := c.cc.Invoke(ctx, UserService_SubscriptionInvokeLimitIntervalUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	// 注册用户
	CreateUser(context.Context, *CreateReq) (*CreateResponse, error)
	// 用户列表查询
	ListUser(context.Context, *ListReq) (*ListResponse, error)
	// 用户选择列表
	QueryUser(context.Context, *QueryReq) (*QueryResponse, error)
	//机构注册
	CreateOrganization(context.Context, *CreateOrganizationReq) (*CreateOrganizationResponse, error)
	// 机构编辑
	UpdateOraganization(context.Context, *UpdateOrganizationReq) (*UpdateOrganizationResponse, error)
	// 机构列表查询
	ListOraganization(context.Context, *ListOrganizationReq) (*ListOrganizationResponse, error)
	// 机构code是否存在
	OrganaizaitionCodeExist(context.Context, *OrganizationExitReq) (*OrganizationExitResponse, error)
	// 应用创建接口
	AppCreate(context.Context, *AppCreateRequest) (*CommonResult, error)
	// 应用修改接口
	AppUpdate(context.Context, *AppUpdateRequest) (*CommonResult, error)
	// 应用查询接口
	AppSelect(context.Context, *AppSelectRequest) (*AppSelectResult, error)
	// 应用唯一性查询接口
	AppSelectOnly(context.Context, *AppSelectOnlyRequest) (*AppSelectOnlyResult, error)
	// 系统创建接口
	SystemCreate(context.Context, *SystemCreateRequest) (*CommonResult, error)
	// 系统修改接口
	SystemUpdate(context.Context, *SystemUpdateRequest) (*CommonResult, error)
	// 系统发布接口（发布）
	SystemStatusUpdate(context.Context, *SystemStatusUpdateRequest) (*CommonResult, error)
	// 系统查询接口
	SystemSelect(context.Context, *SystemSelectRequest) (*SystemSelectResult, error)
	// 系统唯一性查询接口
	SystemSelectOnly(context.Context, *SystemSelectOnlyRequest) (*SystemSelectOnlyResult, error)
	// 服务创建接口
	Create(context.Context, *CreateRequest) (*Result, error)
	// 服务修改接口
	Update(context.Context, *UpdateRequest) (*Result, error)
	// 服务状态修改接口（上线&下线）
	StatusUpdate(context.Context, *StatusUpdateRequest) (*Result, error)
	// 服务订阅接口
	SubscriptionCreate(context.Context, *SubscriptionCreateRequest) (*SubscriptionCreateResult, error)
	// 新增批量服务订阅接口
	BatchSubscriptionCreate(context.Context, *BatchSubscriptionCreateRequest) (*BatchSubscriptionCreateResult, error)
	// 服务订阅状态修改接口
	SubscriptionUpdate(context.Context, *SubscriptionStatusUpdateRequest) (*SubscriptionStatusUpdateResult, error)
	// 服务订阅调用频率修改接口
	SubscriptionInvokeLimitIntervalUpdate(context.Context, *SubscriptionInvokeLimitIntervalUpdateRequest) (*SubscriptionStatusUpdateResult, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateReq) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) ListUser(context.Context, *ListReq) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedUserServiceServer) QueryUser(context.Context, *QueryReq) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUser not implemented")
}
func (UnimplementedUserServiceServer) CreateOrganization(context.Context, *CreateOrganizationReq) (*CreateOrganizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrganization not implemented")
}
func (UnimplementedUserServiceServer) UpdateOraganization(context.Context, *UpdateOrganizationReq) (*UpdateOrganizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOraganization not implemented")
}
func (UnimplementedUserServiceServer) ListOraganization(context.Context, *ListOrganizationReq) (*ListOrganizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOraganization not implemented")
}
func (UnimplementedUserServiceServer) OrganaizaitionCodeExist(context.Context, *OrganizationExitReq) (*OrganizationExitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrganaizaitionCodeExist not implemented")
}
func (UnimplementedUserServiceServer) AppCreate(context.Context, *AppCreateRequest) (*CommonResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppCreate not implemented")
}
func (UnimplementedUserServiceServer) AppUpdate(context.Context, *AppUpdateRequest) (*CommonResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppUpdate not implemented")
}
func (UnimplementedUserServiceServer) AppSelect(context.Context, *AppSelectRequest) (*AppSelectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppSelect not implemented")
}
func (UnimplementedUserServiceServer) AppSelectOnly(context.Context, *AppSelectOnlyRequest) (*AppSelectOnlyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppSelectOnly not implemented")
}
func (UnimplementedUserServiceServer) SystemCreate(context.Context, *SystemCreateRequest) (*CommonResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemCreate not implemented")
}
func (UnimplementedUserServiceServer) SystemUpdate(context.Context, *SystemUpdateRequest) (*CommonResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemUpdate not implemented")
}
func (UnimplementedUserServiceServer) SystemStatusUpdate(context.Context, *SystemStatusUpdateRequest) (*CommonResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemStatusUpdate not implemented")
}
func (UnimplementedUserServiceServer) SystemSelect(context.Context, *SystemSelectRequest) (*SystemSelectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemSelect not implemented")
}
func (UnimplementedUserServiceServer) SystemSelectOnly(context.Context, *SystemSelectOnlyRequest) (*SystemSelectOnlyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemSelectOnly not implemented")
}
func (UnimplementedUserServiceServer) Create(context.Context, *CreateRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserServiceServer) Update(context.Context, *UpdateRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserServiceServer) StatusUpdate(context.Context, *StatusUpdateRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusUpdate not implemented")
}
func (UnimplementedUserServiceServer) SubscriptionCreate(context.Context, *SubscriptionCreateRequest) (*SubscriptionCreateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionCreate not implemented")
}
func (UnimplementedUserServiceServer) BatchSubscriptionCreate(context.Context, *BatchSubscriptionCreateRequest) (*BatchSubscriptionCreateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSubscriptionCreate not implemented")
}
func (UnimplementedUserServiceServer) SubscriptionUpdate(context.Context, *SubscriptionStatusUpdateRequest) (*SubscriptionStatusUpdateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionUpdate not implemented")
}
func (UnimplementedUserServiceServer) SubscriptionInvokeLimitIntervalUpdate(context.Context, *SubscriptionInvokeLimitIntervalUpdateRequest) (*SubscriptionStatusUpdateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionInvokeLimitIntervalUpdate not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QueryUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryUser(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateOrganization(ctx, req.(*CreateOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateOraganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateOraganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateOraganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateOraganization(ctx, req.(*UpdateOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListOraganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListOraganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListOraganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListOraganization(ctx, req.(*ListOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_OrganaizaitionCodeExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationExitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).OrganaizaitionCodeExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_OrganaizaitionCodeExist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).OrganaizaitionCodeExist(ctx, req.(*OrganizationExitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AppCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AppCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AppCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AppCreate(ctx, req.(*AppCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AppUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AppUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AppUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AppUpdate(ctx, req.(*AppUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AppSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AppSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AppSelect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AppSelect(ctx, req.(*AppSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AppSelectOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppSelectOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AppSelectOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AppSelectOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AppSelectOnly(ctx, req.(*AppSelectOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SystemCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SystemCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SystemCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SystemCreate(ctx, req.(*SystemCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SystemUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SystemUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SystemUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SystemUpdate(ctx, req.(*SystemUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SystemStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatusUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SystemStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SystemStatusUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SystemStatusUpdate(ctx, req.(*SystemStatusUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SystemSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SystemSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SystemSelect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SystemSelect(ctx, req.(*SystemSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SystemSelectOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemSelectOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SystemSelectOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SystemSelectOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SystemSelectOnly(ctx, req.(*SystemSelectOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_StatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).StatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_StatusUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).StatusUpdate(ctx, req.(*StatusUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SubscriptionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SubscriptionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SubscriptionCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SubscriptionCreate(ctx, req.(*SubscriptionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_BatchSubscriptionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSubscriptionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).BatchSubscriptionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_BatchSubscriptionCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).BatchSubscriptionCreate(ctx, req.(*BatchSubscriptionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SubscriptionUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionStatusUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SubscriptionUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SubscriptionUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SubscriptionUpdate(ctx, req.(*SubscriptionStatusUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SubscriptionInvokeLimitIntervalUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionInvokeLimitIntervalUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SubscriptionInvokeLimitIntervalUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SubscriptionInvokeLimitIntervalUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SubscriptionInvokeLimitIntervalUpdate(ctx, req.(*SubscriptionInvokeLimitIntervalUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "register.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
		{
			MethodName: "QueryUser",
			Handler:    _UserService_QueryUser_Handler,
		},
		{
			MethodName: "CreateOrganization",
			Handler:    _UserService_CreateOrganization_Handler,
		},
		{
			MethodName: "UpdateOraganization",
			Handler:    _UserService_UpdateOraganization_Handler,
		},
		{
			MethodName: "ListOraganization",
			Handler:    _UserService_ListOraganization_Handler,
		},
		{
			MethodName: "OrganaizaitionCodeExist",
			Handler:    _UserService_OrganaizaitionCodeExist_Handler,
		},
		{
			MethodName: "AppCreate",
			Handler:    _UserService_AppCreate_Handler,
		},
		{
			MethodName: "AppUpdate",
			Handler:    _UserService_AppUpdate_Handler,
		},
		{
			MethodName: "AppSelect",
			Handler:    _UserService_AppSelect_Handler,
		},
		{
			MethodName: "AppSelectOnly",
			Handler:    _UserService_AppSelectOnly_Handler,
		},
		{
			MethodName: "SystemCreate",
			Handler:    _UserService_SystemCreate_Handler,
		},
		{
			MethodName: "SystemUpdate",
			Handler:    _UserService_SystemUpdate_Handler,
		},
		{
			MethodName: "SystemStatusUpdate",
			Handler:    _UserService_SystemStatusUpdate_Handler,
		},
		{
			MethodName: "SystemSelect",
			Handler:    _UserService_SystemSelect_Handler,
		},
		{
			MethodName: "SystemSelectOnly",
			Handler:    _UserService_SystemSelectOnly_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "StatusUpdate",
			Handler:    _UserService_StatusUpdate_Handler,
		},
		{
			MethodName: "SubscriptionCreate",
			Handler:    _UserService_SubscriptionCreate_Handler,
		},
		{
			MethodName: "BatchSubscriptionCreate",
			Handler:    _UserService_BatchSubscriptionCreate_Handler,
		},
		{
			MethodName: "SubscriptionUpdate",
			Handler:    _UserService_SubscriptionUpdate_Handler,
		},
		{
			MethodName: "SubscriptionInvokeLimitIntervalUpdate",
			Handler:    _UserService_SubscriptionInvokeLimitIntervalUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register.proto",
}
