// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		Datasource:          newDatasource(db, opts...),
		Flowchart:           newFlowchart(db, opts...),
		FlowchartNodeConfig: newFlowchartNodeConfig(db, opts...),
		FlowchartNodeTask:   newFlowchartNodeTask(db, opts...),
		FlowchartUnit:       newFlowchartUnit(db, opts...),
		FlowchartVersion:    newFlowchartVersion(db, opts...),
		InfoSystem:          newInfoSystem(db, opts...),
		MqMessage:           newMqMessage(db, opts...),
		Object:              newObject(db, opts...),
		Resource:            newResource(db, opts...),
		SystemRole:          newSystemRole(db, opts...),
		User:                newUser(db, opts...),
		UserRole:            newUserRole(db, opts...),
		Configuration:       newConfiguration(db, opts...),
		TDictItem: newTDictItem(db, opts...),
		TDict: newTDict(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Datasource          datasource
	Flowchart           flowchart
	FlowchartNodeConfig flowchartNodeConfig
	FlowchartNodeTask   flowchartNodeTask
	FlowchartUnit       flowchartUnit
	FlowchartVersion    flowchartVersion
	InfoSystem          infoSystem
	MqMessage           mqMessage
	Object              object
	Resource            resource
	SystemRole          systemRole
	User                user
	UserRole            userRole
	Configuration       configuration
	TDictItem tDictItem
	TDict tDict
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Datasource:          q.Datasource.clone(db),
		Flowchart:           q.Flowchart.clone(db),
		FlowchartNodeConfig: q.FlowchartNodeConfig.clone(db),
		FlowchartNodeTask:   q.FlowchartNodeTask.clone(db),
		FlowchartUnit:       q.FlowchartUnit.clone(db),
		FlowchartVersion:    q.FlowchartVersion.clone(db),
		InfoSystem:          q.InfoSystem.clone(db),
		MqMessage:           q.MqMessage.clone(db),
		Object:              q.Object.clone(db),
		Resource:            q.Resource.clone(db),
		SystemRole:          q.SystemRole.clone(db),
		User:                q.User.clone(db),
		UserRole:            q.UserRole.clone(db),
		Configuration:       q.Configuration.clone(db),
		TDictItem: q.TDictItem.clone(db),
		TDict: q.TDict.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Datasource:          q.Datasource.replaceDB(db),
		Flowchart:           q.Flowchart.replaceDB(db),
		FlowchartNodeConfig: q.FlowchartNodeConfig.replaceDB(db),
		FlowchartNodeTask:   q.FlowchartNodeTask.replaceDB(db),
		FlowchartUnit:       q.FlowchartUnit.replaceDB(db),
		FlowchartVersion:    q.FlowchartVersion.replaceDB(db),
		InfoSystem:          q.InfoSystem.replaceDB(db),
		Object:              q.Object.replaceDB(db),
		MqMessage:           q.MqMessage.replaceDB(db),
		Resource:            q.Resource.replaceDB(db),
		SystemRole:          q.SystemRole.replaceDB(db),
		User:                q.User.replaceDB(db),
		UserRole:            q.UserRole.replaceDB(db),
		Configuration:       q.Configuration.replaceDB(db),
		TDictItem: q.TDictItem.replaceDB(db),
		TDict: q.TDict.replaceDB(db),
	}
}

type queryCtx struct {
	Datasource          IDatasourceDo
	Flowchart           IFlowchartDo
	FlowchartNodeConfig IFlowchartNodeConfigDo
	FlowchartNodeTask   IFlowchartNodeTaskDo
	FlowchartUnit       IFlowchartUnitDo
	FlowchartVersion    IFlowchartVersionDo
	InfoSystem          IInfoSystemDo
	MqMessage           IMqMessageDo
	Object              IObjectDo
	Resource            IResourceDo
	SystemRole          ISystemRoleDo
	User                IUserDo
	UserRole            IUserRoleDo
	Configuration       IConfigurationDo
	TDictItem ITDictItemDo
	TDict ITDictDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Datasource:          q.Datasource.WithContext(ctx),
		Flowchart:           q.Flowchart.WithContext(ctx),
		FlowchartNodeConfig: q.FlowchartNodeConfig.WithContext(ctx),
		FlowchartNodeTask:   q.FlowchartNodeTask.WithContext(ctx),
		FlowchartUnit:       q.FlowchartUnit.WithContext(ctx),
		FlowchartVersion:    q.FlowchartVersion.WithContext(ctx),
		InfoSystem:          q.InfoSystem.WithContext(ctx),
		MqMessage:           q.MqMessage.WithContext(ctx),
		Object:              q.Object.WithContext(ctx),
		Resource:            q.Resource.WithContext(ctx),
		SystemRole:          q.SystemRole.WithContext(ctx),
		User:                q.User.WithContext(ctx),
		UserRole:            q.UserRole.WithContext(ctx),
		Configuration:       q.Configuration.WithContext(ctx),
		TDictItem: q.TDictItem.WithContext(ctx),
		TDict: q.TDict.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
