// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Resource{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Resource{}) fail: %s", err)
	}
}

func Test_resourceQuery(t *testing.T) {
	resource := newResource(db)
	resource = *resource.As(resource.TableName())
	_do := resource.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(resource.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <resource> fail:", err)
		return
	}

	_, ok := resource.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from resource success")
	}

	err = _do.Create(&model.Resource{})
	if err != nil {
		t.Error("create item in table <resource> fail:", err)
	}

	err = _do.Save(&model.Resource{})
	if err != nil {
		t.Error("create item in table <resource> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Resource{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <resource> fail:", err)
	}

	_, err = _do.Select(resource.ALL).Take()
	if err != nil {
		t.Error("Take() on table <resource> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <resource> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <resource> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <resource> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Resource{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <resource> fail:", err)
	}

	_, err = _do.Select(resource.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <resource> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <resource> fail:", err)
	}

	_, err = _do.Select(resource.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <resource> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <resource> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <resource> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <resource> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Resource{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <resource> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <resource> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <resource> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <resource> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <resource> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <resource> fail:", err)
	}
}
