// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameStandardInfo = "standard_info"

// StandardInfo mapped from table <standard_info>
type StandardInfo struct {
	ID             uint64        `gorm:"column:id" json:"id"`                         // 标准ID
	Name           string        `gorm:"column:name;not null" json:"name"`                       // 字段名
	NameEn         string        `gorm:"column:name_en;not null" json:"name_en"`                 // 字段英文名
	DataType       string        `gorm:"column:data_type;not null" json:"data_type"`             // 数据类型
	DataLength     sql.NullInt32 `gorm:"column:data_length" json:"data_length"`                  // 数据长度
	DataAccuracy   sql.NullInt32 `gorm:"column:data_accuracy" json:"data_accuracy"`              // 数据精度
	ValueRange     string        `gorm:"column:value_range;not null" json:"value_range"`         // 值域
	FormulateBasis int32         `gorm:"column:formulate_basis;not null" json:"formulate_basis"` // 制定依据
	CodeTable      string        `gorm:"column:code_table;not null" json:"code_table"`           // 码表
}

func (i *StandardInfo) UniqueKey() string {
	return "id"
}

// TableName StandardInfo's table name
func (*StandardInfo) TableName() string {
	return TableNameStandardInfo
}
