// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameDataQualityImprovement = "data_quality_improvement"

// DataQualityImprovement mapped from table <data_quality_improvement>
type DataQualityImprovement struct {
	ID            string `gorm:"column:id" json:"id"`                     // 整改项id
	WorkOrderID   string `gorm:"column:work_order_id;not null" json:"work_order_id"` // 工单id
	FieldID       string `gorm:"column:field_id;not null" json:"field_id"`           // 字段id
	RuleID        string `gorm:"column:rule_id;not null" json:"rule_id"`             // 规则id
	RuleName      string `gorm:"column:rule_name;not null" json:"rule_name"`         // 规则名称
	Dimension     string `gorm:"column:dimension;not null" json:"dimension"`		 // 规则维度
	InspectedCount int64 `gorm:"column:inspected_count;not null" json:"inspected_count"` // 检测数据量
	IssueCount     int64 `gorm:"column:issue_count;not null" json:"issue_count"`     // 问题数据量
	Score		  float64 `gorm:"column:score;not null" json:"score"`                 // 评分
	DeletedAt     soft_delete.DeletedAt  `gorm:"column:deleted_at;not null" json:"deleted_at"`       // 删除时间
}

func (d *DataQualityImprovement) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}

	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	return nil
}

// TableName DataQualityImprovement's table name
func (*DataQualityImprovement) TableName() string {
	return TableNameDataQualityImprovement
}
