// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameDbSandboxLog = "db_sandbox_log"

// DbSandboxLog mapped from table <db_sandbox_log>
type DBSandboxLog struct {
	Sid          uint64    `gorm:"column:sid;not null" json:"sid"`                                                // 主键雪花ID
	ID           string    `gorm:"column:id" json:"id"`                                                           // 主键，uuid
	ApplyID      string    `gorm:"column:apply_id;not null" json:"apply_id"`                                      // 沙箱实施ID
	ExecuteStep  int32     `gorm:"column:execute_step;not null" json:"execute_step"`                              // 操作步骤,1申请，2扩容，3审核，4实施，5完成
	ExecutorID   string    `gorm:"column:executor_id" json:"executor_id"`                                         // 实施人ID
	ExecutorName string    `gorm:"column:executor_name" json:"executor_name"`                                     // 实施人名称
	ExecuteTime  time.Time `gorm:"column:execute_time;not null;default:current_timestamp(3)" json:"execute_time"` // 操作时间
}

func (m *DBSandboxLog) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}
	if m.Sid == 0 {
		m.Sid, _ = utilities.GetUniqueID()
	}
	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName DbSandboxLog's table name
func (*DBSandboxLog) TableName() string {
	return TableNameDbSandboxLog
}
