// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameDbSandboxExecution = "db_sandbox_execution"

// DBSandboxExecution mapped from table <db_sandbox_execution>
type DBSandboxExecution struct {
	Sid           uint64     `gorm:"column:sid;not null" json:"sid"`                                            // 主键雪花ID
	ID            string     `gorm:"column:id" json:"id"`                                                       // 主键，uuid
	SandboxID     string     `gorm:"column:sandbox_id;not null" json:"sandbox_id"`                              // 沙箱ID
	ApplyID       string     `gorm:"column:apply_id;not null" json:"apply_id"`                                  // 申请ID
	Description   string     `gorm:"column:description;not null" json:"description"`                            // 实施说明
	ExecuteType   int32      `gorm:"column:execute_type;not null" json:"execute_type"`                          // 实施方式,1线下，2线上
	ExecuteStatus int32      `gorm:"column:execute_status;not null" json:"execute_status"`                      // 实施阶段,1待实施，2实施中，3已实施
	ExecutorID    string     `gorm:"column:executor_id" json:"executor_id"`                                     // 实施人ID
	ExecutorName  string     `gorm:"column:executor_name" json:"executor_name"`                                 // 实施人名称
	ExecutedTime  *time.Time `gorm:"column:executed_time;default null" json:"executed_time"`                    // 实施完成时间
	CreatedAt     time.Time  `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	CreatorUID    string     `gorm:"column:creator_uid" json:"creator_uid"`                                     // 创建用户ID
	UpdatedAt     time.Time  `gorm:"column:updated_at;autoUpdateTime;not null" json:"updated_at"`               // 更新时间
	UpdaterUID    string     `gorm:"column:updater_uid" json:"updater_uid"`                                     // 更新用户ID
	DeletedAt     int64      `gorm:"column:deleted_at" json:"deleted_at"`                                       // 删除时间(逻辑删除)
	SandboxSecurityInfo
}

type SandboxSecurityInfo struct {
	DatasourceID       string `gorm:"-" json:"-"` // 数据源ID
	DatasourceName     string `gorm:"-" json:"-"` // 数据源名称
	DatasourceTypeName string `gorm:"-" json:"-"` // 数据库类型名称
	DatabaseName       string `gorm:"-" json:"-"` // 数据库名称
	Username           string `gorm:"-" json:"-"` // 用户名
	Password           string `gorm:"-" json:"-"` // 密码
}

func (m *DBSandboxExecution) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}
	if m.Sid == 0 {
		m.Sid, _ = utilities.GetUniqueID()
	}
	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName DbSandboxExecution's table name
func (*DBSandboxExecution) TableName() string {
	return TableNameDbSandboxExecution
}

func (d *DBSandboxExecution) GenLog(step int32) *DBSandboxLog {
	return &DBSandboxLog{
		ApplyID:      d.ApplyID,
		ExecuteStep:  step,
		ExecutorID:   d.ExecutorID,
		ExecutorName: d.ExecutorName,
	}
}
