// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameDbSandbox = "db_sandbox"

// DBSandbox mapped from table <db_sandbox>
type DBSandbox struct {
	Sid            uint64     `gorm:"column:sid;not null" json:"sid"`                         // 主键雪花ID
	ID             string     `gorm:"column:id" json:"id"`                                    // 主键雪UUID
	DepartmentID   string     `gorm:"column:department_id;not null" json:"department_id"`     // 所属部门ID
	DepartmentName string     `gorm:"column:department_name;not null" json:"department_name"` // 所属部门名称
	ProjectID      string     `gorm:"column:project_id;not null" json:"project_id"`           // 项目ID
	Status         int32      `gorm:"column:status;not null" json:"status"`                   // 状态，0不可用，1可用
	TotalSpace     int32      `gorm:"column:total_space" json:"total_space"`                  // 总的沙箱空间，单位GB
	ValidStart     int64      `gorm:"column:valid_start" json:"valid_start"`                  // 有效期开始时间，单位毫秒
	ValidEnd       int64      `gorm:"column:valid_end" json:"valid_end"`                      // 有效期结束时间，单位毫秒
	ApplicantID    string     `gorm:"column:applicant_id;not null" json:"applicant_id"`       // 申请人ID
	ApplicantName  string     `gorm:"column:applicant_name;not null" json:"applicant_name"`   // 申请人名称
	ApplicantPhone string     `gorm:"column:applicant_phone;not null" json:"applicant_phone"` // 申请人手机号
	ExecutedTime   *time.Time `gorm:"column:executed_time;default null" json:"executed_time"` // 沙箱第一次申请实施时间
	//沙箱空间信息
	DatasourceID       string `gorm:"column:datasource_id;not null" json:"datasource_id"`               // 数据源UUID
	DatasourceName     string `gorm:"column:datasource_name;not null" json:"datasource_name"`           // 数据源名称,catalog
	DatasourceTypeName string `gorm:"column:datasource_type_name;not null" json:"datasource_type_name"` // 数据库类型名称
	DatabaseName       string `gorm:"column:database_name;not null" json:"database_name"`               // 数据库名称
	Username           string `gorm:"column:username;not null" json:"username"`                         // 用户名
	Password           string `gorm:"column:password;not null" json:"password"`                         // 密码
	RecentDataSet      string `gorm:"column:recent_data_set" json:"recent_data_set"`                    // 最近的数据集信息
	//基础字段
	UpdatedAt  time.Time `gorm:"column:updated_at;autoUpdateTime;not null" json:"updated_at"` // 更新时间
	UpdaterUID string    `gorm:"column:updater_uid" json:"updater_uid"`                       // 更新用户ID
	DeletedAt  int64     `gorm:"column:deleted_at" json:"deleted_at"`                         // 删除时间(逻辑删除)
}

func (m *DBSandbox) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}
	if m.Sid == 0 {
		m.Sid, _ = utilities.GetUniqueID()
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName DBSandbox's table name
func (*DBSandbox) TableName() string {
	return TableNameDbSandbox
}
