// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameDbSandboxApply = "db_sandbox_apply"

// DBSandboxApply mapped from table <db_sandbox_apply>
type DBSandboxApply struct {
	Sid            uint64    `gorm:"column:sid;not null" json:"sid"`                                            // 主键雪花ID
	ID             string    `gorm:"column:id" json:"id"`                                                       // 主键，uuid
	SandboxID      string    `gorm:"column:sandbox_id;not null" json:"sandbox_id"`                              // 沙箱ID
	ApplicantID    string    `gorm:"column:applicant_id" json:"applicant_id"`                                   // 申请人ID
	ApplicantName  string    `gorm:"column:applicant_name" json:"applicant_name"`                               // 申请人名称
	ApplicantPhone string    `gorm:"column:applicant_phone;not null" json:"applicant_phone"`                    // 申请人手机号
	RequestSpace   int32     `gorm:"column:request_space" json:"request_space"`                                 // 申请容量，单位GB
	Status         int32     `gorm:"column:status;not null" json:"status"`                                      // 状态,1申请中，2待实施，3实施中，4已完成
	Operation      int32     `gorm:"column:operation;not null" json:"operation"`                                // 操作,1创建申请，2扩容申请
	AuditState     int32     `gorm:"column:audit_state;not null" json:"audit_state"`                            // 审核状态,1审核中，2审核通过，3未通过
	AuditID        string    `gorm:"column:audit_id" json:"audit_id"`                                           // 审核流程ID
	AuditAdvice    string    `gorm:"column:audit_advice" json:"audit_advice"`                                   // 审核意见，仅驳回时有用
	ProcDefKey     string    `gorm:"column:proc_def_key;not null" json:"proc_def_key"`                          // 审核流程key
	Result         int32     `gorm:"column:result;not null" json:"result"`                                      // 申请结果,1通过，2拒绝，3撤回
	Reason         string    `gorm:"column:reason" json:"reason"`                                               // 申请原因
	ApplyTime      time.Time `gorm:"column:apply_time;not null;default:current_timestamp(3)" json:"apply_time"` // 操作时间
	UpdatedAt      time.Time `gorm:"column:updated_at;autoUpdateTime;not null" json:"updated_at"`               // 更新时间
	UpdaterUID     string    `gorm:"column:updater_uid" json:"updater_uid"`                                     // 更新用户ID
	DeletedAt      int64     `gorm:"column:deleted_at" json:"deleted_at"`                                       // 删除时间(逻辑删除)
}

func (m *DBSandboxApply) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}
	if m.Sid == 0 {
		m.Sid, _ = utilities.GetUniqueID()
	}
	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName DbSandboxApply's table name
func (*DBSandboxApply) TableName() string {
	return TableNameDbSandboxApply
}

func (d *DBSandboxApply) GenLog(step int32) *DBSandboxLog {
	return &DBSandboxLog{
		ApplyID:      d.ID,
		ExecuteStep:  step,
		ExecutorID:   d.ApplicantID,
		ExecutorName: d.ApplicantName,
	}
}
