// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameOperationLog = "operation_log"

// OperationLog mapped from table <operation_log>
type OperationLog struct {
	ID           string `gorm:"column:id" json:"id"`                                // 主键，uuid
	Obj          string `gorm:"column:obj;not null" json:"obj"`                                // 操作对象的模块
	ObjID        string `gorm:"column:obj_id;not null" json:"obj_id"`                          // 操作对象ID
	Name         string `gorm:"column:name;not null" json:"name"`                              //操作名
	Success      bool   `gorm:"column:success;not null" json:"success"`                           //是否成功，默认是成功的
	Result       string `gorm:"column:result" json:"result"`                                   // 操作结果, 成功就是为空，否则显示失败的原因
	CreatedByUID string `gorm:"column:created_by_uid;not null" json:"created_by_uid"`          // 操作者的ID
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	DeletedAt    soft_delete.DeletedAt     `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`   // 删除时间(逻辑删除)
}

func (m *OperationLog) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
