// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameTaskRelationsData = "task_relation_data"

// TaskRelationsData mapped from table <task_relations_data>
type TaskRelationsData struct {
	ID              string                `gorm:"column:id" json:"id"`                                                            // 主键,uuid
	Mid             uint64                `gorm:"column:mid;not null" json:"mid"`                                                 // 雪花id
	TaskID          string                `gorm:"column:task_id;not null" json:"task_id"`                                         // 任务ID
	ProjectID       string                `gorm:"column:project_id;not null" json:"project_id"`                                   // 项目ID
	BusinessModelId string                `gorm:"column:business_model_id;not null" json:"business_model_id"`                     // 主干业务的业务模型ID
	Data            string                `gorm:"column:data" json:"data"`                                                        // json类型字段, 关联数据详情
	UpdatedByUID    string                `gorm:"column:updated_by_uid" json:"updated_by_uid"`                                    // 更新人id
	UpdatedAt       time.Time             `gorm:"column:updated_at;autoUpdateTime;default:current_timestamp()" json:"updated_at"` // 更新时间
	DeletedAt       soft_delete.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`                                   // 删除时间(逻辑删除)
}

// TableName TaskRelationsDatum's table name
func (*TaskRelationsData) TableName() string {
	return TableNameTaskRelationsData
}

func (t *TaskRelationsData) BeforeCreate(_ *gorm.DB) error {
	if t == nil {
		return nil
	}

	if t.Mid == 0 {
		t.Mid, _ = utilities.GetUniqueID()
	}
	if len(t.ID) == 0 {
		t.ID = uuid.NewString()
	}
	return nil
}
