// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameTcFlowInfo = "tc_flow_info"

// TcFlowInfo mapped from table <tc_flow_info>
type TcFlowInfo struct {
	ID                 string `gorm:"column:id" json:"id"`                                   // 主键，uuid
	FlowID             string `gorm:"column:flow_id;not null" json:"flow_id"`                           // 流水线id
	FlowVersion        string `gorm:"column:flow_version;not null" json:"flow_version"`                 // 流水线版本
	FlowName           string `gorm:"column:flow_name;not null" json:"flow_name"`                       // 流水线名称
	NodeCompletionMode string `gorm:"column:node_completion_mode;not null" json:"node_completion_mode"` // 节点完成方式
	NodeStartMode      string `gorm:"column:node_start_mode;not null" json:"node_start_mode"`           // 节点启动方式
	NodeID             string `gorm:"column:node_id;not null" json:"node_id"`                           // 节点后端ID
	NodeName           string `gorm:"column:node_name;not null" json:"node_name"`                       // 节点名称
	NodeUnitID         string `gorm:"column:node_unit_id;not null" json:"node_unit_id"`                 // 节点前端ID
	PrevNodeIds        string `gorm:"column:prev_node_ids;not null" json:"prev_node_ids"`               // 前序节点后端ID数组，逗号分割的数组
	PrevNodeUnitIds    string `gorm:"column:prev_node_unit_ids;not null" json:"prev_node_unit_ids"`     // 前序节点前端ID数组，逗号分割的数组
	TaskCompletionMode string `gorm:"column:task_completion_mode;not null" json:"task_completion_mode"` // 任务完成方式
	//TaskExecRole       string `gorm:"column:task_exec_role;not null" json:"task_exec_role"`             // 任务执行的角色ID
	//TaskExecTools      string                `gorm:"column:task_exec_tools;not null" json:"task_exec_tools"`           // 任务执行的工具，逗号分割的数组
	StageID     string `gorm:"column:stage_id" json:"stage_id"`           // 阶段的后端ID
	StageName   string `gorm:"column:stage_name" json:"stage_name"`       // 阶段名称
	StageOrder  int32  `gorm:"column:stage_order" json:"stage_order"`     // 阶段顺序
	StageUnitID string `gorm:"column:stage_unit_id" json:"stage_unit_id"` // 阶段的前端ID

	TaskType int32 `gorm:"column:task_type;not null" json:"task_type"` // 任务类型数组，取值范围:1 普通任务(默认)，2 新建模型类任务，4 标准化任务。
	WorkOrderType string `gorm:"column:work_order_type;not null" json:"work_order_type"` // 任务类型数组。
}

func (m *TcFlowInfo) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TcFlowInfo's table name
func (*TcFlowInfo) TableName() string {
	return TableNameTcFlowInfo
}
