// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
	"time"
)

const TableNameTcFlowView = "tc_flow_view"

// TcFlowView mapped from table <tc_flow_view>
type TcFlowView struct {
	MID          string                `gorm:"column:mid" json:"mid"`                     // 主键，uuid
	ID           string                `gorm:"column:id;not null" json:"id"`                         // 流水线ID，uuid
	Name         string                `gorm:"column:name;not null" json:"name"`                     // 流水线视图名称
	Version      string                `gorm:"column:version;not null;default:1" json:"version"`     // 流水线版本
	Content      string                `gorm:"column:content" json:"content"`                        // 视图信息：包含位置、形状、大小等
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	CreatedByUID string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                      // 创建用户ID
	UpdatedAt    time.Time             `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp(3)" json:"updated_at"` // 更新时间
	UpdatedByUID string                `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"` // 更新用户ID
}

func (m *TcFlowView) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.MID) == 0 {
		m.MID = uuid.NewString()
	}
	return nil
}

// TableName TcFlowView's table name
func (*TcFlowView) TableName() string {
	return TableNameTcFlowView
}
