// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
	"time"
)

const TableNameTcMember = "tc_member"

// TcMember mapped from table <tc_member>
type TcMember struct {
	ID        string                `gorm:"column:id" json:"id"`               // 主键，uuid
	Obj       int8                  `gorm:"column:obj;not null" json:"obj"`               // 成员对象(项目1,任务2)
	ObjID     string                `gorm:"column:obj_id;not null" json:"obj_id"`         // 对象ID
	RoleID    string                `gorm:"column:role_id" json:"role"`          // 用户角色ID
	UserID    string                `gorm:"column:user_id;not null" json:"user_id"`       // 成员ID
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"` // 删除时间(逻辑删除)
}

func (m *TcMember) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TcMember's table name
func (*TcMember) TableName() string {
	return TableNameTcMember
}
