// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameTcOss = "tc_oss"

// TcOss mapped from table <tc_oss>
type TcOss struct {
	ID        string    `gorm:"column:id" json:"id"`                                                // 主键，uuid
	Appendix  string    `gorm:"column:appendix;not null" json:"appendix"`                                      // 对象类型
	Size      int64     `gorm:"column:size;not null" json:"size"`                                              // 对象尺寸
	FileUUID  string   `gorm:"column:file_uuid" json:"file_uuid"`                                             // 文件UUID
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"`     // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp(3)" json:"updated_at"`     // 更新时间
	DeletedAt soft_delete.DeletedAt     `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"` // 删除时间(逻辑删除)
}

func (m *TcOss) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TcOss's table name
func (*TcOss) TableName() string {
	return TableNameTcOss
}
