// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"gorm.io/plugin/soft_delete"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameTcProject = "tc_project"

// TcProject mapped from table <tc_project>
type TcProject struct {
	ID           string                `gorm:"column:id" json:"id"`                                            // 主键，uuid
	Name         string                `gorm:"column:name;not null" json:"name"`                                          // 项目名称
	Description  sql.NullString        `gorm:"column:description" json:"description"`                                     // 项目描述
	Image        sql.NullString        `gorm:"column:image" json:"image"`                                                 // 项目图片
	FlowID       string                `gorm:"column:flow_id;not null" json:"flow_id"`                                    // 流水线id
	FlowVersion  string                `gorm:"column:flow_version;not null" json:"flow_version"`                          // 流水线版本
	Status       int8                  `gorm:"column:status;default:1" json:"status"`                                     // 项目状态（未开始1、进行中2、已完成3)
	Priority     int8                  `gorm:"column:priority;default:1" json:"priority"`                                 // 项目优先级（普通1、紧急2、非常紧急3)
	OwnerID      string                `gorm:"column:owner_id;not null" json:"owner_id"`                                  // 项目负责人id
	Deadline     sql.NullInt64         `gorm:"column:deadline" json:"deadline"`                                           // 项目截止时间
	ProjectType  int32                 `gorm:"column:project_type" json:"project_type"`                                   // 项目类型，见枚举中定义任务类型
	CompleteTime int64                 `gorm:"column:complete_time" json:"complete_time"`                                 // 项目完成时间
	CreatedByUID string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                      // 创建人id
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	UpdatedByUID string                `gorm:"column:updated_by_uid" json:"updated_by_uid"`                               // 更新人id
	UpdatedAt    time.Time             `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp(3)" json:"updated_at"` // 更新时间
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`             // 删除时间(逻辑删除)
	ThirdProjectId  string    `gorm:"column:third_project_id"json:"third_project_id"`                                        //第三方项目ID
}

func (m *TcProject) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TcProject's table name
func (*TcProject) TableName() string {
	return TableNameTcProject
}

type ProjectWorkitems struct {
	ID               string         `gorm:"column:id" json:"id"`                                            // 主键，uuid
	Name             string         `gorm:"column:name;not null" json:"name"`                                          // 任务名称，可以重复
	Type             string         `gorm:"column:type" json:"type"`                                                   // 任务或者工单（task、work-orde）
	SubType          int32          `gorm:"column:sub_type" json:"sub_type"`                                           // 任务类型，见枚举中定义任务类型
	StageID          string         `gorm:"column:stage_id" json:"stage_id"`                                           //阶段id
	NodeID           string         `gorm:"column:node_id;not null" json:"node_id"`                                    // 节点id
	Status           int8           `gorm:"column:status;default:1" json:"status"`                                     // 任务状态（未开始1、进行中2、已完成3)
	ExecutorID       sql.NullString `gorm:"column:executor_id;not null" json:"executor_id"`                            // 任务执行人id
	Deadline         sql.NullInt64  `gorm:"column:deadline;default:null" json:"deadline"`                              // 任务截止时间
	UpdatedByUID     string         `gorm:"column:updated_by_uid" json:"updated_by_uid"`                               // 更新人id
	UpdatedAt        time.Time      `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp(3)" json:"updated_at"` // 更新时间
	AuditStatus      int32          `gorm:"column:audit_status" json:"audit_status"`                                   // 审核状态
	AuditDescription string         `gorm:"column:audit_description" json:"audit_description"`                         // 审核描述
	// 工单是否已经同步到第三方，例如华傲
	Synced bool `json:"synced,omitempty" gorm:"column:synced;not null;default:false"`
}
