// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameTcTask = "tc_task"

// TcTask mapped from table <tc_task>
type TcTask struct {
	ID               string                `gorm:"column:id" json:"id"`                                            // 主键，uuid
	Name             string                `gorm:"column:name;not null" json:"name"`                                          // 任务名称，可以重复
	Description      sql.NullString        `gorm:"column:description" json:"description"`                                     // 任务描述
	ProjectID        string                `gorm:"column:project_id;not null" json:"project_id"`                              // 项目id
	WorkOrderId      string                `gorm:"column:work_order_id;not null" json:"work_order_id"`                        // 工单id
	FlowID           string                `gorm:"column:flow_id" json:"flow_id"`                                             // 流水线id
	FlowVersion      string                `gorm:"column:flow_version" json:"flow_version"`                                   // 流水线版本
	StageID          string                `gorm:"column:stage_id" json:"stage_id"`                                           //阶段id
	NodeID           string                `gorm:"column:node_id;not null" json:"node_id"`                                    // 节点id
	Status           int8                  `gorm:"column:status;default:1" json:"status"`                                     // 任务状态（未开始1、进行中2、已完成3)
	ConfigStatus     int8                  `gorm:"column:config_status" json:"config_status"`                                 //  任务配置状态，默认1正常，2业务域缺失，3主干业务缺失
	ExecutableStatus int8                  `gorm:"column:executable_status" json:"executable_status"`                         //  任务配置状态，默认1正常，2业务域缺失，3主干业务缺失
	Priority         int8                  `gorm:"column:priority;default:1" json:"priority"`                                 // 任务优先级（普通1、紧急2、非常紧急3)
	ExecutorID       sql.NullString        `gorm:"column:executor_id;not null" json:"executor_id"`                            // 任务执行人id
	Deadline         sql.NullInt64         `gorm:"column:deadline;default:null" json:"deadline"`                              // 任务截止时间
	CompleteTime     int64                 `gorm:"column:complete_time" json:"complete_time"`                                 // 任务完成时间
	CreatedByUID     string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                      // 创建人id
	CreatedAt        time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	UpdatedByUID     string                `gorm:"column:updated_by_uid" json:"updated_by_uid"`                               // 更新人id
	UpdatedAt        time.Time             `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp(3)" json:"updated_at"` // 更新时间
	DeletedAt        soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`             // 删除时间(逻辑删除)

	OrgType                     *int   `gorm:"column:org_type" json:"org_type"`                                             //标准分类
	TaskType                    int32  `gorm:"column:task_type" json:"task_type"`                                           // 任务类型，见枚举中定义任务类型
	SubjectDomainId             string `gorm:"column:subject_domain_id" json:"subject_domain_id"`                           // 主题域id
	BusinessModelID             string `gorm:"column:business_model_id" json:"business_model_id"`                           // 任务类型为业务模型&数据模型时存储主干业务ID，采集任务时存储模型ID
	ParentTaskId                string `gorm:"column:parent_task_id" json:"parent_task_id"`                                 // 父任务的ID
	DataComprehensionCatalogId  string `gorm:"column:data_comprehension_catalog_id" json:"data_comprehension_catalog_id"`   // 数据目录理解任务关联数据资源目录id
	DataComprehensionTemplateId string `gorm:"column:data_comprehension_template_id" json:"data_comprehension_template_id"` // 数据目录理解任务关联数据理解模板id
	ModelChildTaskTypes         string   `gorm:"column:model_child_task_types" json:"model_child_task_types"` //业务模型&数据模型的子类型数组，每个模型最多5个子类型。业务模型子类型：1录入流程图、2录入节点表、3录入标准表、4录入指标表、5业务标准表标准化；数据模型子类型：6录入数据来源表、7录入数据标准表、8录入数据融合表、9录入数据统计指标、10数据标准表标准化
}

func (m *TcTask) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName TcTask's table name
func (*TcTask) TableName() string {
	return TableNameTcTask
}
