// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTcTenantAppDbDataResource = "tc_tenant_app_db_data_resource"

// TcTenantAppDbDataResource 租户申请数据库账号数据资源
type TcTenantAppDbDataResource struct {
	DataResourceID      uint64    `gorm:"column:data_resource_id;comment:数据资源id, 雪花id" json:"data_resource_id"`    // 数据资源id, 雪花id
	ID                  string    `gorm:"column:id;comment:id, uuid" json:"id"`                                    // id, uuid
	TenantApplicationID string    `gorm:"column:tenant_application_id;comment:申请id" json:"tenant_application_id"`  // 申请id
	DatabaseAccountID   string    `gorm:"column:database_account_id;comment:数据库账号id" json:"database_account_id"`   // 数据库账号id
	DataCatalogID       string    `gorm:"column:data_catalog_id;comment:数据目录id" json:"data_catalog_id"`            // 数据目录id
	DataCatalogName     string    `gorm:"column:data_catalog_name;comment:数据目录名称" json:"data_catalog_name"`        // 数据目录名称
	DataCatalogCode     string    `gorm:"column:data_catalog_code;comment:数据目录编码" json:"data_catalog_code"`        // 数据目录编码
	MountResourceID     string    `gorm:"column:mount_resource_id;comment:挂载资源id" json:"mount_resource_id"`        // 挂载资源id
	MountResourceName   string    `gorm:"column:mount_resource_name;comment:挂载资源名字" json:"mount_resource_name"`    // 挂载资源名字
	MountResourceCode   string    `gorm:"column:mount_resource_code;comment:挂载资源编码" json:"mount_resource_code"`    // 挂载资源编码
	DataSourceID        string    `gorm:"column:data_source_id;comment:数据源id" json:"data_source_id"`               // 数据源id
	DataSourceName      string    `gorm:"column:data_source_name;comment:数据源" json:"data_source_name"`             // 数据源
	ApplyPermission     string    `gorm:"column:apply_permission;comment:申请权限 read write" json:"apply_permission"` // 申请权限 read write
	ApplyPurpose        string    `gorm:"column:apply_purpose;comment:申请用途" json:"apply_purpose"`                  // 申请用途
	CreatedByUID        string    `gorm:"column:created_by_uid;comment:创建者" json:"created_by_uid"`                 // 创建者
	CreatedAt           time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                        // 创建时间
	UpdatedByUID        string    `gorm:"column:updated_by_uid;comment:更新者" json:"updated_by_uid"`                 // 更新者
	UpdatedAt           time.Time `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp();comment:更新时间" json:"updated_at"`                        // 更新时间
	DeletedAt           int32     `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                        // 删除时间
}

// TableName TcTenantAppDbDataResource's table name
func (*TcTenantAppDbDataResource) TableName() string {
	return TableNameTcTenantAppDbDataResource
}
