// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTcTenantAppDbAccount = "tc_tenant_app_db_account"

// TcTenantAppDbAccount 租户申请数据库账号
type TcTenantAppDbAccount struct {
	DatabaseAccountID        uint64    `gorm:"column:database_account_id;comment:数据库账号id" json:"database_account_id"`                     // 数据库账号id
	ID                       string    `gorm:"column:id;comment:id， uuid" json:"id"`                                                      // id， uuid
	TenantApplicationID      string    `gorm:"column:tenant_application_id;comment:租户申请id" json:"tenant_application_id"`                  // 租户申请id
	DatabaseType             string    `gorm:"column:database_type;comment:数据库类型" json:"database_type"`                                   // 数据库类型
	DatabaseName             string    `gorm:"column:database_name;comment:数据库名称" json:"database_name"`                                   // 数据库名称
	TenantAccount            string    `gorm:"column:tenant_account;comment:租户账号" json:"tenant_account"`                                  // 租户账号
	TenantPasswd             string    `gorm:"column:tenant_passwd;comment:租户密码" json:"tenant_passwd"`                                    // 租户密码
	ProjectName              string    `gorm:"column:project_name;comment:项目名称" json:"project_name"`                                      // 项目名称
	ActualAllocatedResources string    `gorm:"column:actual_allocated_resources;comment:实际分配资源" json:"actual_allocated_resources"`        // 实际分配资源
	UserAuthenticationHadoop string    `gorm:"column:user_authentication_hadoop;comment:用户认证信息 hadoop" json:"user_authentication_hadoop"` // 用户认证信息 hadoop
	UserAuthenticationHbase  string    `gorm:"column:user_authentication_hbase;comment:用户授权信息 hbase" json:"user_authentication_hbase"`    // 用户授权信息 hbase
	UserAuthenticationHive   string    `gorm:"column:user_authentication_hive;comment:用户授权信息 hive" json:"user_authentication_hive"`       // 用户授权信息 hive
	CreatedByUID             string    `gorm:"column:created_by_uid;comment:创建者" json:"created_by_uid"`                                   // 创建者
	CreatedAt                time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                          // 创建时间
	UpdatedByUID             string    `gorm:"column:updated_by_uid;comment:更新者" json:"updated_by_uid"`                                   // 更新者
	UpdatedAt                time.Time `gorm:"column:updated_at;autoUpdateTime;not null;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt                int32     `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                          // 删除时间
}

// TableName TcTenantAppDbAccount's table name
func (*TcTenantAppDbAccount) TableName() string {
	return TableNameTcTenantAppDbAccount
}
