// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTcTenantApp = "tc_tenant_app"

// TcTenantApp mapped from table <tc_tenant_app>
type TcTenantApp struct {
	TenantApplicationID          uint64    `gorm:"column:tenant_application_id;not null;comment:租户申请id, 雪花id" json:"tenant_application_id"`       // 租户申请id, 雪花id
	ID                           string    `gorm:"column:id;comment:id， uuid" json:"id"`                                                          // id， uuid
	ApplicationName              string    `gorm:"column:application_name;comment:租户申请名称" json:"application_name"`                                // 租户申请名称
	ApplicationCode              string    `gorm:"column:application_code;comment:申请单编码" json:"application_code"`                                 // 申请单编码
	TenantName                   string    `gorm:"column:tenant_name;comment:租户名称" json:"tenant_name"`                                            // 租户名称
	TenantAdminID                string    `gorm:"column:tenant_admin_id;comment:租户管理员" json:"tenant_admin_id"`                                   // 租户管理员
	BusinessUnitID               string    `gorm:"column:business_unit_id;comment:业务单位id" json:"business_unit_id"`                                // 业务单位id
	BusinessUnitContactorID      string    `gorm:"column:business_unit_contactor_id;comment:业务单位联系人" json:"business_unit_contactor_id"`           // 业务单位联系人
	BusinessUnitPhone            string    `gorm:"column:business_unit_phone;comment:业务单位联系电话" json:"business_unit_phone"`                        // 业务单位联系电话
	BusinessUnitEmail            string    `gorm:"column:business_unit_email;comment:业务单位邮箱" json:"business_unit_email"`                          // 业务单位邮箱
	BusinessUnitFax              string    `gorm:"column:business_unit_fax;comment:业务单位传真" json:"business_unit_fax"`                              // 业务单位传真
	MaintenanceUnitID            string    `gorm:"column:maintenance_unit_id;comment:维护单位id" json:"maintenance_unit_id"`                          // 维护单位id
	MaintenanceUnitName          string    `gorm:"column:maintenance_unit_name;comment:维护单位名称" json:"maintenance_unit_name"`                      // 维护单位名称
	MaintenanceUnitContactorID   string    `gorm:"column:maintenance_unit_contactor_id;comment:维护单位联系人" json:"maintenance_unit_contactor_id"`     // 维护单位联系人
	MaintenanceUnitContactorName string    `gorm:"column:maintenance_unit_contactor_name;comment:维护单位联系人" json:"maintenance_unit_contactor_name"` // 维护单位联系人
	MaintenanceUnitPhone         string    `gorm:"column:maintenance_unit_phone;comment:维护单位联系电话" json:"maintenance_unit_phone"`                  // 维护单位联系电话
	MaintenanceUnitEmail         string    `gorm:"column:maintenance_unit_email;comment:维护单位邮箱" json:"maintenance_unit_email"`                    // 维护单位邮箱
	Status                       int       `gorm:"column:status;comment:状态，1 未申报， 2 待激活， 3 已激活， 4 已禁用" json:"status"`                             // 状态，1 未申报， 2 待激活， 3 已激活， 4 已禁用
	AuditID                      *uint64   `gorm:"column:audit_id;comment:审核记录ID" json:"audit_id"`                                                // 审核记录ID
	AuditProcInstID              string    `gorm:"col*mn:audit_proc_inst_id;comment:审核实例ID" json:"audit_proc_inst_id"`                            // 审核实例ID
	AuditResult                  *string   `gorm:"column:audit_result;comment:审核结果 agree 通过 reject 拒绝 undone 撤销" json:"audit_result"`             // 审核结果 agree 通过 reject 拒绝 undone 撤销
	RejectReason                 string    `gorm:"column:reject_reason;comment:驳回原因" json:"reject_reason"`                                        // 驳回原因
	CancelReason                 string    `gorm:"column:cancel_reason;comment:需求撤销原因" json:"cancel_reason"`                                      // 需求撤销原因
	DeclarationStatus            *int32    `gorm:"column:declaration_status;comment:申报状态【1:待申报  2：已申报】" json:"declaration_status"`                // 申报状态【1:待申报  2：已申报】
	AuditStatus                  *int32    `gorm:"column:audit_status;comment:审核状态" json:"audit_status"`                                          // 审核状态
	CreatedByUID                 string    `gorm:"column:created_by_uid;comment:创建者id" json:"created_by_uid"`                                     // 创建者id
	CreatedAt                    time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                              // 创建时间
	UpdatedByUID                 string    `gorm:"column:updated_by_uid;comment:更新者id" json:"updated_by_uid"`                                     // 更新者id
	UpdatedAt                    time.Time `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp();comment:更新时间" json:"updated_at"`                                              // 更新时间
	DeletedAt                    int32     `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                              // 删除时间
}

// TableName TcTenantApp's table name
func (*TcTenantApp) TableName() string {
	return TableNameTcTenantApp
}
