// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserSingle = "user"

// User mapped from table <user>
type UserSingle struct {
	ID          string    `gorm:"column:id" json:"id"` // 主键，uuid
	Name        string    `gorm:"column:name" json:"name"`
	Status      int32     `gorm:"column:status;not null;default:1;comment:用户状态,1正常,2删除" json:"status"`           // 用户状态,1正常,2删除
	UserType    int32     `gorm:"column:user_type;not null;default:1;comment:用户类型,1普通账号,2应用账号" json:"user_type"` // 用户类型,1普通账号,2应用账号
	PhoneNumber string    `gorm:"column:phone_number" json:"phone_number"`                                       // 手机号码
	MailAddress string    `gorm:"column:mail_address" json:"mail_address"`                                       // 邮箱地址
	LoginName   string    `gorm:"column:login_name" json:"login_name"`                                           // 登录名称
	Scope       string    `gorm:"column:scope" json:"scope"`                                                     // 权限范围
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:current_timestamp(3)" json:"updated_at"`     // 更新时间
	ThirdUserId string    `gorm:"column:f_third_user_id" json:"third_user_id"`
	UpdatedBy   string    `gorm:"column:updated_by" json:"updated_by"` // 更新人id
	// 注册时间
	RegisterAt string `gorm:"column:register_at;not null;default:current_timestamp(3)" json:"register_at"`
	// 是否注册
	IsRegistered int32 `gorm:"column:is_registered;not null;default:0" json:"registered"`
	// 第三方服务ID
	ThirdServiceId string `gorm:"column:third_service_id" json:"third_service_id"`
}

func (m *UserSingle) UniqueKey() string {
	return "id"
}

// TableName User's table name
func (*UserSingle) TableName() string {
	return TableNameUserSingle
}

type UserWithPhoneNumber struct {
	// ID
	ID string `gorm:"column:id" json:"id,omitempty"`
	// 手机号码
	PhoneNumber string `gorm:"column:phone_number" json:"phone_number,omitempty"`
}
