// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       string `gorm:"column:id" json:"id"` // 主键，uuid
	Name     string `gorm:"column:name" json:"name"`
	Status   int32  `gorm:"column:status;not null;default:1;comment:用户状态,1正常,2删除" json:"status"`           // 用户状态,1正常,2删除
	UserType int32  `gorm:"column:user_type;not null;default:1;comment:用户类型,1普通账号,2应用账号" json:"user_type"` // 用户类型,1普通账号,2应用账号
}

func (m *User) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}
	return nil
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
