// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/plugin/soft_delete"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameWorkOrder = "work_order"

// WorkOrder mapped from table <work_order>
type WorkOrder struct {
	ID                         uint64     `gorm:"column:id" json:"id"`                                                              // 雪花id
	WorkOrderID                string     `gorm:"column:work_order_id;not null" json:"work_order_id"`                               // 工单id
	Name                       string     `gorm:"column:name;not null" json:"name"`                                                 // 工单名称
	Code                       string     `gorm:"column:code;not null" json:"code"`                                                 // 工单编号
	DepartmentId               string     `gorm:"column:department_id;comment:所属部门id" json:"department_id"`                         // 所属部门(创建人部门id)
	DataSourceDepartmentId     string     `gorm:"column:data_source_department_id;comment:所属部门id" json:"data_source_department_id"` // 数源部门（质量整改工单使用）
	Type                       int32      `gorm:"column:type;not null" json:"type"`                                                 // 工单类型
	Status                     int32      `gorm:"column:status;not null" json:"status"`                                             // 工单状态
	Draft                      *bool      `gorm:"column:draft;not null" json:"draft,omitempty"`                                     // 是否为草稿，使用指针，避免 gorm 零值更新问题
	ResponsibleUID             string     `gorm:"column:responsible_uid" json:"responsible_uid"`                                    // 责任人
	Priority                   int32      `gorm:"column:priority" json:"priority"`                                                  // 优先级
	FinishedAt                 *time.Time `gorm:"column:finished_at" json:"finished_at"`                                            // 截止日期
	CatalogIds                 string     `gorm:"column:catalog_ids" json:"catalog_ids"`                                            // 关联数据资源目录
	DataAggregationInventoryID string     `gorm:"column:data_aggregation_inventory_id" json:"data_aggregation_inventory_id"`        // 关联的数据归集清单 ID，工单类型是数据归集时有值
	// Deprecated: 使用 data_aggregation_resource 记录来源是业务表的数据归集工单的归集数据
	BusinessForms          []byte                `gorm:"column:business_forms;serializer:json"`                                                   // 归集工单关联的业务表列表
	Description            string                `gorm:"column:description" json:"description"`                                                   // 工单说明
	Remark                 string                `gorm:"column:remark" json:"remark"`                                                             // 备注
	ProcessingInstructions string                `gorm:"column:processing_instructions" json:"processing_instructions"`                           // 处理说明
	AuditID                *uint64               `gorm:"column:audit_id" json:"audit_id"`                                                         // 审核id
	AuditStatus            int32                 `gorm:"column:audit_status" json:"audit_status"`                                                 // 审核状态
	AuditDescription       string                `gorm:"column:audit_description" json:"audit_description"`                                       // 审核描述
	SourceType             int32                 `gorm:"column:source_type" json:"source_type"`                                                   // 来源类型
	SourceID               string                `gorm:"column:source_id" json:"source_id"`                                                       // 来源id
	SourceIDs              []string              `gorm:"column:source_ids;serializer:json" json:"source_ids"`                                     // 来源id列表
	ReportID               string                `gorm:"column:report_id" json:"report_id"`                                                       // 报告id
	ReportVersion          int32                 `gorm:"column:report_version" json:"report_version"`                                             // 报告版本
	ReportAt               *time.Time            `gorm:"column:report_at" json:"report_at"`                                                       // 报告生成时间
	RejectReason           string                `gorm:"column:reject_reason" json:"reject_reason"`                                               // 驳回理由
	CreatedByUID           string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                                    // 创建人
	CreatedAt              time.Time             `gorm:"column:created_at;not null" json:"created_at"`                                            // 创建时间
	UpdatedByUID           string                `gorm:"column:updated_by_uid" json:"updated_by_uid"`                                             // 更新人
	UpdatedAt              time.Time             `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp()" json:"updated_at"` // 更新时间
	AcceptanceAt           *time.Time            `gorm:"column:acceptance_at" json:"acceptance_at"`                                               // 签收时间
	ProcessAt              *time.Time            `gorm:"column:process_at" json:"process_at"`                                                     // 签收时间
	Remind                 int32                 `gorm:"column:remind" json:"remind"`                                                             // 催办
	Score                  int32                 `gorm:"column:score" json:"score"`                                                               // 得分
	FeedbackContent        string                `gorm:"column:feedback_content" json:"feedback_content"`                                         // 反馈内容
	FeedbackAt             *time.Time            `gorm:"column:feedback_at" json:"feedback_at"`                                                   // 反馈时间
	FeedbackBy             string                `gorm:"column:feedback_by" json:"feedback_by"`                                                   // 反馈人
	DeletedAt              soft_delete.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`                                            // 删除时间
	// 工单是否已经同步到第三方，例如华傲
	Synced bool `json:"synced,omitempty" gorm:"column:synced;not null;default:false"`
	// 工单所属项目的运营流程节点 ID，仅当来源是项目时有值
	NodeID string `json:"node_id,omitempty" gorm:"column:node_id;default:null"`
	// 工单所属项目的运营流程阶段 ID，仅当来源是项目时有值
	StageID string `json:"stage_id,omitempty" gorm:"column:stage_id;default:null"`
}

func (m *WorkOrder) BeforeSave(_ *gorm.DB) error {
	if m.SourceID != "" && len(m.SourceIDs) == 0 {
		m.SourceIDs = []string{m.SourceID}
	}
	if m.SourceID == "" && len(m.SourceIDs) != 0 {
		m.SourceID = m.SourceIDs[0]
	}
	return nil
}

func (m *WorkOrder) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, _ = utilities.GetUniqueID()
	}
	if len(m.WorkOrderID) == 0 {
		m.WorkOrderID = uuid.NewString()
	}
	return nil
}

func (m *WorkOrder) AfterFind(_ *gorm.DB) error {
	if m.SourceID != "" && len(m.SourceIDs) == 0 {
		m.SourceIDs = []string{m.SourceID}
	}
	if m.SourceID == "" && len(m.SourceIDs) != 0 {
		m.SourceID = m.SourceIDs[0]
	}
	return nil
}

// TableName WorkOrder's table name
func (*WorkOrder) TableName() string {
	return TableNameWorkOrder
}
