// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConfiguration = "configuration"

// Configuration mapped from table <configuration>
type Configuration struct {
	Key   string `gorm:"column:key;primaryKey" json:"key"`
	Value string `gorm:"column:value;not null" json:"value"`
	Type  int32  `gorm:"column:type;not null;default:0" json:"type"` // 第三方地址类型，枚举：1：带路径；2：不带路径；
}

// TableName Configuration's table name
func (*Configuration) TableName() string {
	return TableNameConfiguration
}
