// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	ID       uint64 `gorm:"column:id;primaryKey;comment:菜单id" json:"id"`                          //菜单id
	Platform int32  `gorm:"column:platform;not null;comment:菜单归属平台 1：标品 2：xx数据局" json:"platform"` //菜单归属平台 1：标品 2：xx数据局
	Value    string `gorm:"column:value;not null;comment:菜单信息" json:"value"`                      //菜单信息
}

func (m *Menu) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, _ = utils.GetUniqueID()
	}

	return nil
}

// TableName Resource's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
