// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/plugin/soft_delete"
	"time"

	"gorm.io/gorm"
)

const TableNameTDict = "t_dict"

// TDict mapped from table <t_dict>
type TDict struct {
	ID           uint64                `gorm:"column:id;primaryKey" json:"id"`            // 唯一id，雪花算法
	FType        string                `gorm:"column:f_type;not null" json:"f_type"`      // 字典类型
	Name         string                `gorm:"column:name;not null" json:"name"`          // 字典名称
	FDescription string                `gorm:"column:f_description" json:"f_description"` // 描述
	FVersion     string                `gorm:"column:f_version;not null;default:'V1.0.0'" json:"f_version"`
	CreatedAt    time.Time             `gorm:"column:created_at;not null" json:"created_at"` // 创建时间
	CreatorUID   string                `gorm:"column:creator_uid" json:"creator_uid"`        // 创建用户ID
	CreatorName  string                `gorm:"column:creator_name" json:"creator_name"`      // 创建用户名称
	UpdatedAt    time.Time             `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`          // 更新时间
	UpdaterUID   string                `gorm:"column:updater_uid" json:"updater_uid"`        // 更新用户ID
	UpdaterName  string                `gorm:"column:updater_name" json:"updater_name"`      // 更新用户名称
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`
	SszdFlag     int32                 `gorm:"column:sszd_flag;not null;default:1" json:"sszd_flag"` // 是否省市直达1是0否
}

func (m *TDict) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, _ = utils.GetUniqueID()
	}

	return nil
}

// TableName TDict's table name
func (*TDict) TableName() string {
	return TableNameTDict
}
