// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"time"

	"gorm.io/gorm"
)

const TableNameTDictItem = "t_dict_item"

// TDictItem mapped from table <t_dict_item>
type TDictItem struct {
	ID           uint64    `gorm:"column:id;primaryKey" json:"id"`               // 唯一id，雪花算法
	DictID       uint64    `gorm:"column:dict_id;not null" json:"dict_id"`       // 字典ID
	FType        string    `gorm:"column:f_type;not null" json:"f_type"`         // 字典类型 area 所属领域、应用领域【应用系统】 scene 应用场景 scene-type 应用场景类型 one-thing 高效办成“一件事” range 应用范围 sensitive-level 敏感级别 catalog-share-type 数据目录共享类型 catalog-open-type 数据目录开放类型 resource-share-type 数据资源共享类型 resource-open-type 数据资源开放类型 resource-type 数据资源类型 column-type 字段类型 serve-type 服务类型 use-scope 使用范围 update-cycle 更新周期 publish 是否发布 share-type 共享类型 data-region 数据区域范围 level-type 数据所属层级 open-type 开放类型 certification-type 是否电子证照编码 net-type 提供渠道 data-processing 数据加工程度 data-backflow 是否回流地市（州） backflow-region 回流是否能区分地市（州） field-type 数据所属领域 org-code 统一社会信用代码 division-code 行政区划代码 center-dept-code 中央业务指导（实施）部门代码 data-sensitive-class 数据分级 catalog-tag 目录标签 system-class 系统所属分类
	FKey         string    `gorm:"column:f_key;not null" json:"f_key"`           // 键（字典码）
	FValue       string    `gorm:"column:f_value;not null" json:"f_value"`       // 值（值名称）
	FDescription string    `gorm:"column:f_description" json:"f_description"`    // 备注
	FSort        int32     `gorm:"column:f_sort;not null" json:"f_sort"`         // 排序（升序）
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"` // 创建时间
	CreatorUID   string    `gorm:"column:creator_uid" json:"creator_uid"`        // 创建用户ID
	CreatorName  string    `gorm:"column:creator_name" json:"creator_name"`      // 创建用户名称
}

func (m *TDictItem) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, _ = utils.GetUniqueID()
	}

	return nil
}

// TableName TDictItem's table name
func (*TDictItem) TableName() string {
	return TableNameTDictItem
}
