// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"time"

	"gorm.io/gorm"
)

const TableNameTFirm = "t_firm"

// TFirm mapped from table <t_firm>
type TFirm struct {
	ID             uint64                `gorm:"column:id;primaryKey" json:"id"`                         // 唯一id，雪花算法
	Name           string                `gorm:"column:name;not null" json:"name"`                       // 厂商名称
	UniformCode    string                `gorm:"column:uniform_code;not null" json:"uniform_code"`       // 统一社会信用代码
	LegalRepresent string                `gorm:"column:legal_represent;not null" json:"legal_represent"` // 法定代表名称
	ContactPhone   string                `gorm:"column:contact_phone;not null" json:"contact_phone"`     // 联系电话
	CreatedAt      time.Time             `gorm:"column:created_at;not null" json:"created_at"`           // 创建时间
	CreatedBy      string                `gorm:"column:created_by;not null" json:"created_by"`           // 创建用户ID
	UpdatedAt      *time.Time             `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`                   // 更新时间
	UpdatedBy      *string                `gorm:"column:updated_by" json:"updated_by"`                   // 更新用户ID
	DeletedAt      *time.Time             `gorm:"column:deleted_at" json:"deleted_at"`                   // 删除时间
	DeletedBy      *string                `gorm:"column:deleted_by" json:"deleted_by"`                   // 删除用户ID
}

func (m *TFirm) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, _ = utils.GetUniqueID()
	}

	return nil
}

// TableName TFirm's table name
func (*TFirm) TableName() string {
	return TableNameTFirm
}
